lappend pragmaStatus0 {pragma "INLINE" source "/home/yx388/ece5775/final_project/ECE5775_Final_Project/ecelinux_dummy/dut.cpp" location "vm2x1_base" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'INLINE' cannot be applied: Function 'vm2x1_base' does not exist in any synthesis source file."}
lappend pragmaStatus1 {pragma "PIPELINE" source "/home/yx388/ece5775/final_project/ECE5775_Final_Project/ecelinux_dummy/dut.cpp" location "svd_alt/rd_buffer" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus2 {pragma "PIPELINE" source "/home/yx388/ece5775/final_project/ECE5775_Final_Project/ecelinux_dummy/dut.cpp" location "svd_alt/svd_rd_diag" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus3 {pragma "PIPELINE" source "/home/yx388/ece5775/final_project/ECE5775_Final_Project/ecelinux_dummy/dut.cpp" location "calc_svd/svd_calc_diag" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus4 {pragma "PIPELINE" source "/home/yx388/ece5775/final_project/ECE5775_Final_Project/ecelinux_dummy/dut.cpp" location "svd_alt/svd_wb_diag" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus5 {pragma "PIPELINE" source "/home/yx388/ece5775/final_project/ECE5775_Final_Project/ecelinux_dummy/dut.cpp" location "svd_alt/svd_rd_off_r" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus6 {pragma "PIPELINE" source "/home/yx388/ece5775/final_project/ECE5775_Final_Project/ecelinux_dummy/dut.cpp" location "update_off_diag_r/svd_calc_off_r" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus7 {pragma "PIPELINE" source "/home/yx388/ece5775/final_project/ECE5775_Final_Project/ecelinux_dummy/dut.cpp" location "svd_alt/svd_wb_off_r" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus8 {pragma "PIPELINE" source "/home/yx388/ece5775/final_project/ECE5775_Final_Project/ecelinux_dummy/dut.cpp" location "svd_alt/svd_rd_off_c" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus9 {pragma "PIPELINE" source "/home/yx388/ece5775/final_project/ECE5775_Final_Project/ecelinux_dummy/dut.cpp" location "update_off_diag_c/svd_calc_off_c" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus10 {pragma "PIPELINE" source "/home/yx388/ece5775/final_project/ECE5775_Final_Project/ecelinux_dummy/dut.cpp" location "svd_alt/svd_wb_off_c" found 0 funcFound 1 applied 0 ambiguous 0 reason "Directive 'PIPELINE' cannot be applied: Label 'svd_wb_off_c' does not exist in function 'svd_alt'. "}
lappend pragmaStatus11 {pragma "PIPELINE" source "/home/yx388/ece5775/final_project/ECE5775_Final_Project/ecelinux_dummy/dut.cpp" location "svd_alt/wb_buffer" found 0 funcFound 1 applied 0 ambiguous 0 reason "Directive 'PIPELINE' cannot be applied: Label 'wb_buffer' does not exist in function 'svd_alt'. "}
lappend pragmaStatus12 {pragma "PIPELINE" source "/home/yx388/ece5775/final_project/ECE5775_Final_Project/ecelinux_dummy/dut.cpp" location "matmul/LOOP_ST_A" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'PIPELINE' cannot be applied: Function 'matmul' does not exist in any synthesis source file."}
lappend pragmaStatus13 {pragma "PIPELINE" source "/home/yx388/ece5775/final_project/ECE5775_Final_Project/ecelinux_dummy/dut.cpp" location "matmul/LOOP_DOT_PROD" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'PIPELINE' cannot be applied: Function 'matmul' does not exist in any synthesis source file."}
lappend pragmaStatus14 {pragma "PIPELINE" source "/home/yx388/ece5775/final_project/ECE5775_Final_Project/ecelinux_dummy/dut.cpp" location "backproj/LOOP_ST_A" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'PIPELINE' cannot be applied: Function 'backproj' does not exist in any synthesis source file."}
lappend pragmaStatus15 {pragma "PIPELINE" source "/home/yx388/ece5775/final_project/ECE5775_Final_Project/ecelinux_dummy/dut.cpp" location "backproj/LOOP_DOT_PROD" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'PIPELINE' cannot be applied: Function 'backproj' does not exist in any synthesis source file."}
lappend pragmaStatus0 {pragma "INLINE" source "/home/yx388/ece5775/final_project/ECE5775_Final_Project/ecelinux_dummy/pca.cpp" location "vm2x1_base" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'INLINE' cannot be applied: Function 'vm2x1_base' does not exist in any synthesis source file."}
lappend pragmaStatus1 {pragma "PIPELINE" source "/home/yx388/ece5775/final_project/ECE5775_Final_Project/ecelinux_dummy/pca.cpp" location "svd_alt/rd_buffer" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus2 {pragma "PIPELINE" source "/home/yx388/ece5775/final_project/ECE5775_Final_Project/ecelinux_dummy/pca.cpp" location "svd_alt/svd_rd_diag" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus3 {pragma "PIPELINE" source "/home/yx388/ece5775/final_project/ECE5775_Final_Project/ecelinux_dummy/pca.cpp" location "calc_svd/svd_calc_diag" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus4 {pragma "PIPELINE" source "/home/yx388/ece5775/final_project/ECE5775_Final_Project/ecelinux_dummy/pca.cpp" location "svd_alt/svd_wb_diag" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus5 {pragma "PIPELINE" source "/home/yx388/ece5775/final_project/ECE5775_Final_Project/ecelinux_dummy/pca.cpp" location "svd_alt/svd_rd_off_r" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus6 {pragma "PIPELINE" source "/home/yx388/ece5775/final_project/ECE5775_Final_Project/ecelinux_dummy/pca.cpp" location "update_off_diag_r/svd_calc_off_r" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus7 {pragma "PIPELINE" source "/home/yx388/ece5775/final_project/ECE5775_Final_Project/ecelinux_dummy/pca.cpp" location "svd_alt/svd_wb_off_r" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus8 {pragma "PIPELINE" source "/home/yx388/ece5775/final_project/ECE5775_Final_Project/ecelinux_dummy/pca.cpp" location "svd_alt/svd_rd_off_c" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus9 {pragma "PIPELINE" source "/home/yx388/ece5775/final_project/ECE5775_Final_Project/ecelinux_dummy/pca.cpp" location "update_off_diag_c/svd_calc_off_c" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus10 {pragma "PIPELINE" source "/home/yx388/ece5775/final_project/ECE5775_Final_Project/ecelinux_dummy/pca.cpp" location "svd_alt/svd_wb_off_c" found 0 funcFound 1 applied 0 ambiguous 0 reason "Directive 'PIPELINE' cannot be applied: Label 'svd_wb_off_c' does not exist in function 'svd_alt'. "}
lappend pragmaStatus11 {pragma "PIPELINE" source "/home/yx388/ece5775/final_project/ECE5775_Final_Project/ecelinux_dummy/pca.cpp" location "svd_alt/wb_buffer" found 0 funcFound 1 applied 0 ambiguous 0 reason "Directive 'PIPELINE' cannot be applied: Label 'wb_buffer' does not exist in function 'svd_alt'. "}
lappend pragmaStatus12 {pragma "PIPELINE" source "/home/yx388/ece5775/final_project/ECE5775_Final_Project/ecelinux_dummy/pca.cpp" location "matmul/LOOP_ST_A" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'PIPELINE' cannot be applied: Function 'matmul' does not exist in any synthesis source file."}
lappend pragmaStatus13 {pragma "PIPELINE" source "/home/yx388/ece5775/final_project/ECE5775_Final_Project/ecelinux_dummy/pca.cpp" location "matmul/LOOP_DOT_PROD" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'PIPELINE' cannot be applied: Function 'matmul' does not exist in any synthesis source file."}
lappend pragmaStatus14 {pragma "PIPELINE" source "/home/yx388/ece5775/final_project/ECE5775_Final_Project/ecelinux_dummy/pca.cpp" location "backproj/LOOP_ST_A" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'PIPELINE' cannot be applied: Function 'backproj' does not exist in any synthesis source file."}
lappend pragmaStatus15 {pragma "PIPELINE" source "/home/yx388/ece5775/final_project/ECE5775_Final_Project/ecelinux_dummy/pca.cpp" location "backproj/LOOP_DOT_PROD" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'PIPELINE' cannot be applied: Function 'backproj' does not exist in any synthesis source file."}
