// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.2
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "dut_matrix_multiply_alt2.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic dut_matrix_multiply_alt2::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic dut_matrix_multiply_alt2::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<3> dut_matrix_multiply_alt2::ap_ST_st1_fsm_0 = "1";
const sc_lv<3> dut_matrix_multiply_alt2::ap_ST_pp0_stg0_fsm_1 = "10";
const sc_lv<3> dut_matrix_multiply_alt2::ap_ST_st14_fsm_2 = "100";
const bool dut_matrix_multiply_alt2::ap_true = true;
const sc_lv<32> dut_matrix_multiply_alt2::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> dut_matrix_multiply_alt2::ap_const_lv1_1 = "1";
const sc_lv<32> dut_matrix_multiply_alt2::ap_const_lv32_1 = "1";
const sc_lv<1> dut_matrix_multiply_alt2::ap_const_lv1_0 = "0";
const sc_lv<22> dut_matrix_multiply_alt2::ap_const_lv22_0 = "0000000000000000000000";
const sc_lv<10> dut_matrix_multiply_alt2::ap_const_lv10_0 = "0000000000";
const sc_lv<13> dut_matrix_multiply_alt2::ap_const_lv13_0 = "0000000000000";
const sc_lv<5> dut_matrix_multiply_alt2::ap_const_lv5_0 = "00000";
const sc_lv<8> dut_matrix_multiply_alt2::ap_const_lv8_0 = "00000000";
const sc_lv<22> dut_matrix_multiply_alt2::ap_const_lv22_2FDA00 = "1011111101101000000000";
const sc_lv<22> dut_matrix_multiply_alt2::ap_const_lv22_1 = "1";
const sc_lv<10> dut_matrix_multiply_alt2::ap_const_lv10_1 = "1";
const sc_lv<13> dut_matrix_multiply_alt2::ap_const_lv13_FA0 = "111110100000";
const sc_lv<10> dut_matrix_multiply_alt2::ap_const_lv10_30F = "1100001111";
const sc_lv<8> dut_matrix_multiply_alt2::ap_const_lv8_C8 = "11001000";
const sc_lv<5> dut_matrix_multiply_alt2::ap_const_lv5_1 = "1";
const sc_lv<8> dut_matrix_multiply_alt2::ap_const_lv8_1 = "1";
const sc_lv<13> dut_matrix_multiply_alt2::ap_const_lv13_1 = "1";
const sc_lv<13> dut_matrix_multiply_alt2::ap_const_lv13_C8 = "11001000";
const sc_lv<18> dut_matrix_multiply_alt2::ap_const_lv18_C8 = "11001000";
const sc_lv<15> dut_matrix_multiply_alt2::ap_const_lv15_310 = "1100010000";
const sc_lv<32> dut_matrix_multiply_alt2::ap_const_lv32_2 = "10";

dut_matrix_multiply_alt2::dut_matrix_multiply_alt2(sc_module_name name) : sc_module(name), mVcdFile(0) {
    sum_mult_U = new dut_matrix_multiply_alt2_sum_mult("sum_mult_U");
    sum_mult_U->clk(ap_clk);
    sum_mult_U->reset(ap_rst);
    sum_mult_U->address0(sum_mult_address0);
    sum_mult_U->ce0(sum_mult_ce0);
    sum_mult_U->q0(sum_mult_q0);
    sum_mult_U->address1(ap_reg_ppstg_sum_mult_addr_reg_464_pp0_iter10);
    sum_mult_U->ce1(sum_mult_ce1);
    sum_mult_U->we1(sum_mult_we1);
    sum_mult_U->d1(sum_mult_d1);
    dut_fadd_32ns_32ns_32_5_full_dsp_U48 = new dut_fadd_32ns_32ns_32_5_full_dsp<1,5,32,32,32>("dut_fadd_32ns_32ns_32_5_full_dsp_U48");
    dut_fadd_32ns_32ns_32_5_full_dsp_U48->clk(ap_clk);
    dut_fadd_32ns_32ns_32_5_full_dsp_U48->reset(ap_rst);
    dut_fadd_32ns_32ns_32_5_full_dsp_U48->din0(sum_mult_load_reg_476);
    dut_fadd_32ns_32ns_32_5_full_dsp_U48->din1(mult_reg_470);
    dut_fadd_32ns_32ns_32_5_full_dsp_U48->ce(ap_var_for_const0);
    dut_fadd_32ns_32ns_32_5_full_dsp_U48->dout(grp_fu_178_p2);
    dut_fmul_32ns_32ns_32_4_max_dsp_U49 = new dut_fmul_32ns_32ns_32_4_max_dsp<1,4,32,32,32>("dut_fmul_32ns_32ns_32_4_max_dsp_U49");
    dut_fmul_32ns_32ns_32_4_max_dsp_U49->clk(ap_clk);
    dut_fmul_32ns_32ns_32_4_max_dsp_U49->reset(ap_rst);
    dut_fmul_32ns_32ns_32_4_max_dsp_U49->din0(A_q0);
    dut_fmul_32ns_32ns_32_4_max_dsp_U49->din1(B_q0);
    dut_fmul_32ns_32ns_32_4_max_dsp_U49->ce(ap_var_for_const0);
    dut_fmul_32ns_32ns_32_4_max_dsp_U49->dout(grp_fu_182_p2);
    dut_mac_muladd_5ns_9ns_8ns_13_1_U50 = new dut_mac_muladd_5ns_9ns_8ns_13_1<1,1,5,9,8,13>("dut_mac_muladd_5ns_9ns_8ns_13_1_U50");
    dut_mac_muladd_5ns_9ns_8ns_13_1_U50->din0(grp_fu_365_p0);
    dut_mac_muladd_5ns_9ns_8ns_13_1_U50->din1(grp_fu_365_p1);
    dut_mac_muladd_5ns_9ns_8ns_13_1_U50->din2(grp_fu_365_p2);
    dut_mac_muladd_5ns_9ns_8ns_13_1_U50->dout(grp_fu_365_p3);
    dut_mac_muladd_10ns_9ns_8ns_18_1_U51 = new dut_mac_muladd_10ns_9ns_8ns_18_1<1,1,10,9,8,18>("dut_mac_muladd_10ns_9ns_8ns_18_1_U51");
    dut_mac_muladd_10ns_9ns_8ns_18_1_U51->din0(grp_fu_374_p0);
    dut_mac_muladd_10ns_9ns_8ns_18_1_U51->din1(grp_fu_374_p1);
    dut_mac_muladd_10ns_9ns_8ns_18_1_U51->din2(grp_fu_374_p2);
    dut_mac_muladd_10ns_9ns_8ns_18_1_U51->dout(grp_fu_374_p3);
    dut_mac_muladd_5ns_11ns_10ns_15_1_U52 = new dut_mac_muladd_5ns_11ns_10ns_15_1<1,1,5,11,10,15>("dut_mac_muladd_5ns_11ns_10ns_15_1_U52");
    dut_mac_muladd_5ns_11ns_10ns_15_1_U52->din0(grp_fu_383_p0);
    dut_mac_muladd_5ns_11ns_10ns_15_1_U52->din1(grp_fu_383_p1);
    dut_mac_muladd_5ns_11ns_10ns_15_1_U52->din2(grp_fu_383_p2);
    dut_mac_muladd_5ns_11ns_10ns_15_1_U52->dout(grp_fu_383_p3);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_A_address0);
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( tmp_184_cast_fu_343_p1 );

    SC_METHOD(thread_A_ce0);
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );

    SC_METHOD(thread_B_address0);
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( tmp_186_cast_fu_350_p1 );

    SC_METHOD(thread_B_ce0);
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );

    SC_METHOD(thread_C_address0);
    sensitive << ( ap_reg_ppiten_pp0_it11 );
    sensitive << ( ap_reg_ppstg_C_addr_reg_459_pp0_iter10 );

    SC_METHOD(thread_C_ce0);
    sensitive << ( ap_reg_ppiten_pp0_it11 );

    SC_METHOD(thread_C_d0);
    sensitive << ( ap_reg_ppiten_pp0_it11 );
    sensitive << ( tmp_139_reg_481 );

    SC_METHOD(thread_C_we0);
    sensitive << ( ap_reg_ppiten_pp0_it11 );
    sensitive << ( ap_reg_ppstg_tmp_mid2_reg_401_pp0_iter10 );
    sensitive << ( ap_reg_ppstg_tmp_mid2_29_reg_405_pp0_iter10 );

    SC_METHOD(thread_Col_assign_3_phi_fu_138_p4);
    sensitive << ( Col_assign_3_reg_134 );
    sensitive << ( exitcond_flatten4_reg_392 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( tmp_i_i_mid2_v_reg_409 );

    SC_METHOD(thread_Col_assign_mid2_fu_298_p3);
    sensitive << ( Col_assign_reg_167 );
    sensitive << ( tmp_165_fu_292_p2 );

    SC_METHOD(thread_Row_assign_mid_fu_212_p3);
    sensitive << ( Row_assign_phi_fu_160_p4 );
    sensitive << ( exitcond_flatten_fu_206_p2 );

    SC_METHOD(thread_Row_assign_phi_fu_160_p4);
    sensitive << ( Row_assign_reg_156 );
    sensitive << ( exitcond_flatten4_reg_392 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( tmp_139_mid2_reg_422 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( ap_sig_cseq_ST_st14_fsm_2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_sig_cseq_ST_st14_fsm_2 );

    SC_METHOD(thread_ap_sig_20);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_239);
    sensitive << ( ap_reg_ppstg_tmp_mid2_reg_401_pp0_iter10 );
    sensitive << ( ap_reg_ppstg_tmp_mid2_29_reg_405_pp0_iter10 );

    SC_METHOD(thread_ap_sig_402);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_61);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_cseq_ST_pp0_stg0_fsm_1);
    sensitive << ( ap_sig_61 );

    SC_METHOD(thread_ap_sig_cseq_ST_st14_fsm_2);
    sensitive << ( ap_sig_402 );

    SC_METHOD(thread_ap_sig_cseq_ST_st1_fsm_0);
    sensitive << ( ap_sig_20 );

    SC_METHOD(thread_c_fu_314_p2);
    sensitive << ( Col_assign_mid2_fu_298_p3 );

    SC_METHOD(thread_exitcond_flatten4_fu_188_p2);
    sensitive << ( indvar_flatten4_reg_123 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );

    SC_METHOD(thread_exitcond_flatten_fu_206_p2);
    sensitive << ( indvar_flatten_reg_145 );
    sensitive << ( exitcond_flatten4_fu_188_p2 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );

    SC_METHOD(thread_exitcond_fu_274_p2);
    sensitive << ( Col_assign_reg_167 );
    sensitive << ( exitcond_flatten4_fu_188_p2 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );

    SC_METHOD(thread_exitcond_mid_fu_280_p2);
    sensitive << ( exitcond_fu_274_p2 );
    sensitive << ( not_exitcond_flatten_fu_268_p2 );

    SC_METHOD(thread_grp_fu_365_p0);
    sensitive << ( ap_reg_ppiten_pp0_it4 );
    sensitive << ( ap_reg_ppstg_exitcond_flatten4_reg_392_pp0_iter3 );
    sensitive << ( grp_fu_365_p00 );

    SC_METHOD(thread_grp_fu_365_p00);
    sensitive << ( ap_reg_ppstg_tmp_139_mid2_reg_422_pp0_iter3 );

    SC_METHOD(thread_grp_fu_365_p1);
    sensitive << ( ap_reg_ppiten_pp0_it4 );
    sensitive << ( ap_reg_ppstg_exitcond_flatten4_reg_392_pp0_iter3 );

    SC_METHOD(thread_grp_fu_365_p2);
    sensitive << ( ap_reg_ppiten_pp0_it4 );
    sensitive << ( ap_reg_ppstg_exitcond_flatten4_reg_392_pp0_iter3 );
    sensitive << ( grp_fu_365_p20 );

    SC_METHOD(thread_grp_fu_365_p20);
    sensitive << ( ap_reg_ppstg_Col_assign_mid2_reg_416_pp0_iter3 );

    SC_METHOD(thread_grp_fu_374_p0);
    sensitive << ( exitcond_flatten4_reg_392 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( grp_fu_374_p00 );

    SC_METHOD(thread_grp_fu_374_p00);
    sensitive << ( tmp_i_i_mid2_v_reg_409 );

    SC_METHOD(thread_grp_fu_374_p1);
    sensitive << ( exitcond_flatten4_reg_392 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );

    SC_METHOD(thread_grp_fu_374_p2);
    sensitive << ( exitcond_flatten4_reg_392 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( grp_fu_374_p20 );

    SC_METHOD(thread_grp_fu_374_p20);
    sensitive << ( Col_assign_mid2_reg_416 );

    SC_METHOD(thread_grp_fu_383_p0);
    sensitive << ( exitcond_flatten4_reg_392 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( grp_fu_383_p00 );

    SC_METHOD(thread_grp_fu_383_p00);
    sensitive << ( tmp_139_mid2_reg_422 );

    SC_METHOD(thread_grp_fu_383_p1);
    sensitive << ( exitcond_flatten4_reg_392 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );

    SC_METHOD(thread_grp_fu_383_p2);
    sensitive << ( exitcond_flatten4_reg_392 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( grp_fu_383_p20 );

    SC_METHOD(thread_grp_fu_383_p20);
    sensitive << ( tmp_i_i_mid2_v_reg_409 );

    SC_METHOD(thread_indvar_flatten_next4_fu_194_p2);
    sensitive << ( indvar_flatten4_reg_123 );

    SC_METHOD(thread_indvar_flatten_next_fu_326_p3);
    sensitive << ( exitcond_flatten_fu_206_p2 );
    sensitive << ( indvar_flatten_op_fu_320_p2 );

    SC_METHOD(thread_indvar_flatten_op_fu_320_p2);
    sensitive << ( indvar_flatten_reg_145 );

    SC_METHOD(thread_k_fu_200_p2);
    sensitive << ( Col_assign_3_phi_fu_138_p4 );

    SC_METHOD(thread_not_exitcond_flatten_fu_268_p2);
    sensitive << ( exitcond_flatten_fu_206_p2 );

    SC_METHOD(thread_r_fu_286_p2);
    sensitive << ( Row_assign_mid_fu_212_p3 );

    SC_METHOD(thread_sum_mult_address0);
    sensitive << ( ap_reg_ppiten_pp0_it4 );
    sensitive << ( tmp_187_cast_fu_360_p1 );

    SC_METHOD(thread_sum_mult_ce0);
    sensitive << ( ap_reg_ppiten_pp0_it4 );

    SC_METHOD(thread_sum_mult_ce1);
    sensitive << ( ap_reg_ppiten_pp0_it11 );
    sensitive << ( ap_reg_ppstg_tmp_mid2_reg_401_pp0_iter10 );
    sensitive << ( ap_reg_ppstg_tmp_mid2_29_reg_405_pp0_iter10 );

    SC_METHOD(thread_sum_mult_d1);
    sensitive << ( ap_reg_ppiten_pp0_it11 );
    sensitive << ( ap_reg_ppstg_tmp_mid2_reg_401_pp0_iter10 );
    sensitive << ( ap_reg_ppstg_mult_reg_470_pp0_iter10 );
    sensitive << ( tmp_139_reg_481 );
    sensitive << ( ap_sig_239 );

    SC_METHOD(thread_sum_mult_we1);
    sensitive << ( ap_reg_ppiten_pp0_it11 );
    sensitive << ( ap_reg_ppstg_tmp_mid2_reg_401_pp0_iter10 );
    sensitive << ( ap_reg_ppstg_tmp_mid2_29_reg_405_pp0_iter10 );

    SC_METHOD(thread_tmp2_fu_226_p2);
    sensitive << ( exitcond_flatten4_fu_188_p2 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( Col_assign_3_phi_fu_138_p4 );

    SC_METHOD(thread_tmp_139_mid2_fu_306_p3);
    sensitive << ( Row_assign_mid_fu_212_p3 );
    sensitive << ( exitcond_mid_fu_280_p2 );
    sensitive << ( r_fu_286_p2 );

    SC_METHOD(thread_tmp_165_fu_292_p2);
    sensitive << ( exitcond_flatten_fu_206_p2 );
    sensitive << ( exitcond_mid_fu_280_p2 );

    SC_METHOD(thread_tmp_184_cast_fu_343_p1);
    sensitive << ( grp_fu_383_p3 );

    SC_METHOD(thread_tmp_186_cast_fu_350_p1);
    sensitive << ( grp_fu_374_p3 );

    SC_METHOD(thread_tmp_187_cast_fu_360_p1);
    sensitive << ( grp_fu_365_p3 );

    SC_METHOD(thread_tmp_1_fu_246_p2);
    sensitive << ( exitcond_flatten4_fu_188_p2 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( Col_assign_3_phi_fu_138_p4 );

    SC_METHOD(thread_tmp_i_i_mid2_v_fu_260_p3);
    sensitive << ( Col_assign_3_phi_fu_138_p4 );
    sensitive << ( exitcond_flatten_fu_206_p2 );
    sensitive << ( k_fu_200_p2 );

    SC_METHOD(thread_tmp_mid1_28_fu_240_p2);
    sensitive << ( exitcond_flatten4_fu_188_p2 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( k_fu_200_p2 );

    SC_METHOD(thread_tmp_mid1_fu_220_p2);
    sensitive << ( exitcond_flatten4_fu_188_p2 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( k_fu_200_p2 );

    SC_METHOD(thread_tmp_mid2_29_fu_252_p3);
    sensitive << ( exitcond_flatten_fu_206_p2 );
    sensitive << ( tmp_mid1_28_fu_240_p2 );
    sensitive << ( tmp_1_fu_246_p2 );

    SC_METHOD(thread_tmp_mid2_fu_232_p3);
    sensitive << ( exitcond_flatten_fu_206_p2 );
    sensitive << ( tmp_mid1_fu_220_p2 );
    sensitive << ( tmp2_fu_226_p2 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( exitcond_flatten4_fu_188_p2 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_reg_ppiten_pp0_it10 );
    sensitive << ( ap_reg_ppiten_pp0_it11 );

    SC_THREAD(thread_ap_var_for_const0);

    ap_CS_fsm = "001";
    ap_reg_ppiten_pp0_it0 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it1 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it2 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it3 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it4 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it5 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it6 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it7 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it8 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it9 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it10 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it11 = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "dut_matrix_multiply_alt2_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, A_address0, "(port)A_address0");
    sc_trace(mVcdFile, A_ce0, "(port)A_ce0");
    sc_trace(mVcdFile, A_q0, "(port)A_q0");
    sc_trace(mVcdFile, B_address0, "(port)B_address0");
    sc_trace(mVcdFile, B_ce0, "(port)B_ce0");
    sc_trace(mVcdFile, B_q0, "(port)B_q0");
    sc_trace(mVcdFile, C_address0, "(port)C_address0");
    sc_trace(mVcdFile, C_ce0, "(port)C_ce0");
    sc_trace(mVcdFile, C_we0, "(port)C_we0");
    sc_trace(mVcdFile, C_d0, "(port)C_d0");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st1_fsm_0, "ap_sig_cseq_ST_st1_fsm_0");
    sc_trace(mVcdFile, ap_sig_20, "ap_sig_20");
    sc_trace(mVcdFile, indvar_flatten4_reg_123, "indvar_flatten4_reg_123");
    sc_trace(mVcdFile, Col_assign_3_reg_134, "Col_assign_3_reg_134");
    sc_trace(mVcdFile, indvar_flatten_reg_145, "indvar_flatten_reg_145");
    sc_trace(mVcdFile, Row_assign_reg_156, "Row_assign_reg_156");
    sc_trace(mVcdFile, Col_assign_reg_167, "Col_assign_reg_167");
    sc_trace(mVcdFile, exitcond_flatten4_fu_188_p2, "exitcond_flatten4_fu_188_p2");
    sc_trace(mVcdFile, exitcond_flatten4_reg_392, "exitcond_flatten4_reg_392");
    sc_trace(mVcdFile, ap_sig_cseq_ST_pp0_stg0_fsm_1, "ap_sig_cseq_ST_pp0_stg0_fsm_1");
    sc_trace(mVcdFile, ap_sig_61, "ap_sig_61");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it0, "ap_reg_ppiten_pp0_it0");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it1, "ap_reg_ppiten_pp0_it1");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it2, "ap_reg_ppiten_pp0_it2");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it3, "ap_reg_ppiten_pp0_it3");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it4, "ap_reg_ppiten_pp0_it4");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it5, "ap_reg_ppiten_pp0_it5");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it6, "ap_reg_ppiten_pp0_it6");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it7, "ap_reg_ppiten_pp0_it7");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it8, "ap_reg_ppiten_pp0_it8");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it9, "ap_reg_ppiten_pp0_it9");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it10, "ap_reg_ppiten_pp0_it10");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it11, "ap_reg_ppiten_pp0_it11");
    sc_trace(mVcdFile, ap_reg_ppstg_exitcond_flatten4_reg_392_pp0_iter1, "ap_reg_ppstg_exitcond_flatten4_reg_392_pp0_iter1");
    sc_trace(mVcdFile, ap_reg_ppstg_exitcond_flatten4_reg_392_pp0_iter2, "ap_reg_ppstg_exitcond_flatten4_reg_392_pp0_iter2");
    sc_trace(mVcdFile, ap_reg_ppstg_exitcond_flatten4_reg_392_pp0_iter3, "ap_reg_ppstg_exitcond_flatten4_reg_392_pp0_iter3");
    sc_trace(mVcdFile, ap_reg_ppstg_exitcond_flatten4_reg_392_pp0_iter4, "ap_reg_ppstg_exitcond_flatten4_reg_392_pp0_iter4");
    sc_trace(mVcdFile, indvar_flatten_next4_fu_194_p2, "indvar_flatten_next4_fu_194_p2");
    sc_trace(mVcdFile, tmp_mid2_fu_232_p3, "tmp_mid2_fu_232_p3");
    sc_trace(mVcdFile, tmp_mid2_reg_401, "tmp_mid2_reg_401");
    sc_trace(mVcdFile, ap_reg_ppstg_tmp_mid2_reg_401_pp0_iter1, "ap_reg_ppstg_tmp_mid2_reg_401_pp0_iter1");
    sc_trace(mVcdFile, ap_reg_ppstg_tmp_mid2_reg_401_pp0_iter2, "ap_reg_ppstg_tmp_mid2_reg_401_pp0_iter2");
    sc_trace(mVcdFile, ap_reg_ppstg_tmp_mid2_reg_401_pp0_iter3, "ap_reg_ppstg_tmp_mid2_reg_401_pp0_iter3");
    sc_trace(mVcdFile, ap_reg_ppstg_tmp_mid2_reg_401_pp0_iter4, "ap_reg_ppstg_tmp_mid2_reg_401_pp0_iter4");
    sc_trace(mVcdFile, ap_reg_ppstg_tmp_mid2_reg_401_pp0_iter5, "ap_reg_ppstg_tmp_mid2_reg_401_pp0_iter5");
    sc_trace(mVcdFile, ap_reg_ppstg_tmp_mid2_reg_401_pp0_iter6, "ap_reg_ppstg_tmp_mid2_reg_401_pp0_iter6");
    sc_trace(mVcdFile, ap_reg_ppstg_tmp_mid2_reg_401_pp0_iter7, "ap_reg_ppstg_tmp_mid2_reg_401_pp0_iter7");
    sc_trace(mVcdFile, ap_reg_ppstg_tmp_mid2_reg_401_pp0_iter8, "ap_reg_ppstg_tmp_mid2_reg_401_pp0_iter8");
    sc_trace(mVcdFile, ap_reg_ppstg_tmp_mid2_reg_401_pp0_iter9, "ap_reg_ppstg_tmp_mid2_reg_401_pp0_iter9");
    sc_trace(mVcdFile, ap_reg_ppstg_tmp_mid2_reg_401_pp0_iter10, "ap_reg_ppstg_tmp_mid2_reg_401_pp0_iter10");
    sc_trace(mVcdFile, tmp_mid2_29_fu_252_p3, "tmp_mid2_29_fu_252_p3");
    sc_trace(mVcdFile, tmp_mid2_29_reg_405, "tmp_mid2_29_reg_405");
    sc_trace(mVcdFile, ap_reg_ppstg_tmp_mid2_29_reg_405_pp0_iter1, "ap_reg_ppstg_tmp_mid2_29_reg_405_pp0_iter1");
    sc_trace(mVcdFile, ap_reg_ppstg_tmp_mid2_29_reg_405_pp0_iter2, "ap_reg_ppstg_tmp_mid2_29_reg_405_pp0_iter2");
    sc_trace(mVcdFile, ap_reg_ppstg_tmp_mid2_29_reg_405_pp0_iter3, "ap_reg_ppstg_tmp_mid2_29_reg_405_pp0_iter3");
    sc_trace(mVcdFile, ap_reg_ppstg_tmp_mid2_29_reg_405_pp0_iter4, "ap_reg_ppstg_tmp_mid2_29_reg_405_pp0_iter4");
    sc_trace(mVcdFile, ap_reg_ppstg_tmp_mid2_29_reg_405_pp0_iter5, "ap_reg_ppstg_tmp_mid2_29_reg_405_pp0_iter5");
    sc_trace(mVcdFile, ap_reg_ppstg_tmp_mid2_29_reg_405_pp0_iter6, "ap_reg_ppstg_tmp_mid2_29_reg_405_pp0_iter6");
    sc_trace(mVcdFile, ap_reg_ppstg_tmp_mid2_29_reg_405_pp0_iter7, "ap_reg_ppstg_tmp_mid2_29_reg_405_pp0_iter7");
    sc_trace(mVcdFile, ap_reg_ppstg_tmp_mid2_29_reg_405_pp0_iter8, "ap_reg_ppstg_tmp_mid2_29_reg_405_pp0_iter8");
    sc_trace(mVcdFile, ap_reg_ppstg_tmp_mid2_29_reg_405_pp0_iter9, "ap_reg_ppstg_tmp_mid2_29_reg_405_pp0_iter9");
    sc_trace(mVcdFile, ap_reg_ppstg_tmp_mid2_29_reg_405_pp0_iter10, "ap_reg_ppstg_tmp_mid2_29_reg_405_pp0_iter10");
    sc_trace(mVcdFile, tmp_i_i_mid2_v_fu_260_p3, "tmp_i_i_mid2_v_fu_260_p3");
    sc_trace(mVcdFile, tmp_i_i_mid2_v_reg_409, "tmp_i_i_mid2_v_reg_409");
    sc_trace(mVcdFile, Col_assign_mid2_fu_298_p3, "Col_assign_mid2_fu_298_p3");
    sc_trace(mVcdFile, Col_assign_mid2_reg_416, "Col_assign_mid2_reg_416");
    sc_trace(mVcdFile, ap_reg_ppstg_Col_assign_mid2_reg_416_pp0_iter1, "ap_reg_ppstg_Col_assign_mid2_reg_416_pp0_iter1");
    sc_trace(mVcdFile, ap_reg_ppstg_Col_assign_mid2_reg_416_pp0_iter2, "ap_reg_ppstg_Col_assign_mid2_reg_416_pp0_iter2");
    sc_trace(mVcdFile, ap_reg_ppstg_Col_assign_mid2_reg_416_pp0_iter3, "ap_reg_ppstg_Col_assign_mid2_reg_416_pp0_iter3");
    sc_trace(mVcdFile, tmp_139_mid2_fu_306_p3, "tmp_139_mid2_fu_306_p3");
    sc_trace(mVcdFile, tmp_139_mid2_reg_422, "tmp_139_mid2_reg_422");
    sc_trace(mVcdFile, ap_reg_ppstg_tmp_139_mid2_reg_422_pp0_iter1, "ap_reg_ppstg_tmp_139_mid2_reg_422_pp0_iter1");
    sc_trace(mVcdFile, ap_reg_ppstg_tmp_139_mid2_reg_422_pp0_iter2, "ap_reg_ppstg_tmp_139_mid2_reg_422_pp0_iter2");
    sc_trace(mVcdFile, ap_reg_ppstg_tmp_139_mid2_reg_422_pp0_iter3, "ap_reg_ppstg_tmp_139_mid2_reg_422_pp0_iter3");
    sc_trace(mVcdFile, c_fu_314_p2, "c_fu_314_p2");
    sc_trace(mVcdFile, indvar_flatten_next_fu_326_p3, "indvar_flatten_next_fu_326_p3");
    sc_trace(mVcdFile, C_addr_reg_459, "C_addr_reg_459");
    sc_trace(mVcdFile, ap_reg_ppstg_C_addr_reg_459_pp0_iter5, "ap_reg_ppstg_C_addr_reg_459_pp0_iter5");
    sc_trace(mVcdFile, ap_reg_ppstg_C_addr_reg_459_pp0_iter6, "ap_reg_ppstg_C_addr_reg_459_pp0_iter6");
    sc_trace(mVcdFile, ap_reg_ppstg_C_addr_reg_459_pp0_iter7, "ap_reg_ppstg_C_addr_reg_459_pp0_iter7");
    sc_trace(mVcdFile, ap_reg_ppstg_C_addr_reg_459_pp0_iter8, "ap_reg_ppstg_C_addr_reg_459_pp0_iter8");
    sc_trace(mVcdFile, ap_reg_ppstg_C_addr_reg_459_pp0_iter9, "ap_reg_ppstg_C_addr_reg_459_pp0_iter9");
    sc_trace(mVcdFile, ap_reg_ppstg_C_addr_reg_459_pp0_iter10, "ap_reg_ppstg_C_addr_reg_459_pp0_iter10");
    sc_trace(mVcdFile, sum_mult_addr_reg_464, "sum_mult_addr_reg_464");
    sc_trace(mVcdFile, ap_reg_ppstg_sum_mult_addr_reg_464_pp0_iter5, "ap_reg_ppstg_sum_mult_addr_reg_464_pp0_iter5");
    sc_trace(mVcdFile, ap_reg_ppstg_sum_mult_addr_reg_464_pp0_iter6, "ap_reg_ppstg_sum_mult_addr_reg_464_pp0_iter6");
    sc_trace(mVcdFile, ap_reg_ppstg_sum_mult_addr_reg_464_pp0_iter7, "ap_reg_ppstg_sum_mult_addr_reg_464_pp0_iter7");
    sc_trace(mVcdFile, ap_reg_ppstg_sum_mult_addr_reg_464_pp0_iter8, "ap_reg_ppstg_sum_mult_addr_reg_464_pp0_iter8");
    sc_trace(mVcdFile, ap_reg_ppstg_sum_mult_addr_reg_464_pp0_iter9, "ap_reg_ppstg_sum_mult_addr_reg_464_pp0_iter9");
    sc_trace(mVcdFile, ap_reg_ppstg_sum_mult_addr_reg_464_pp0_iter10, "ap_reg_ppstg_sum_mult_addr_reg_464_pp0_iter10");
    sc_trace(mVcdFile, grp_fu_182_p2, "grp_fu_182_p2");
    sc_trace(mVcdFile, mult_reg_470, "mult_reg_470");
    sc_trace(mVcdFile, ap_reg_ppstg_mult_reg_470_pp0_iter6, "ap_reg_ppstg_mult_reg_470_pp0_iter6");
    sc_trace(mVcdFile, ap_reg_ppstg_mult_reg_470_pp0_iter7, "ap_reg_ppstg_mult_reg_470_pp0_iter7");
    sc_trace(mVcdFile, ap_reg_ppstg_mult_reg_470_pp0_iter8, "ap_reg_ppstg_mult_reg_470_pp0_iter8");
    sc_trace(mVcdFile, ap_reg_ppstg_mult_reg_470_pp0_iter9, "ap_reg_ppstg_mult_reg_470_pp0_iter9");
    sc_trace(mVcdFile, ap_reg_ppstg_mult_reg_470_pp0_iter10, "ap_reg_ppstg_mult_reg_470_pp0_iter10");
    sc_trace(mVcdFile, sum_mult_q0, "sum_mult_q0");
    sc_trace(mVcdFile, sum_mult_load_reg_476, "sum_mult_load_reg_476");
    sc_trace(mVcdFile, grp_fu_178_p2, "grp_fu_178_p2");
    sc_trace(mVcdFile, tmp_139_reg_481, "tmp_139_reg_481");
    sc_trace(mVcdFile, sum_mult_address0, "sum_mult_address0");
    sc_trace(mVcdFile, sum_mult_ce0, "sum_mult_ce0");
    sc_trace(mVcdFile, sum_mult_ce1, "sum_mult_ce1");
    sc_trace(mVcdFile, sum_mult_we1, "sum_mult_we1");
    sc_trace(mVcdFile, sum_mult_d1, "sum_mult_d1");
    sc_trace(mVcdFile, Col_assign_3_phi_fu_138_p4, "Col_assign_3_phi_fu_138_p4");
    sc_trace(mVcdFile, Row_assign_phi_fu_160_p4, "Row_assign_phi_fu_160_p4");
    sc_trace(mVcdFile, tmp_184_cast_fu_343_p1, "tmp_184_cast_fu_343_p1");
    sc_trace(mVcdFile, tmp_186_cast_fu_350_p1, "tmp_186_cast_fu_350_p1");
    sc_trace(mVcdFile, tmp_187_cast_fu_360_p1, "tmp_187_cast_fu_360_p1");
    sc_trace(mVcdFile, exitcond_flatten_fu_206_p2, "exitcond_flatten_fu_206_p2");
    sc_trace(mVcdFile, k_fu_200_p2, "k_fu_200_p2");
    sc_trace(mVcdFile, tmp_mid1_fu_220_p2, "tmp_mid1_fu_220_p2");
    sc_trace(mVcdFile, tmp2_fu_226_p2, "tmp2_fu_226_p2");
    sc_trace(mVcdFile, tmp_mid1_28_fu_240_p2, "tmp_mid1_28_fu_240_p2");
    sc_trace(mVcdFile, tmp_1_fu_246_p2, "tmp_1_fu_246_p2");
    sc_trace(mVcdFile, exitcond_fu_274_p2, "exitcond_fu_274_p2");
    sc_trace(mVcdFile, not_exitcond_flatten_fu_268_p2, "not_exitcond_flatten_fu_268_p2");
    sc_trace(mVcdFile, Row_assign_mid_fu_212_p3, "Row_assign_mid_fu_212_p3");
    sc_trace(mVcdFile, exitcond_mid_fu_280_p2, "exitcond_mid_fu_280_p2");
    sc_trace(mVcdFile, tmp_165_fu_292_p2, "tmp_165_fu_292_p2");
    sc_trace(mVcdFile, r_fu_286_p2, "r_fu_286_p2");
    sc_trace(mVcdFile, indvar_flatten_op_fu_320_p2, "indvar_flatten_op_fu_320_p2");
    sc_trace(mVcdFile, grp_fu_383_p3, "grp_fu_383_p3");
    sc_trace(mVcdFile, grp_fu_374_p3, "grp_fu_374_p3");
    sc_trace(mVcdFile, grp_fu_365_p3, "grp_fu_365_p3");
    sc_trace(mVcdFile, grp_fu_365_p0, "grp_fu_365_p0");
    sc_trace(mVcdFile, grp_fu_365_p1, "grp_fu_365_p1");
    sc_trace(mVcdFile, grp_fu_365_p2, "grp_fu_365_p2");
    sc_trace(mVcdFile, grp_fu_374_p0, "grp_fu_374_p0");
    sc_trace(mVcdFile, grp_fu_374_p1, "grp_fu_374_p1");
    sc_trace(mVcdFile, grp_fu_374_p2, "grp_fu_374_p2");
    sc_trace(mVcdFile, grp_fu_383_p0, "grp_fu_383_p0");
    sc_trace(mVcdFile, grp_fu_383_p1, "grp_fu_383_p1");
    sc_trace(mVcdFile, grp_fu_383_p2, "grp_fu_383_p2");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st14_fsm_2, "ap_sig_cseq_ST_st14_fsm_2");
    sc_trace(mVcdFile, ap_sig_402, "ap_sig_402");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, grp_fu_365_p00, "grp_fu_365_p00");
    sc_trace(mVcdFile, grp_fu_365_p20, "grp_fu_365_p20");
    sc_trace(mVcdFile, grp_fu_374_p00, "grp_fu_374_p00");
    sc_trace(mVcdFile, grp_fu_374_p20, "grp_fu_374_p20");
    sc_trace(mVcdFile, grp_fu_383_p00, "grp_fu_383_p00");
    sc_trace(mVcdFile, grp_fu_383_p20, "grp_fu_383_p20");
    sc_trace(mVcdFile, ap_sig_239, "ap_sig_239");
#endif

    }
}

dut_matrix_multiply_alt2::~dut_matrix_multiply_alt2() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete sum_mult_U;
    delete dut_fadd_32ns_32ns_32_5_full_dsp_U48;
    delete dut_fmul_32ns_32ns_32_4_max_dsp_U49;
    delete dut_mac_muladd_5ns_9ns_8ns_13_1_U50;
    delete dut_mac_muladd_10ns_9ns_8ns_18_1_U51;
    delete dut_mac_muladd_5ns_11ns_10ns_15_1_U52;
}

void dut_matrix_multiply_alt2::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void dut_matrix_multiply_alt2::thread_ap_clk_no_reset_() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten4_reg_392.read(), ap_const_lv1_0))) {
        Col_assign_3_reg_134 = tmp_i_i_mid2_v_reg_409.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        Col_assign_3_reg_134 = ap_const_lv10_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten4_fu_188_p2.read(), ap_const_lv1_0))) {
        Col_assign_reg_167 = c_fu_314_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        Col_assign_reg_167 = ap_const_lv8_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten4_reg_392.read(), ap_const_lv1_0))) {
        Row_assign_reg_156 = tmp_139_mid2_reg_422.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        Row_assign_reg_156 = ap_const_lv5_0;
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_st1_fsm_0;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
             !esl_seteq<1,1,1>(exitcond_flatten4_fu_188_p2.read(), ap_const_lv1_0))) {
            ap_reg_ppiten_pp0_it0 = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                    !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
            ap_reg_ppiten_pp0_it0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it1 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
             esl_seteq<1,1,1>(exitcond_flatten4_fu_188_p2.read(), ap_const_lv1_0))) {
            ap_reg_ppiten_pp0_it1 = ap_const_logic_1;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                     !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) || 
                    (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
                     !esl_seteq<1,1,1>(exitcond_flatten4_fu_188_p2.read(), ap_const_lv1_0)))) {
            ap_reg_ppiten_pp0_it1 = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it10 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_true, ap_true)) {
            ap_reg_ppiten_pp0_it10 = ap_reg_ppiten_pp0_it9.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it11 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_true, ap_true)) {
            ap_reg_ppiten_pp0_it11 = ap_reg_ppiten_pp0_it10.read();
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                    !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
            ap_reg_ppiten_pp0_it11 = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it2 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_true, ap_true)) {
            ap_reg_ppiten_pp0_it2 = ap_reg_ppiten_pp0_it1.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it3 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_true, ap_true)) {
            ap_reg_ppiten_pp0_it3 = ap_reg_ppiten_pp0_it2.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it4 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_true, ap_true)) {
            ap_reg_ppiten_pp0_it4 = ap_reg_ppiten_pp0_it3.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it5 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_true, ap_true)) {
            ap_reg_ppiten_pp0_it5 = ap_reg_ppiten_pp0_it4.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it6 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_true, ap_true)) {
            ap_reg_ppiten_pp0_it6 = ap_reg_ppiten_pp0_it5.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it7 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_true, ap_true)) {
            ap_reg_ppiten_pp0_it7 = ap_reg_ppiten_pp0_it6.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it8 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_true, ap_true)) {
            ap_reg_ppiten_pp0_it8 = ap_reg_ppiten_pp0_it7.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it9 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_true, ap_true)) {
            ap_reg_ppiten_pp0_it9 = ap_reg_ppiten_pp0_it8.read();
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten4_fu_188_p2.read(), ap_const_lv1_0))) {
        indvar_flatten4_reg_123 = indvar_flatten_next4_fu_194_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        indvar_flatten4_reg_123 = ap_const_lv22_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten4_fu_188_p2.read(), ap_const_lv1_0))) {
        indvar_flatten_reg_145 = indvar_flatten_next_fu_326_p3.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        indvar_flatten_reg_145 = ap_const_lv13_0;
    }
    if (esl_seteq<1,1,1>(ap_reg_ppstg_exitcond_flatten4_reg_392_pp0_iter3.read(), ap_const_lv1_0)) {
        C_addr_reg_459 =  (sc_lv<12>) (tmp_187_cast_fu_360_p1.read());
        sum_mult_addr_reg_464 =  (sc_lv<12>) (tmp_187_cast_fu_360_p1.read());
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && esl_seteq<1,1,1>(exitcond_flatten4_fu_188_p2.read(), ap_const_lv1_0))) {
        Col_assign_mid2_reg_416 = Col_assign_mid2_fu_298_p3.read();
        tmp_mid2_29_reg_405 = tmp_mid2_29_fu_252_p3.read();
        tmp_mid2_reg_401 = tmp_mid2_fu_232_p3.read();
    }
    if (esl_seteq<1,1,1>(ap_true, ap_true)) {
        ap_reg_ppstg_C_addr_reg_459_pp0_iter10 = ap_reg_ppstg_C_addr_reg_459_pp0_iter9.read();
        ap_reg_ppstg_C_addr_reg_459_pp0_iter5 = C_addr_reg_459.read();
        ap_reg_ppstg_C_addr_reg_459_pp0_iter6 = ap_reg_ppstg_C_addr_reg_459_pp0_iter5.read();
        ap_reg_ppstg_C_addr_reg_459_pp0_iter7 = ap_reg_ppstg_C_addr_reg_459_pp0_iter6.read();
        ap_reg_ppstg_C_addr_reg_459_pp0_iter8 = ap_reg_ppstg_C_addr_reg_459_pp0_iter7.read();
        ap_reg_ppstg_C_addr_reg_459_pp0_iter9 = ap_reg_ppstg_C_addr_reg_459_pp0_iter8.read();
        ap_reg_ppstg_Col_assign_mid2_reg_416_pp0_iter2 = ap_reg_ppstg_Col_assign_mid2_reg_416_pp0_iter1.read();
        ap_reg_ppstg_Col_assign_mid2_reg_416_pp0_iter3 = ap_reg_ppstg_Col_assign_mid2_reg_416_pp0_iter2.read();
        ap_reg_ppstg_exitcond_flatten4_reg_392_pp0_iter2 = ap_reg_ppstg_exitcond_flatten4_reg_392_pp0_iter1.read();
        ap_reg_ppstg_exitcond_flatten4_reg_392_pp0_iter3 = ap_reg_ppstg_exitcond_flatten4_reg_392_pp0_iter2.read();
        ap_reg_ppstg_exitcond_flatten4_reg_392_pp0_iter4 = ap_reg_ppstg_exitcond_flatten4_reg_392_pp0_iter3.read();
        ap_reg_ppstg_mult_reg_470_pp0_iter10 = ap_reg_ppstg_mult_reg_470_pp0_iter9.read();
        ap_reg_ppstg_mult_reg_470_pp0_iter6 = mult_reg_470.read();
        ap_reg_ppstg_mult_reg_470_pp0_iter7 = ap_reg_ppstg_mult_reg_470_pp0_iter6.read();
        ap_reg_ppstg_mult_reg_470_pp0_iter8 = ap_reg_ppstg_mult_reg_470_pp0_iter7.read();
        ap_reg_ppstg_mult_reg_470_pp0_iter9 = ap_reg_ppstg_mult_reg_470_pp0_iter8.read();
        ap_reg_ppstg_sum_mult_addr_reg_464_pp0_iter10 = ap_reg_ppstg_sum_mult_addr_reg_464_pp0_iter9.read();
        ap_reg_ppstg_sum_mult_addr_reg_464_pp0_iter5 = sum_mult_addr_reg_464.read();
        ap_reg_ppstg_sum_mult_addr_reg_464_pp0_iter6 = ap_reg_ppstg_sum_mult_addr_reg_464_pp0_iter5.read();
        ap_reg_ppstg_sum_mult_addr_reg_464_pp0_iter7 = ap_reg_ppstg_sum_mult_addr_reg_464_pp0_iter6.read();
        ap_reg_ppstg_sum_mult_addr_reg_464_pp0_iter8 = ap_reg_ppstg_sum_mult_addr_reg_464_pp0_iter7.read();
        ap_reg_ppstg_sum_mult_addr_reg_464_pp0_iter9 = ap_reg_ppstg_sum_mult_addr_reg_464_pp0_iter8.read();
        ap_reg_ppstg_tmp_139_mid2_reg_422_pp0_iter2 = ap_reg_ppstg_tmp_139_mid2_reg_422_pp0_iter1.read();
        ap_reg_ppstg_tmp_139_mid2_reg_422_pp0_iter3 = ap_reg_ppstg_tmp_139_mid2_reg_422_pp0_iter2.read();
        ap_reg_ppstg_tmp_mid2_29_reg_405_pp0_iter10 = ap_reg_ppstg_tmp_mid2_29_reg_405_pp0_iter9.read();
        ap_reg_ppstg_tmp_mid2_29_reg_405_pp0_iter2 = ap_reg_ppstg_tmp_mid2_29_reg_405_pp0_iter1.read();
        ap_reg_ppstg_tmp_mid2_29_reg_405_pp0_iter3 = ap_reg_ppstg_tmp_mid2_29_reg_405_pp0_iter2.read();
        ap_reg_ppstg_tmp_mid2_29_reg_405_pp0_iter4 = ap_reg_ppstg_tmp_mid2_29_reg_405_pp0_iter3.read();
        ap_reg_ppstg_tmp_mid2_29_reg_405_pp0_iter5 = ap_reg_ppstg_tmp_mid2_29_reg_405_pp0_iter4.read();
        ap_reg_ppstg_tmp_mid2_29_reg_405_pp0_iter6 = ap_reg_ppstg_tmp_mid2_29_reg_405_pp0_iter5.read();
        ap_reg_ppstg_tmp_mid2_29_reg_405_pp0_iter7 = ap_reg_ppstg_tmp_mid2_29_reg_405_pp0_iter6.read();
        ap_reg_ppstg_tmp_mid2_29_reg_405_pp0_iter8 = ap_reg_ppstg_tmp_mid2_29_reg_405_pp0_iter7.read();
        ap_reg_ppstg_tmp_mid2_29_reg_405_pp0_iter9 = ap_reg_ppstg_tmp_mid2_29_reg_405_pp0_iter8.read();
        ap_reg_ppstg_tmp_mid2_reg_401_pp0_iter10 = ap_reg_ppstg_tmp_mid2_reg_401_pp0_iter9.read();
        ap_reg_ppstg_tmp_mid2_reg_401_pp0_iter2 = ap_reg_ppstg_tmp_mid2_reg_401_pp0_iter1.read();
        ap_reg_ppstg_tmp_mid2_reg_401_pp0_iter3 = ap_reg_ppstg_tmp_mid2_reg_401_pp0_iter2.read();
        ap_reg_ppstg_tmp_mid2_reg_401_pp0_iter4 = ap_reg_ppstg_tmp_mid2_reg_401_pp0_iter3.read();
        ap_reg_ppstg_tmp_mid2_reg_401_pp0_iter5 = ap_reg_ppstg_tmp_mid2_reg_401_pp0_iter4.read();
        ap_reg_ppstg_tmp_mid2_reg_401_pp0_iter6 = ap_reg_ppstg_tmp_mid2_reg_401_pp0_iter5.read();
        ap_reg_ppstg_tmp_mid2_reg_401_pp0_iter7 = ap_reg_ppstg_tmp_mid2_reg_401_pp0_iter6.read();
        ap_reg_ppstg_tmp_mid2_reg_401_pp0_iter8 = ap_reg_ppstg_tmp_mid2_reg_401_pp0_iter7.read();
        ap_reg_ppstg_tmp_mid2_reg_401_pp0_iter9 = ap_reg_ppstg_tmp_mid2_reg_401_pp0_iter8.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read())) {
        ap_reg_ppstg_Col_assign_mid2_reg_416_pp0_iter1 = Col_assign_mid2_reg_416.read();
        ap_reg_ppstg_exitcond_flatten4_reg_392_pp0_iter1 = exitcond_flatten4_reg_392.read();
        ap_reg_ppstg_tmp_139_mid2_reg_422_pp0_iter1 = tmp_139_mid2_reg_422.read();
        ap_reg_ppstg_tmp_mid2_29_reg_405_pp0_iter1 = tmp_mid2_29_reg_405.read();
        ap_reg_ppstg_tmp_mid2_reg_401_pp0_iter1 = tmp_mid2_reg_401.read();
        exitcond_flatten4_reg_392 = exitcond_flatten4_fu_188_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_reg_ppstg_exitcond_flatten4_reg_392_pp0_iter4.read(), ap_const_lv1_0)) {
        mult_reg_470 = grp_fu_182_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it5.read()) && esl_seteq<1,1,1>(ap_reg_ppstg_exitcond_flatten4_reg_392_pp0_iter4.read(), ap_const_lv1_0))) {
        sum_mult_load_reg_476 = sum_mult_q0.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && esl_seteq<1,1,1>(exitcond_flatten4_fu_188_p2.read(), ap_const_lv1_0))) {
        tmp_139_mid2_reg_422 = tmp_139_mid2_fu_306_p3.read();
        tmp_i_i_mid2_v_reg_409 = tmp_i_i_mid2_v_fu_260_p3.read();
    }
    if (esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_tmp_mid2_reg_401_pp0_iter9.read())) {
        tmp_139_reg_481 = grp_fu_178_p2.read();
    }
}

void dut_matrix_multiply_alt2::thread_A_address0() {
    A_address0 =  (sc_lv<14>) (tmp_184_cast_fu_343_p1.read());
}

void dut_matrix_multiply_alt2::thread_A_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()))) {
        A_ce0 = ap_const_logic_1;
    } else {
        A_ce0 = ap_const_logic_0;
    }
}

void dut_matrix_multiply_alt2::thread_B_address0() {
    B_address0 =  (sc_lv<18>) (tmp_186_cast_fu_350_p1.read());
}

void dut_matrix_multiply_alt2::thread_B_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()))) {
        B_ce0 = ap_const_logic_1;
    } else {
        B_ce0 = ap_const_logic_0;
    }
}

void dut_matrix_multiply_alt2::thread_C_address0() {
    C_address0 = ap_reg_ppstg_C_addr_reg_459_pp0_iter10.read();
}

void dut_matrix_multiply_alt2::thread_C_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it11.read())) {
        C_ce0 = ap_const_logic_1;
    } else {
        C_ce0 = ap_const_logic_0;
    }
}

void dut_matrix_multiply_alt2::thread_C_d0() {
    C_d0 = tmp_139_reg_481.read();
}

void dut_matrix_multiply_alt2::thread_C_we0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it11.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_tmp_mid2_reg_401_pp0_iter10.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_tmp_mid2_29_reg_405_pp0_iter10.read())))) {
        C_we0 = ap_const_logic_1;
    } else {
        C_we0 = ap_const_logic_0;
    }
}

void dut_matrix_multiply_alt2::thread_Col_assign_3_phi_fu_138_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten4_reg_392.read(), ap_const_lv1_0))) {
        Col_assign_3_phi_fu_138_p4 = tmp_i_i_mid2_v_reg_409.read();
    } else {
        Col_assign_3_phi_fu_138_p4 = Col_assign_3_reg_134.read();
    }
}

void dut_matrix_multiply_alt2::thread_Col_assign_mid2_fu_298_p3() {
    Col_assign_mid2_fu_298_p3 = (!tmp_165_fu_292_p2.read()[0].is_01())? sc_lv<8>(): ((tmp_165_fu_292_p2.read()[0].to_bool())? ap_const_lv8_0: Col_assign_reg_167.read());
}

void dut_matrix_multiply_alt2::thread_Row_assign_mid_fu_212_p3() {
    Row_assign_mid_fu_212_p3 = (!exitcond_flatten_fu_206_p2.read()[0].is_01())? sc_lv<5>(): ((exitcond_flatten_fu_206_p2.read()[0].to_bool())? ap_const_lv5_0: Row_assign_phi_fu_160_p4.read());
}

void dut_matrix_multiply_alt2::thread_Row_assign_phi_fu_160_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten4_reg_392.read(), ap_const_lv1_0))) {
        Row_assign_phi_fu_160_p4 = tmp_139_mid2_reg_422.read();
    } else {
        Row_assign_phi_fu_160_p4 = Row_assign_reg_156.read();
    }
}

void dut_matrix_multiply_alt2::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st14_fsm_2.read()))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void dut_matrix_multiply_alt2::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void dut_matrix_multiply_alt2::thread_ap_ready() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st14_fsm_2.read())) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void dut_matrix_multiply_alt2::thread_ap_sig_20() {
    ap_sig_20 = esl_seteq<1,1,1>(ap_CS_fsm.read().range(0, 0), ap_const_lv1_1);
}

void dut_matrix_multiply_alt2::thread_ap_sig_239() {
    ap_sig_239 = (esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_tmp_mid2_reg_401_pp0_iter10.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_tmp_mid2_29_reg_405_pp0_iter10.read()));
}

void dut_matrix_multiply_alt2::thread_ap_sig_402() {
    ap_sig_402 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(2, 2));
}

void dut_matrix_multiply_alt2::thread_ap_sig_61() {
    ap_sig_61 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(1, 1));
}

void dut_matrix_multiply_alt2::thread_ap_sig_cseq_ST_pp0_stg0_fsm_1() {
    if (ap_sig_61.read()) {
        ap_sig_cseq_ST_pp0_stg0_fsm_1 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_pp0_stg0_fsm_1 = ap_const_logic_0;
    }
}

void dut_matrix_multiply_alt2::thread_ap_sig_cseq_ST_st14_fsm_2() {
    if (ap_sig_402.read()) {
        ap_sig_cseq_ST_st14_fsm_2 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st14_fsm_2 = ap_const_logic_0;
    }
}

void dut_matrix_multiply_alt2::thread_ap_sig_cseq_ST_st1_fsm_0() {
    if (ap_sig_20.read()) {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    }
}

void dut_matrix_multiply_alt2::thread_c_fu_314_p2() {
    c_fu_314_p2 = (!Col_assign_mid2_fu_298_p3.read().is_01() || !ap_const_lv8_1.is_01())? sc_lv<8>(): (sc_biguint<8>(Col_assign_mid2_fu_298_p3.read()) + sc_biguint<8>(ap_const_lv8_1));
}

void dut_matrix_multiply_alt2::thread_exitcond_flatten4_fu_188_p2() {
    exitcond_flatten4_fu_188_p2 = (!indvar_flatten4_reg_123.read().is_01() || !ap_const_lv22_2FDA00.is_01())? sc_lv<1>(): sc_lv<1>(indvar_flatten4_reg_123.read() == ap_const_lv22_2FDA00);
}

void dut_matrix_multiply_alt2::thread_exitcond_flatten_fu_206_p2() {
    exitcond_flatten_fu_206_p2 = (!indvar_flatten_reg_145.read().is_01() || !ap_const_lv13_FA0.is_01())? sc_lv<1>(): sc_lv<1>(indvar_flatten_reg_145.read() == ap_const_lv13_FA0);
}

void dut_matrix_multiply_alt2::thread_exitcond_fu_274_p2() {
    exitcond_fu_274_p2 = (!Col_assign_reg_167.read().is_01() || !ap_const_lv8_C8.is_01())? sc_lv<1>(): sc_lv<1>(Col_assign_reg_167.read() == ap_const_lv8_C8);
}

void dut_matrix_multiply_alt2::thread_exitcond_mid_fu_280_p2() {
    exitcond_mid_fu_280_p2 = (exitcond_fu_274_p2.read() & not_exitcond_flatten_fu_268_p2.read());
}

void dut_matrix_multiply_alt2::thread_grp_fu_365_p0() {
    grp_fu_365_p0 =  (sc_lv<5>) (grp_fu_365_p00.read());
}

void dut_matrix_multiply_alt2::thread_grp_fu_365_p00() {
    grp_fu_365_p00 = esl_zext<13,5>(ap_reg_ppstg_tmp_139_mid2_reg_422_pp0_iter3.read());
}

void dut_matrix_multiply_alt2::thread_grp_fu_365_p1() {
    grp_fu_365_p1 =  (sc_lv<9>) (ap_const_lv13_C8);
}

void dut_matrix_multiply_alt2::thread_grp_fu_365_p2() {
    grp_fu_365_p2 =  (sc_lv<8>) (grp_fu_365_p20.read());
}

void dut_matrix_multiply_alt2::thread_grp_fu_365_p20() {
    grp_fu_365_p20 = esl_zext<13,8>(ap_reg_ppstg_Col_assign_mid2_reg_416_pp0_iter3.read());
}

void dut_matrix_multiply_alt2::thread_grp_fu_374_p0() {
    grp_fu_374_p0 =  (sc_lv<10>) (grp_fu_374_p00.read());
}

void dut_matrix_multiply_alt2::thread_grp_fu_374_p00() {
    grp_fu_374_p00 = esl_zext<18,10>(tmp_i_i_mid2_v_reg_409.read());
}

void dut_matrix_multiply_alt2::thread_grp_fu_374_p1() {
    grp_fu_374_p1 =  (sc_lv<9>) (ap_const_lv18_C8);
}

void dut_matrix_multiply_alt2::thread_grp_fu_374_p2() {
    grp_fu_374_p2 =  (sc_lv<8>) (grp_fu_374_p20.read());
}

void dut_matrix_multiply_alt2::thread_grp_fu_374_p20() {
    grp_fu_374_p20 = esl_zext<18,8>(Col_assign_mid2_reg_416.read());
}

void dut_matrix_multiply_alt2::thread_grp_fu_383_p0() {
    grp_fu_383_p0 =  (sc_lv<5>) (grp_fu_383_p00.read());
}

void dut_matrix_multiply_alt2::thread_grp_fu_383_p00() {
    grp_fu_383_p00 = esl_zext<15,5>(tmp_139_mid2_reg_422.read());
}

void dut_matrix_multiply_alt2::thread_grp_fu_383_p1() {
    grp_fu_383_p1 =  (sc_lv<11>) (ap_const_lv15_310);
}

void dut_matrix_multiply_alt2::thread_grp_fu_383_p2() {
    grp_fu_383_p2 =  (sc_lv<10>) (grp_fu_383_p20.read());
}

void dut_matrix_multiply_alt2::thread_grp_fu_383_p20() {
    grp_fu_383_p20 = esl_zext<15,10>(tmp_i_i_mid2_v_reg_409.read());
}

void dut_matrix_multiply_alt2::thread_indvar_flatten_next4_fu_194_p2() {
    indvar_flatten_next4_fu_194_p2 = (!indvar_flatten4_reg_123.read().is_01() || !ap_const_lv22_1.is_01())? sc_lv<22>(): (sc_biguint<22>(indvar_flatten4_reg_123.read()) + sc_biguint<22>(ap_const_lv22_1));
}

void dut_matrix_multiply_alt2::thread_indvar_flatten_next_fu_326_p3() {
    indvar_flatten_next_fu_326_p3 = (!exitcond_flatten_fu_206_p2.read()[0].is_01())? sc_lv<13>(): ((exitcond_flatten_fu_206_p2.read()[0].to_bool())? ap_const_lv13_1: indvar_flatten_op_fu_320_p2.read());
}

void dut_matrix_multiply_alt2::thread_indvar_flatten_op_fu_320_p2() {
    indvar_flatten_op_fu_320_p2 = (!indvar_flatten_reg_145.read().is_01() || !ap_const_lv13_1.is_01())? sc_lv<13>(): (sc_biguint<13>(indvar_flatten_reg_145.read()) + sc_biguint<13>(ap_const_lv13_1));
}

void dut_matrix_multiply_alt2::thread_k_fu_200_p2() {
    k_fu_200_p2 = (!Col_assign_3_phi_fu_138_p4.read().is_01() || !ap_const_lv10_1.is_01())? sc_lv<10>(): (sc_biguint<10>(Col_assign_3_phi_fu_138_p4.read()) + sc_biguint<10>(ap_const_lv10_1));
}

void dut_matrix_multiply_alt2::thread_not_exitcond_flatten_fu_268_p2() {
    not_exitcond_flatten_fu_268_p2 = (exitcond_flatten_fu_206_p2.read() ^ ap_const_lv1_1);
}

void dut_matrix_multiply_alt2::thread_r_fu_286_p2() {
    r_fu_286_p2 = (!Row_assign_mid_fu_212_p3.read().is_01() || !ap_const_lv5_1.is_01())? sc_lv<5>(): (sc_biguint<5>(Row_assign_mid_fu_212_p3.read()) + sc_biguint<5>(ap_const_lv5_1));
}

void dut_matrix_multiply_alt2::thread_sum_mult_address0() {
    sum_mult_address0 =  (sc_lv<12>) (tmp_187_cast_fu_360_p1.read());
}

void dut_matrix_multiply_alt2::thread_sum_mult_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it4.read())) {
        sum_mult_ce0 = ap_const_logic_1;
    } else {
        sum_mult_ce0 = ap_const_logic_0;
    }
}

void dut_matrix_multiply_alt2::thread_sum_mult_ce1() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it11.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_tmp_mid2_reg_401_pp0_iter10.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_tmp_mid2_29_reg_405_pp0_iter10.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it11.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_tmp_mid2_reg_401_pp0_iter10.read())))) {
        sum_mult_ce1 = ap_const_logic_1;
    } else {
        sum_mult_ce1 = ap_const_logic_0;
    }
}

void dut_matrix_multiply_alt2::thread_sum_mult_d1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it11.read())) {
        if (!esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_tmp_mid2_reg_401_pp0_iter10.read())) {
            sum_mult_d1 = ap_reg_ppstg_mult_reg_470_pp0_iter10.read();
        } else if (ap_sig_239.read()) {
            sum_mult_d1 = tmp_139_reg_481.read();
        } else {
            sum_mult_d1 = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        }
    } else {
        sum_mult_d1 = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    }
}

void dut_matrix_multiply_alt2::thread_sum_mult_we1() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it11.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_tmp_mid2_reg_401_pp0_iter10.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_tmp_mid2_29_reg_405_pp0_iter10.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it11.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_tmp_mid2_reg_401_pp0_iter10.read())))) {
        sum_mult_we1 = ap_const_logic_1;
    } else {
        sum_mult_we1 = ap_const_logic_0;
    }
}

void dut_matrix_multiply_alt2::thread_tmp2_fu_226_p2() {
    tmp2_fu_226_p2 = (!Col_assign_3_phi_fu_138_p4.read().is_01() || !ap_const_lv10_0.is_01())? sc_lv<1>(): sc_lv<1>(Col_assign_3_phi_fu_138_p4.read() == ap_const_lv10_0);
}

void dut_matrix_multiply_alt2::thread_tmp_139_mid2_fu_306_p3() {
    tmp_139_mid2_fu_306_p3 = (!exitcond_mid_fu_280_p2.read()[0].is_01())? sc_lv<5>(): ((exitcond_mid_fu_280_p2.read()[0].to_bool())? r_fu_286_p2.read(): Row_assign_mid_fu_212_p3.read());
}

void dut_matrix_multiply_alt2::thread_tmp_165_fu_292_p2() {
    tmp_165_fu_292_p2 = (exitcond_mid_fu_280_p2.read() | exitcond_flatten_fu_206_p2.read());
}

void dut_matrix_multiply_alt2::thread_tmp_184_cast_fu_343_p1() {
    tmp_184_cast_fu_343_p1 = esl_sext<64,15>(grp_fu_383_p3.read());
}

void dut_matrix_multiply_alt2::thread_tmp_186_cast_fu_350_p1() {
    tmp_186_cast_fu_350_p1 = esl_zext<64,18>(grp_fu_374_p3.read());
}

void dut_matrix_multiply_alt2::thread_tmp_187_cast_fu_360_p1() {
    tmp_187_cast_fu_360_p1 = esl_sext<64,13>(grp_fu_365_p3.read());
}

void dut_matrix_multiply_alt2::thread_tmp_1_fu_246_p2() {
    tmp_1_fu_246_p2 = (!Col_assign_3_phi_fu_138_p4.read().is_01() || !ap_const_lv10_30F.is_01())? sc_lv<1>(): sc_lv<1>(Col_assign_3_phi_fu_138_p4.read() == ap_const_lv10_30F);
}

void dut_matrix_multiply_alt2::thread_tmp_i_i_mid2_v_fu_260_p3() {
    tmp_i_i_mid2_v_fu_260_p3 = (!exitcond_flatten_fu_206_p2.read()[0].is_01())? sc_lv<10>(): ((exitcond_flatten_fu_206_p2.read()[0].to_bool())? k_fu_200_p2.read(): Col_assign_3_phi_fu_138_p4.read());
}

void dut_matrix_multiply_alt2::thread_tmp_mid1_28_fu_240_p2() {
    tmp_mid1_28_fu_240_p2 = (!k_fu_200_p2.read().is_01() || !ap_const_lv10_30F.is_01())? sc_lv<1>(): sc_lv<1>(k_fu_200_p2.read() == ap_const_lv10_30F);
}

void dut_matrix_multiply_alt2::thread_tmp_mid1_fu_220_p2() {
    tmp_mid1_fu_220_p2 = (!k_fu_200_p2.read().is_01() || !ap_const_lv10_0.is_01())? sc_lv<1>(): sc_lv<1>(k_fu_200_p2.read() == ap_const_lv10_0);
}

void dut_matrix_multiply_alt2::thread_tmp_mid2_29_fu_252_p3() {
    tmp_mid2_29_fu_252_p3 = (!exitcond_flatten_fu_206_p2.read()[0].is_01())? sc_lv<1>(): ((exitcond_flatten_fu_206_p2.read()[0].to_bool())? tmp_mid1_28_fu_240_p2.read(): tmp_1_fu_246_p2.read());
}

void dut_matrix_multiply_alt2::thread_tmp_mid2_fu_232_p3() {
    tmp_mid2_fu_232_p3 = (!exitcond_flatten_fu_206_p2.read()[0].is_01())? sc_lv<1>(): ((exitcond_flatten_fu_206_p2.read()[0].to_bool())? tmp_mid1_fu_220_p2.read(): tmp2_fu_226_p2.read());
}

void dut_matrix_multiply_alt2::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if (!esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) {
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_1;
            } else {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            }
            break;
        case 2 : 
            if ((!(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it11.read()) && !esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it10.read())) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && !esl_seteq<1,1,1>(exitcond_flatten4_fu_188_p2.read(), ap_const_lv1_0) && !esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_1;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && !esl_seteq<1,1,1>(exitcond_flatten4_fu_188_p2.read(), ap_const_lv1_0) && !esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()))) {
                ap_NS_fsm = ap_ST_st14_fsm_2;
            } else {
                ap_NS_fsm = ap_ST_st14_fsm_2;
            }
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_st1_fsm_0;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<3>) ("XXX");
            break;
    }
}

}

