// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.2
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "dut_matrix_multiply_alt26.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic dut_matrix_multiply_alt26::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic dut_matrix_multiply_alt26::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<3> dut_matrix_multiply_alt26::ap_ST_st1_fsm_0 = "1";
const sc_lv<3> dut_matrix_multiply_alt26::ap_ST_pp0_stg0_fsm_1 = "10";
const sc_lv<3> dut_matrix_multiply_alt26::ap_ST_st15_fsm_2 = "100";
const bool dut_matrix_multiply_alt26::ap_true = true;
const sc_lv<32> dut_matrix_multiply_alt26::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> dut_matrix_multiply_alt26::ap_const_lv1_1 = "1";
const sc_lv<32> dut_matrix_multiply_alt26::ap_const_lv32_1 = "1";
const sc_lv<1> dut_matrix_multiply_alt26::ap_const_lv1_0 = "0";
const sc_lv<26> dut_matrix_multiply_alt26::ap_const_lv26_0 = "00000000000000000000000000";
const sc_lv<7> dut_matrix_multiply_alt26::ap_const_lv7_0 = "0000000";
const sc_lv<20> dut_matrix_multiply_alt26::ap_const_lv20_0 = "00000000000000000000";
const sc_lv<10> dut_matrix_multiply_alt26::ap_const_lv10_0 = "0000000000";
const sc_lv<26> dut_matrix_multiply_alt26::ap_const_lv26_3A9E400 = "11101010011110010000000000";
const sc_lv<26> dut_matrix_multiply_alt26::ap_const_lv26_1 = "1";
const sc_lv<7> dut_matrix_multiply_alt26::ap_const_lv7_1 = "1";
const sc_lv<20> dut_matrix_multiply_alt26::ap_const_lv20_96100 = "10010110000100000000";
const sc_lv<7> dut_matrix_multiply_alt26::ap_const_lv7_63 = "1100011";
const sc_lv<10> dut_matrix_multiply_alt26::ap_const_lv10_310 = "1100010000";
const sc_lv<10> dut_matrix_multiply_alt26::ap_const_lv10_1 = "1";
const sc_lv<20> dut_matrix_multiply_alt26::ap_const_lv20_1 = "1";
const sc_lv<20> dut_matrix_multiply_alt26::ap_const_lv20_310 = "1100010000";
const sc_lv<17> dut_matrix_multiply_alt26::ap_const_lv17_310 = "1100010000";
const sc_lv<17> dut_matrix_multiply_alt26::ap_const_lv17_64 = "1100100";
const sc_lv<32> dut_matrix_multiply_alt26::ap_const_lv32_2 = "10";

dut_matrix_multiply_alt26::dut_matrix_multiply_alt26(sc_module_name name) : sc_module(name), mVcdFile(0) {
    sum_mult_U = new dut_matrix_multiply_alt26_sum_mult("sum_mult_U");
    sum_mult_U->clk(ap_clk);
    sum_mult_U->reset(ap_rst);
    sum_mult_U->address0(sum_mult_address0);
    sum_mult_U->ce0(sum_mult_ce0);
    sum_mult_U->q0(sum_mult_q0);
    sum_mult_U->address1(ap_reg_ppstg_sum_mult_addr_reg_455_pp0_iter10);
    sum_mult_U->ce1(sum_mult_ce1);
    sum_mult_U->we1(sum_mult_we1);
    sum_mult_U->d1(sum_mult_d1);
    dut_fadd_32ns_32ns_32_5_full_dsp_U5 = new dut_fadd_32ns_32ns_32_5_full_dsp<1,5,32,32,32>("dut_fadd_32ns_32ns_32_5_full_dsp_U5");
    dut_fadd_32ns_32ns_32_5_full_dsp_U5->clk(ap_clk);
    dut_fadd_32ns_32ns_32_5_full_dsp_U5->reset(ap_rst);
    dut_fadd_32ns_32ns_32_5_full_dsp_U5->din0(sum_mult_load_reg_472);
    dut_fadd_32ns_32ns_32_5_full_dsp_U5->din1(mult_reg_466);
    dut_fadd_32ns_32ns_32_5_full_dsp_U5->ce(ap_var_for_const0);
    dut_fadd_32ns_32ns_32_5_full_dsp_U5->dout(grp_fu_174_p2);
    dut_fmul_32ns_32ns_32_4_max_dsp_U6 = new dut_fmul_32ns_32ns_32_4_max_dsp<1,4,32,32,32>("dut_fmul_32ns_32ns_32_4_max_dsp_U6");
    dut_fmul_32ns_32ns_32_4_max_dsp_U6->clk(ap_clk);
    dut_fmul_32ns_32ns_32_4_max_dsp_U6->reset(ap_rst);
    dut_fmul_32ns_32ns_32_4_max_dsp_U6->din0(A_q0);
    dut_fmul_32ns_32ns_32_4_max_dsp_U6->din1(B_q0);
    dut_fmul_32ns_32ns_32_4_max_dsp_U6->ce(ap_var_for_const0);
    dut_fmul_32ns_32ns_32_4_max_dsp_U6->dout(grp_fu_178_p2);
    dut_mac_muladd_10ns_11ns_10ns_20_1_U7 = new dut_mac_muladd_10ns_11ns_10ns_20_1<1,1,10,11,10,20>("dut_mac_muladd_10ns_11ns_10ns_20_1_U7");
    dut_mac_muladd_10ns_11ns_10ns_20_1_U7->din0(grp_fu_361_p0);
    dut_mac_muladd_10ns_11ns_10ns_20_1_U7->din1(grp_fu_361_p1);
    dut_mac_muladd_10ns_11ns_10ns_20_1_U7->din2(grp_fu_361_p2);
    dut_mac_muladd_10ns_11ns_10ns_20_1_U7->dout(grp_fu_361_p3);
    dut_mac_muladd_7ns_11ns_10ns_17_1_U8 = new dut_mac_muladd_7ns_11ns_10ns_17_1<1,1,7,11,10,17>("dut_mac_muladd_7ns_11ns_10ns_17_1_U8");
    dut_mac_muladd_7ns_11ns_10ns_17_1_U8->din0(grp_fu_370_p0);
    dut_mac_muladd_7ns_11ns_10ns_17_1_U8->din1(grp_fu_370_p1);
    dut_mac_muladd_7ns_11ns_10ns_17_1_U8->din2(grp_fu_370_p2);
    dut_mac_muladd_7ns_11ns_10ns_17_1_U8->dout(grp_fu_370_p3);
    dut_mac_muladd_10ns_8ns_7ns_17_1_U9 = new dut_mac_muladd_10ns_8ns_7ns_17_1<1,1,10,8,7,17>("dut_mac_muladd_10ns_8ns_7ns_17_1_U9");
    dut_mac_muladd_10ns_8ns_7ns_17_1_U9->din0(grp_fu_379_p0);
    dut_mac_muladd_10ns_8ns_7ns_17_1_U9->din1(grp_fu_379_p1);
    dut_mac_muladd_10ns_8ns_7ns_17_1_U9->din2(grp_fu_379_p2);
    dut_mac_muladd_10ns_8ns_7ns_17_1_U9->dout(grp_fu_379_p3);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_A_address0);
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( tmp_55_cast_fu_339_p1 );

    SC_METHOD(thread_A_ce0);
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );

    SC_METHOD(thread_B_address0);
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( tmp_57_cast_fu_346_p1 );

    SC_METHOD(thread_B_ce0);
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );

    SC_METHOD(thread_C_address0);
    sensitive << ( ap_reg_ppiten_pp0_it11 );
    sensitive << ( ap_reg_ppstg_C_addr_reg_450_pp0_iter10 );

    SC_METHOD(thread_C_ce0);
    sensitive << ( ap_reg_ppiten_pp0_it11 );
    sensitive << ( ap_reg_ppiten_pp0_it12 );

    SC_METHOD(thread_C_d0);
    sensitive << ( ap_reg_ppiten_pp0_it11 );
    sensitive << ( tmp_36_reg_477 );

    SC_METHOD(thread_C_we0);
    sensitive << ( ap_reg_ppiten_pp0_it11 );
    sensitive << ( ap_reg_ppstg_tmp_mid2_reg_397_pp0_iter10 );
    sensitive << ( ap_reg_ppstg_tmp_mid2_21_reg_401_pp0_iter10 );

    SC_METHOD(thread_Col_assign_2_phi_fu_134_p4);
    sensitive << ( Col_assign_2_reg_130 );
    sensitive << ( exitcond_flatten1_reg_388 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( tmp_i_i_mid2_v_reg_405 );

    SC_METHOD(thread_Col_assign_mid2_fu_294_p3);
    sensitive << ( Col_assign_reg_163 );
    sensitive << ( tmp_47_fu_288_p2 );

    SC_METHOD(thread_Row_assign_mid_fu_208_p3);
    sensitive << ( Row_assign_phi_fu_156_p4 );
    sensitive << ( exitcond_flatten_fu_202_p2 );

    SC_METHOD(thread_Row_assign_phi_fu_156_p4);
    sensitive << ( Row_assign_reg_152 );
    sensitive << ( exitcond_flatten1_reg_388 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( tmp_34_mid2_reg_418 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( ap_sig_cseq_ST_st15_fsm_2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_sig_cseq_ST_st15_fsm_2 );

    SC_METHOD(thread_ap_sig_20);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_250);
    sensitive << ( ap_reg_ppstg_tmp_mid2_reg_397_pp0_iter10 );
    sensitive << ( ap_reg_ppstg_tmp_mid2_21_reg_401_pp0_iter10 );

    SC_METHOD(thread_ap_sig_415);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_61);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_cseq_ST_pp0_stg0_fsm_1);
    sensitive << ( ap_sig_61 );

    SC_METHOD(thread_ap_sig_cseq_ST_st15_fsm_2);
    sensitive << ( ap_sig_415 );

    SC_METHOD(thread_ap_sig_cseq_ST_st1_fsm_0);
    sensitive << ( ap_sig_20 );

    SC_METHOD(thread_c_fu_310_p2);
    sensitive << ( Col_assign_mid2_fu_294_p3 );

    SC_METHOD(thread_exitcond_flatten1_fu_184_p2);
    sensitive << ( indvar_flatten1_reg_119 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );

    SC_METHOD(thread_exitcond_flatten_fu_202_p2);
    sensitive << ( indvar_flatten_reg_141 );
    sensitive << ( exitcond_flatten1_fu_184_p2 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );

    SC_METHOD(thread_exitcond_fu_270_p2);
    sensitive << ( Col_assign_reg_163 );
    sensitive << ( exitcond_flatten1_fu_184_p2 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );

    SC_METHOD(thread_exitcond_mid_fu_276_p2);
    sensitive << ( exitcond_fu_270_p2 );
    sensitive << ( not_exitcond_flatten_fu_264_p2 );

    SC_METHOD(thread_grp_fu_361_p0);
    sensitive << ( ap_reg_ppiten_pp0_it2 );
    sensitive << ( ap_reg_ppstg_exitcond_flatten1_reg_388_pp0_iter1 );
    sensitive << ( grp_fu_361_p00 );

    SC_METHOD(thread_grp_fu_361_p00);
    sensitive << ( ap_reg_ppstg_tmp_34_mid2_reg_418_pp0_iter1 );

    SC_METHOD(thread_grp_fu_361_p1);
    sensitive << ( ap_reg_ppiten_pp0_it2 );
    sensitive << ( ap_reg_ppstg_exitcond_flatten1_reg_388_pp0_iter1 );

    SC_METHOD(thread_grp_fu_361_p2);
    sensitive << ( ap_reg_ppiten_pp0_it2 );
    sensitive << ( ap_reg_ppstg_exitcond_flatten1_reg_388_pp0_iter1 );
    sensitive << ( grp_fu_361_p20 );

    SC_METHOD(thread_grp_fu_361_p20);
    sensitive << ( ap_reg_ppstg_Col_assign_mid2_reg_412_pp0_iter1 );

    SC_METHOD(thread_grp_fu_370_p0);
    sensitive << ( exitcond_flatten1_reg_388 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( grp_fu_370_p00 );

    SC_METHOD(thread_grp_fu_370_p00);
    sensitive << ( tmp_i_i_mid2_v_reg_405 );

    SC_METHOD(thread_grp_fu_370_p1);
    sensitive << ( exitcond_flatten1_reg_388 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );

    SC_METHOD(thread_grp_fu_370_p2);
    sensitive << ( exitcond_flatten1_reg_388 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( grp_fu_370_p20 );

    SC_METHOD(thread_grp_fu_370_p20);
    sensitive << ( Col_assign_mid2_reg_412 );

    SC_METHOD(thread_grp_fu_379_p0);
    sensitive << ( exitcond_flatten1_reg_388 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( grp_fu_379_p00 );

    SC_METHOD(thread_grp_fu_379_p00);
    sensitive << ( tmp_34_mid2_reg_418 );

    SC_METHOD(thread_grp_fu_379_p1);
    sensitive << ( exitcond_flatten1_reg_388 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );

    SC_METHOD(thread_grp_fu_379_p2);
    sensitive << ( exitcond_flatten1_reg_388 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( grp_fu_379_p20 );

    SC_METHOD(thread_grp_fu_379_p20);
    sensitive << ( tmp_i_i_mid2_v_reg_405 );

    SC_METHOD(thread_indvar_flatten_next1_fu_190_p2);
    sensitive << ( indvar_flatten1_reg_119 );

    SC_METHOD(thread_indvar_flatten_next_fu_322_p3);
    sensitive << ( exitcond_flatten_fu_202_p2 );
    sensitive << ( indvar_flatten_op_fu_316_p2 );

    SC_METHOD(thread_indvar_flatten_op_fu_316_p2);
    sensitive << ( indvar_flatten_reg_141 );

    SC_METHOD(thread_k_fu_196_p2);
    sensitive << ( Col_assign_2_phi_fu_134_p4 );

    SC_METHOD(thread_not_exitcond_flatten_fu_264_p2);
    sensitive << ( exitcond_flatten_fu_202_p2 );

    SC_METHOD(thread_r_fu_282_p2);
    sensitive << ( Row_assign_mid_fu_208_p3 );

    SC_METHOD(thread_sum_mult_address0);
    sensitive << ( ap_reg_ppiten_pp0_it2 );
    sensitive << ( tmp_58_cast_fu_356_p1 );

    SC_METHOD(thread_sum_mult_ce0);
    sensitive << ( ap_reg_ppiten_pp0_it2 );
    sensitive << ( ap_reg_ppiten_pp0_it3 );
    sensitive << ( ap_reg_ppiten_pp0_it4 );
    sensitive << ( ap_reg_ppiten_pp0_it5 );

    SC_METHOD(thread_sum_mult_ce1);
    sensitive << ( ap_reg_ppiten_pp0_it11 );
    sensitive << ( ap_reg_ppiten_pp0_it12 );
    sensitive << ( ap_reg_ppstg_tmp_mid2_reg_397_pp0_iter10 );
    sensitive << ( ap_reg_ppstg_tmp_mid2_21_reg_401_pp0_iter10 );

    SC_METHOD(thread_sum_mult_d1);
    sensitive << ( ap_reg_ppiten_pp0_it11 );
    sensitive << ( ap_reg_ppstg_tmp_mid2_reg_397_pp0_iter10 );
    sensitive << ( ap_reg_ppstg_mult_reg_466_pp0_iter10 );
    sensitive << ( tmp_36_reg_477 );
    sensitive << ( ap_sig_250 );

    SC_METHOD(thread_sum_mult_we1);
    sensitive << ( ap_reg_ppiten_pp0_it11 );
    sensitive << ( ap_reg_ppstg_tmp_mid2_reg_397_pp0_iter10 );
    sensitive << ( ap_reg_ppstg_tmp_mid2_21_reg_401_pp0_iter10 );

    SC_METHOD(thread_tmp2_fu_222_p2);
    sensitive << ( exitcond_flatten1_fu_184_p2 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( Col_assign_2_phi_fu_134_p4 );

    SC_METHOD(thread_tmp_1_fu_242_p2);
    sensitive << ( exitcond_flatten1_fu_184_p2 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( Col_assign_2_phi_fu_134_p4 );

    SC_METHOD(thread_tmp_34_mid2_fu_302_p3);
    sensitive << ( Row_assign_mid_fu_208_p3 );
    sensitive << ( exitcond_mid_fu_276_p2 );
    sensitive << ( r_fu_282_p2 );

    SC_METHOD(thread_tmp_47_fu_288_p2);
    sensitive << ( exitcond_flatten_fu_202_p2 );
    sensitive << ( exitcond_mid_fu_276_p2 );

    SC_METHOD(thread_tmp_55_cast_fu_339_p1);
    sensitive << ( grp_fu_379_p3 );

    SC_METHOD(thread_tmp_57_cast_fu_346_p1);
    sensitive << ( grp_fu_370_p3 );

    SC_METHOD(thread_tmp_58_cast_fu_356_p1);
    sensitive << ( grp_fu_361_p3 );

    SC_METHOD(thread_tmp_i_i_mid2_v_fu_256_p3);
    sensitive << ( Col_assign_2_phi_fu_134_p4 );
    sensitive << ( exitcond_flatten_fu_202_p2 );
    sensitive << ( k_fu_196_p2 );

    SC_METHOD(thread_tmp_mid1_20_fu_236_p2);
    sensitive << ( exitcond_flatten1_fu_184_p2 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( k_fu_196_p2 );

    SC_METHOD(thread_tmp_mid1_fu_216_p2);
    sensitive << ( exitcond_flatten1_fu_184_p2 );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_1 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( k_fu_196_p2 );

    SC_METHOD(thread_tmp_mid2_21_fu_248_p3);
    sensitive << ( exitcond_flatten_fu_202_p2 );
    sensitive << ( tmp_mid1_20_fu_236_p2 );
    sensitive << ( tmp_1_fu_242_p2 );

    SC_METHOD(thread_tmp_mid2_fu_228_p3);
    sensitive << ( exitcond_flatten_fu_202_p2 );
    sensitive << ( tmp_mid1_fu_216_p2 );
    sensitive << ( tmp2_fu_222_p2 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( exitcond_flatten1_fu_184_p2 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_reg_ppiten_pp0_it11 );
    sensitive << ( ap_reg_ppiten_pp0_it12 );

    SC_THREAD(thread_ap_var_for_const0);

    ap_CS_fsm = "001";
    ap_reg_ppiten_pp0_it0 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it1 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it2 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it3 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it4 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it5 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it6 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it7 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it8 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it9 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it10 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it11 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it12 = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "dut_matrix_multiply_alt26_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, A_address0, "(port)A_address0");
    sc_trace(mVcdFile, A_ce0, "(port)A_ce0");
    sc_trace(mVcdFile, A_q0, "(port)A_q0");
    sc_trace(mVcdFile, B_address0, "(port)B_address0");
    sc_trace(mVcdFile, B_ce0, "(port)B_ce0");
    sc_trace(mVcdFile, B_q0, "(port)B_q0");
    sc_trace(mVcdFile, C_address0, "(port)C_address0");
    sc_trace(mVcdFile, C_ce0, "(port)C_ce0");
    sc_trace(mVcdFile, C_we0, "(port)C_we0");
    sc_trace(mVcdFile, C_d0, "(port)C_d0");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st1_fsm_0, "ap_sig_cseq_ST_st1_fsm_0");
    sc_trace(mVcdFile, ap_sig_20, "ap_sig_20");
    sc_trace(mVcdFile, indvar_flatten1_reg_119, "indvar_flatten1_reg_119");
    sc_trace(mVcdFile, Col_assign_2_reg_130, "Col_assign_2_reg_130");
    sc_trace(mVcdFile, indvar_flatten_reg_141, "indvar_flatten_reg_141");
    sc_trace(mVcdFile, Row_assign_reg_152, "Row_assign_reg_152");
    sc_trace(mVcdFile, Col_assign_reg_163, "Col_assign_reg_163");
    sc_trace(mVcdFile, exitcond_flatten1_fu_184_p2, "exitcond_flatten1_fu_184_p2");
    sc_trace(mVcdFile, exitcond_flatten1_reg_388, "exitcond_flatten1_reg_388");
    sc_trace(mVcdFile, ap_sig_cseq_ST_pp0_stg0_fsm_1, "ap_sig_cseq_ST_pp0_stg0_fsm_1");
    sc_trace(mVcdFile, ap_sig_61, "ap_sig_61");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it0, "ap_reg_ppiten_pp0_it0");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it1, "ap_reg_ppiten_pp0_it1");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it2, "ap_reg_ppiten_pp0_it2");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it3, "ap_reg_ppiten_pp0_it3");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it4, "ap_reg_ppiten_pp0_it4");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it5, "ap_reg_ppiten_pp0_it5");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it6, "ap_reg_ppiten_pp0_it6");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it7, "ap_reg_ppiten_pp0_it7");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it8, "ap_reg_ppiten_pp0_it8");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it9, "ap_reg_ppiten_pp0_it9");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it10, "ap_reg_ppiten_pp0_it10");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it11, "ap_reg_ppiten_pp0_it11");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it12, "ap_reg_ppiten_pp0_it12");
    sc_trace(mVcdFile, ap_reg_ppstg_exitcond_flatten1_reg_388_pp0_iter1, "ap_reg_ppstg_exitcond_flatten1_reg_388_pp0_iter1");
    sc_trace(mVcdFile, ap_reg_ppstg_exitcond_flatten1_reg_388_pp0_iter2, "ap_reg_ppstg_exitcond_flatten1_reg_388_pp0_iter2");
    sc_trace(mVcdFile, ap_reg_ppstg_exitcond_flatten1_reg_388_pp0_iter3, "ap_reg_ppstg_exitcond_flatten1_reg_388_pp0_iter3");
    sc_trace(mVcdFile, ap_reg_ppstg_exitcond_flatten1_reg_388_pp0_iter4, "ap_reg_ppstg_exitcond_flatten1_reg_388_pp0_iter4");
    sc_trace(mVcdFile, indvar_flatten_next1_fu_190_p2, "indvar_flatten_next1_fu_190_p2");
    sc_trace(mVcdFile, tmp_mid2_fu_228_p3, "tmp_mid2_fu_228_p3");
    sc_trace(mVcdFile, tmp_mid2_reg_397, "tmp_mid2_reg_397");
    sc_trace(mVcdFile, ap_reg_ppstg_tmp_mid2_reg_397_pp0_iter1, "ap_reg_ppstg_tmp_mid2_reg_397_pp0_iter1");
    sc_trace(mVcdFile, ap_reg_ppstg_tmp_mid2_reg_397_pp0_iter2, "ap_reg_ppstg_tmp_mid2_reg_397_pp0_iter2");
    sc_trace(mVcdFile, ap_reg_ppstg_tmp_mid2_reg_397_pp0_iter3, "ap_reg_ppstg_tmp_mid2_reg_397_pp0_iter3");
    sc_trace(mVcdFile, ap_reg_ppstg_tmp_mid2_reg_397_pp0_iter4, "ap_reg_ppstg_tmp_mid2_reg_397_pp0_iter4");
    sc_trace(mVcdFile, ap_reg_ppstg_tmp_mid2_reg_397_pp0_iter5, "ap_reg_ppstg_tmp_mid2_reg_397_pp0_iter5");
    sc_trace(mVcdFile, ap_reg_ppstg_tmp_mid2_reg_397_pp0_iter6, "ap_reg_ppstg_tmp_mid2_reg_397_pp0_iter6");
    sc_trace(mVcdFile, ap_reg_ppstg_tmp_mid2_reg_397_pp0_iter7, "ap_reg_ppstg_tmp_mid2_reg_397_pp0_iter7");
    sc_trace(mVcdFile, ap_reg_ppstg_tmp_mid2_reg_397_pp0_iter8, "ap_reg_ppstg_tmp_mid2_reg_397_pp0_iter8");
    sc_trace(mVcdFile, ap_reg_ppstg_tmp_mid2_reg_397_pp0_iter9, "ap_reg_ppstg_tmp_mid2_reg_397_pp0_iter9");
    sc_trace(mVcdFile, ap_reg_ppstg_tmp_mid2_reg_397_pp0_iter10, "ap_reg_ppstg_tmp_mid2_reg_397_pp0_iter10");
    sc_trace(mVcdFile, tmp_mid2_21_fu_248_p3, "tmp_mid2_21_fu_248_p3");
    sc_trace(mVcdFile, tmp_mid2_21_reg_401, "tmp_mid2_21_reg_401");
    sc_trace(mVcdFile, ap_reg_ppstg_tmp_mid2_21_reg_401_pp0_iter1, "ap_reg_ppstg_tmp_mid2_21_reg_401_pp0_iter1");
    sc_trace(mVcdFile, ap_reg_ppstg_tmp_mid2_21_reg_401_pp0_iter2, "ap_reg_ppstg_tmp_mid2_21_reg_401_pp0_iter2");
    sc_trace(mVcdFile, ap_reg_ppstg_tmp_mid2_21_reg_401_pp0_iter3, "ap_reg_ppstg_tmp_mid2_21_reg_401_pp0_iter3");
    sc_trace(mVcdFile, ap_reg_ppstg_tmp_mid2_21_reg_401_pp0_iter4, "ap_reg_ppstg_tmp_mid2_21_reg_401_pp0_iter4");
    sc_trace(mVcdFile, ap_reg_ppstg_tmp_mid2_21_reg_401_pp0_iter5, "ap_reg_ppstg_tmp_mid2_21_reg_401_pp0_iter5");
    sc_trace(mVcdFile, ap_reg_ppstg_tmp_mid2_21_reg_401_pp0_iter6, "ap_reg_ppstg_tmp_mid2_21_reg_401_pp0_iter6");
    sc_trace(mVcdFile, ap_reg_ppstg_tmp_mid2_21_reg_401_pp0_iter7, "ap_reg_ppstg_tmp_mid2_21_reg_401_pp0_iter7");
    sc_trace(mVcdFile, ap_reg_ppstg_tmp_mid2_21_reg_401_pp0_iter8, "ap_reg_ppstg_tmp_mid2_21_reg_401_pp0_iter8");
    sc_trace(mVcdFile, ap_reg_ppstg_tmp_mid2_21_reg_401_pp0_iter9, "ap_reg_ppstg_tmp_mid2_21_reg_401_pp0_iter9");
    sc_trace(mVcdFile, ap_reg_ppstg_tmp_mid2_21_reg_401_pp0_iter10, "ap_reg_ppstg_tmp_mid2_21_reg_401_pp0_iter10");
    sc_trace(mVcdFile, tmp_i_i_mid2_v_fu_256_p3, "tmp_i_i_mid2_v_fu_256_p3");
    sc_trace(mVcdFile, tmp_i_i_mid2_v_reg_405, "tmp_i_i_mid2_v_reg_405");
    sc_trace(mVcdFile, Col_assign_mid2_fu_294_p3, "Col_assign_mid2_fu_294_p3");
    sc_trace(mVcdFile, Col_assign_mid2_reg_412, "Col_assign_mid2_reg_412");
    sc_trace(mVcdFile, ap_reg_ppstg_Col_assign_mid2_reg_412_pp0_iter1, "ap_reg_ppstg_Col_assign_mid2_reg_412_pp0_iter1");
    sc_trace(mVcdFile, tmp_34_mid2_fu_302_p3, "tmp_34_mid2_fu_302_p3");
    sc_trace(mVcdFile, tmp_34_mid2_reg_418, "tmp_34_mid2_reg_418");
    sc_trace(mVcdFile, ap_reg_ppstg_tmp_34_mid2_reg_418_pp0_iter1, "ap_reg_ppstg_tmp_34_mid2_reg_418_pp0_iter1");
    sc_trace(mVcdFile, c_fu_310_p2, "c_fu_310_p2");
    sc_trace(mVcdFile, indvar_flatten_next_fu_322_p3, "indvar_flatten_next_fu_322_p3");
    sc_trace(mVcdFile, C_addr_reg_450, "C_addr_reg_450");
    sc_trace(mVcdFile, ap_reg_ppstg_C_addr_reg_450_pp0_iter3, "ap_reg_ppstg_C_addr_reg_450_pp0_iter3");
    sc_trace(mVcdFile, ap_reg_ppstg_C_addr_reg_450_pp0_iter4, "ap_reg_ppstg_C_addr_reg_450_pp0_iter4");
    sc_trace(mVcdFile, ap_reg_ppstg_C_addr_reg_450_pp0_iter5, "ap_reg_ppstg_C_addr_reg_450_pp0_iter5");
    sc_trace(mVcdFile, ap_reg_ppstg_C_addr_reg_450_pp0_iter6, "ap_reg_ppstg_C_addr_reg_450_pp0_iter6");
    sc_trace(mVcdFile, ap_reg_ppstg_C_addr_reg_450_pp0_iter7, "ap_reg_ppstg_C_addr_reg_450_pp0_iter7");
    sc_trace(mVcdFile, ap_reg_ppstg_C_addr_reg_450_pp0_iter8, "ap_reg_ppstg_C_addr_reg_450_pp0_iter8");
    sc_trace(mVcdFile, ap_reg_ppstg_C_addr_reg_450_pp0_iter9, "ap_reg_ppstg_C_addr_reg_450_pp0_iter9");
    sc_trace(mVcdFile, ap_reg_ppstg_C_addr_reg_450_pp0_iter10, "ap_reg_ppstg_C_addr_reg_450_pp0_iter10");
    sc_trace(mVcdFile, sum_mult_addr_reg_455, "sum_mult_addr_reg_455");
    sc_trace(mVcdFile, ap_reg_ppstg_sum_mult_addr_reg_455_pp0_iter3, "ap_reg_ppstg_sum_mult_addr_reg_455_pp0_iter3");
    sc_trace(mVcdFile, ap_reg_ppstg_sum_mult_addr_reg_455_pp0_iter4, "ap_reg_ppstg_sum_mult_addr_reg_455_pp0_iter4");
    sc_trace(mVcdFile, ap_reg_ppstg_sum_mult_addr_reg_455_pp0_iter5, "ap_reg_ppstg_sum_mult_addr_reg_455_pp0_iter5");
    sc_trace(mVcdFile, ap_reg_ppstg_sum_mult_addr_reg_455_pp0_iter6, "ap_reg_ppstg_sum_mult_addr_reg_455_pp0_iter6");
    sc_trace(mVcdFile, ap_reg_ppstg_sum_mult_addr_reg_455_pp0_iter7, "ap_reg_ppstg_sum_mult_addr_reg_455_pp0_iter7");
    sc_trace(mVcdFile, ap_reg_ppstg_sum_mult_addr_reg_455_pp0_iter8, "ap_reg_ppstg_sum_mult_addr_reg_455_pp0_iter8");
    sc_trace(mVcdFile, ap_reg_ppstg_sum_mult_addr_reg_455_pp0_iter9, "ap_reg_ppstg_sum_mult_addr_reg_455_pp0_iter9");
    sc_trace(mVcdFile, ap_reg_ppstg_sum_mult_addr_reg_455_pp0_iter10, "ap_reg_ppstg_sum_mult_addr_reg_455_pp0_iter10");
    sc_trace(mVcdFile, grp_fu_178_p2, "grp_fu_178_p2");
    sc_trace(mVcdFile, mult_reg_466, "mult_reg_466");
    sc_trace(mVcdFile, ap_reg_ppstg_mult_reg_466_pp0_iter6, "ap_reg_ppstg_mult_reg_466_pp0_iter6");
    sc_trace(mVcdFile, ap_reg_ppstg_mult_reg_466_pp0_iter7, "ap_reg_ppstg_mult_reg_466_pp0_iter7");
    sc_trace(mVcdFile, ap_reg_ppstg_mult_reg_466_pp0_iter8, "ap_reg_ppstg_mult_reg_466_pp0_iter8");
    sc_trace(mVcdFile, ap_reg_ppstg_mult_reg_466_pp0_iter9, "ap_reg_ppstg_mult_reg_466_pp0_iter9");
    sc_trace(mVcdFile, ap_reg_ppstg_mult_reg_466_pp0_iter10, "ap_reg_ppstg_mult_reg_466_pp0_iter10");
    sc_trace(mVcdFile, sum_mult_q0, "sum_mult_q0");
    sc_trace(mVcdFile, sum_mult_load_reg_472, "sum_mult_load_reg_472");
    sc_trace(mVcdFile, grp_fu_174_p2, "grp_fu_174_p2");
    sc_trace(mVcdFile, tmp_36_reg_477, "tmp_36_reg_477");
    sc_trace(mVcdFile, sum_mult_address0, "sum_mult_address0");
    sc_trace(mVcdFile, sum_mult_ce0, "sum_mult_ce0");
    sc_trace(mVcdFile, sum_mult_ce1, "sum_mult_ce1");
    sc_trace(mVcdFile, sum_mult_we1, "sum_mult_we1");
    sc_trace(mVcdFile, sum_mult_d1, "sum_mult_d1");
    sc_trace(mVcdFile, Col_assign_2_phi_fu_134_p4, "Col_assign_2_phi_fu_134_p4");
    sc_trace(mVcdFile, Row_assign_phi_fu_156_p4, "Row_assign_phi_fu_156_p4");
    sc_trace(mVcdFile, tmp_55_cast_fu_339_p1, "tmp_55_cast_fu_339_p1");
    sc_trace(mVcdFile, tmp_57_cast_fu_346_p1, "tmp_57_cast_fu_346_p1");
    sc_trace(mVcdFile, tmp_58_cast_fu_356_p1, "tmp_58_cast_fu_356_p1");
    sc_trace(mVcdFile, exitcond_flatten_fu_202_p2, "exitcond_flatten_fu_202_p2");
    sc_trace(mVcdFile, k_fu_196_p2, "k_fu_196_p2");
    sc_trace(mVcdFile, tmp_mid1_fu_216_p2, "tmp_mid1_fu_216_p2");
    sc_trace(mVcdFile, tmp2_fu_222_p2, "tmp2_fu_222_p2");
    sc_trace(mVcdFile, tmp_mid1_20_fu_236_p2, "tmp_mid1_20_fu_236_p2");
    sc_trace(mVcdFile, tmp_1_fu_242_p2, "tmp_1_fu_242_p2");
    sc_trace(mVcdFile, exitcond_fu_270_p2, "exitcond_fu_270_p2");
    sc_trace(mVcdFile, not_exitcond_flatten_fu_264_p2, "not_exitcond_flatten_fu_264_p2");
    sc_trace(mVcdFile, Row_assign_mid_fu_208_p3, "Row_assign_mid_fu_208_p3");
    sc_trace(mVcdFile, exitcond_mid_fu_276_p2, "exitcond_mid_fu_276_p2");
    sc_trace(mVcdFile, tmp_47_fu_288_p2, "tmp_47_fu_288_p2");
    sc_trace(mVcdFile, r_fu_282_p2, "r_fu_282_p2");
    sc_trace(mVcdFile, indvar_flatten_op_fu_316_p2, "indvar_flatten_op_fu_316_p2");
    sc_trace(mVcdFile, grp_fu_379_p3, "grp_fu_379_p3");
    sc_trace(mVcdFile, grp_fu_370_p3, "grp_fu_370_p3");
    sc_trace(mVcdFile, grp_fu_361_p3, "grp_fu_361_p3");
    sc_trace(mVcdFile, grp_fu_361_p0, "grp_fu_361_p0");
    sc_trace(mVcdFile, grp_fu_361_p1, "grp_fu_361_p1");
    sc_trace(mVcdFile, grp_fu_361_p2, "grp_fu_361_p2");
    sc_trace(mVcdFile, grp_fu_370_p0, "grp_fu_370_p0");
    sc_trace(mVcdFile, grp_fu_370_p1, "grp_fu_370_p1");
    sc_trace(mVcdFile, grp_fu_370_p2, "grp_fu_370_p2");
    sc_trace(mVcdFile, grp_fu_379_p0, "grp_fu_379_p0");
    sc_trace(mVcdFile, grp_fu_379_p1, "grp_fu_379_p1");
    sc_trace(mVcdFile, grp_fu_379_p2, "grp_fu_379_p2");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st15_fsm_2, "ap_sig_cseq_ST_st15_fsm_2");
    sc_trace(mVcdFile, ap_sig_415, "ap_sig_415");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, grp_fu_361_p00, "grp_fu_361_p00");
    sc_trace(mVcdFile, grp_fu_361_p20, "grp_fu_361_p20");
    sc_trace(mVcdFile, grp_fu_370_p00, "grp_fu_370_p00");
    sc_trace(mVcdFile, grp_fu_370_p20, "grp_fu_370_p20");
    sc_trace(mVcdFile, grp_fu_379_p00, "grp_fu_379_p00");
    sc_trace(mVcdFile, grp_fu_379_p20, "grp_fu_379_p20");
    sc_trace(mVcdFile, ap_sig_250, "ap_sig_250");
#endif

    }
}

dut_matrix_multiply_alt26::~dut_matrix_multiply_alt26() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete sum_mult_U;
    delete dut_fadd_32ns_32ns_32_5_full_dsp_U5;
    delete dut_fmul_32ns_32ns_32_4_max_dsp_U6;
    delete dut_mac_muladd_10ns_11ns_10ns_20_1_U7;
    delete dut_mac_muladd_7ns_11ns_10ns_17_1_U8;
    delete dut_mac_muladd_10ns_8ns_7ns_17_1_U9;
}

void dut_matrix_multiply_alt26::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void dut_matrix_multiply_alt26::thread_ap_clk_no_reset_() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten1_reg_388.read(), ap_const_lv1_0))) {
        Col_assign_2_reg_130 = tmp_i_i_mid2_v_reg_405.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        Col_assign_2_reg_130 = ap_const_lv7_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten1_fu_184_p2.read(), ap_const_lv1_0))) {
        Col_assign_reg_163 = c_fu_310_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        Col_assign_reg_163 = ap_const_lv10_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten1_reg_388.read(), ap_const_lv1_0))) {
        Row_assign_reg_152 = tmp_34_mid2_reg_418.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        Row_assign_reg_152 = ap_const_lv10_0;
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_st1_fsm_0;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
             !esl_seteq<1,1,1>(exitcond_flatten1_fu_184_p2.read(), ap_const_lv1_0))) {
            ap_reg_ppiten_pp0_it0 = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                    !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
            ap_reg_ppiten_pp0_it0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it1 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
             esl_seteq<1,1,1>(exitcond_flatten1_fu_184_p2.read(), ap_const_lv1_0))) {
            ap_reg_ppiten_pp0_it1 = ap_const_logic_1;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                     !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) || 
                    (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
                     !esl_seteq<1,1,1>(exitcond_flatten1_fu_184_p2.read(), ap_const_lv1_0)))) {
            ap_reg_ppiten_pp0_it1 = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it10 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_true, ap_true)) {
            ap_reg_ppiten_pp0_it10 = ap_reg_ppiten_pp0_it9.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it11 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_true, ap_true)) {
            ap_reg_ppiten_pp0_it11 = ap_reg_ppiten_pp0_it10.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it12 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_true, ap_true)) {
            ap_reg_ppiten_pp0_it12 = ap_reg_ppiten_pp0_it11.read();
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                    !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
            ap_reg_ppiten_pp0_it12 = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it2 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_true, ap_true)) {
            ap_reg_ppiten_pp0_it2 = ap_reg_ppiten_pp0_it1.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it3 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_true, ap_true)) {
            ap_reg_ppiten_pp0_it3 = ap_reg_ppiten_pp0_it2.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it4 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_true, ap_true)) {
            ap_reg_ppiten_pp0_it4 = ap_reg_ppiten_pp0_it3.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it5 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_true, ap_true)) {
            ap_reg_ppiten_pp0_it5 = ap_reg_ppiten_pp0_it4.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it6 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_true, ap_true)) {
            ap_reg_ppiten_pp0_it6 = ap_reg_ppiten_pp0_it5.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it7 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_true, ap_true)) {
            ap_reg_ppiten_pp0_it7 = ap_reg_ppiten_pp0_it6.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it8 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_true, ap_true)) {
            ap_reg_ppiten_pp0_it8 = ap_reg_ppiten_pp0_it7.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it9 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_true, ap_true)) {
            ap_reg_ppiten_pp0_it9 = ap_reg_ppiten_pp0_it8.read();
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten1_fu_184_p2.read(), ap_const_lv1_0))) {
        indvar_flatten1_reg_119 = indvar_flatten_next1_fu_190_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        indvar_flatten1_reg_119 = ap_const_lv26_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten1_fu_184_p2.read(), ap_const_lv1_0))) {
        indvar_flatten_reg_141 = indvar_flatten_next_fu_322_p3.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        indvar_flatten_reg_141 = ap_const_lv20_0;
    }
    if (esl_seteq<1,1,1>(ap_reg_ppstg_exitcond_flatten1_reg_388_pp0_iter1.read(), ap_const_lv1_0)) {
        C_addr_reg_450 =  (sc_lv<20>) (tmp_58_cast_fu_356_p1.read());
        sum_mult_addr_reg_455 =  (sc_lv<20>) (tmp_58_cast_fu_356_p1.read());
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && esl_seteq<1,1,1>(exitcond_flatten1_fu_184_p2.read(), ap_const_lv1_0))) {
        Col_assign_mid2_reg_412 = Col_assign_mid2_fu_294_p3.read();
        tmp_mid2_21_reg_401 = tmp_mid2_21_fu_248_p3.read();
        tmp_mid2_reg_397 = tmp_mid2_fu_228_p3.read();
    }
    if (esl_seteq<1,1,1>(ap_true, ap_true)) {
        ap_reg_ppstg_C_addr_reg_450_pp0_iter10 = ap_reg_ppstg_C_addr_reg_450_pp0_iter9.read();
        ap_reg_ppstg_C_addr_reg_450_pp0_iter3 = C_addr_reg_450.read();
        ap_reg_ppstg_C_addr_reg_450_pp0_iter4 = ap_reg_ppstg_C_addr_reg_450_pp0_iter3.read();
        ap_reg_ppstg_C_addr_reg_450_pp0_iter5 = ap_reg_ppstg_C_addr_reg_450_pp0_iter4.read();
        ap_reg_ppstg_C_addr_reg_450_pp0_iter6 = ap_reg_ppstg_C_addr_reg_450_pp0_iter5.read();
        ap_reg_ppstg_C_addr_reg_450_pp0_iter7 = ap_reg_ppstg_C_addr_reg_450_pp0_iter6.read();
        ap_reg_ppstg_C_addr_reg_450_pp0_iter8 = ap_reg_ppstg_C_addr_reg_450_pp0_iter7.read();
        ap_reg_ppstg_C_addr_reg_450_pp0_iter9 = ap_reg_ppstg_C_addr_reg_450_pp0_iter8.read();
        ap_reg_ppstg_exitcond_flatten1_reg_388_pp0_iter2 = ap_reg_ppstg_exitcond_flatten1_reg_388_pp0_iter1.read();
        ap_reg_ppstg_exitcond_flatten1_reg_388_pp0_iter3 = ap_reg_ppstg_exitcond_flatten1_reg_388_pp0_iter2.read();
        ap_reg_ppstg_exitcond_flatten1_reg_388_pp0_iter4 = ap_reg_ppstg_exitcond_flatten1_reg_388_pp0_iter3.read();
        ap_reg_ppstg_mult_reg_466_pp0_iter10 = ap_reg_ppstg_mult_reg_466_pp0_iter9.read();
        ap_reg_ppstg_mult_reg_466_pp0_iter6 = mult_reg_466.read();
        ap_reg_ppstg_mult_reg_466_pp0_iter7 = ap_reg_ppstg_mult_reg_466_pp0_iter6.read();
        ap_reg_ppstg_mult_reg_466_pp0_iter8 = ap_reg_ppstg_mult_reg_466_pp0_iter7.read();
        ap_reg_ppstg_mult_reg_466_pp0_iter9 = ap_reg_ppstg_mult_reg_466_pp0_iter8.read();
        ap_reg_ppstg_sum_mult_addr_reg_455_pp0_iter10 = ap_reg_ppstg_sum_mult_addr_reg_455_pp0_iter9.read();
        ap_reg_ppstg_sum_mult_addr_reg_455_pp0_iter3 = sum_mult_addr_reg_455.read();
        ap_reg_ppstg_sum_mult_addr_reg_455_pp0_iter4 = ap_reg_ppstg_sum_mult_addr_reg_455_pp0_iter3.read();
        ap_reg_ppstg_sum_mult_addr_reg_455_pp0_iter5 = ap_reg_ppstg_sum_mult_addr_reg_455_pp0_iter4.read();
        ap_reg_ppstg_sum_mult_addr_reg_455_pp0_iter6 = ap_reg_ppstg_sum_mult_addr_reg_455_pp0_iter5.read();
        ap_reg_ppstg_sum_mult_addr_reg_455_pp0_iter7 = ap_reg_ppstg_sum_mult_addr_reg_455_pp0_iter6.read();
        ap_reg_ppstg_sum_mult_addr_reg_455_pp0_iter8 = ap_reg_ppstg_sum_mult_addr_reg_455_pp0_iter7.read();
        ap_reg_ppstg_sum_mult_addr_reg_455_pp0_iter9 = ap_reg_ppstg_sum_mult_addr_reg_455_pp0_iter8.read();
        ap_reg_ppstg_tmp_mid2_21_reg_401_pp0_iter10 = ap_reg_ppstg_tmp_mid2_21_reg_401_pp0_iter9.read();
        ap_reg_ppstg_tmp_mid2_21_reg_401_pp0_iter2 = ap_reg_ppstg_tmp_mid2_21_reg_401_pp0_iter1.read();
        ap_reg_ppstg_tmp_mid2_21_reg_401_pp0_iter3 = ap_reg_ppstg_tmp_mid2_21_reg_401_pp0_iter2.read();
        ap_reg_ppstg_tmp_mid2_21_reg_401_pp0_iter4 = ap_reg_ppstg_tmp_mid2_21_reg_401_pp0_iter3.read();
        ap_reg_ppstg_tmp_mid2_21_reg_401_pp0_iter5 = ap_reg_ppstg_tmp_mid2_21_reg_401_pp0_iter4.read();
        ap_reg_ppstg_tmp_mid2_21_reg_401_pp0_iter6 = ap_reg_ppstg_tmp_mid2_21_reg_401_pp0_iter5.read();
        ap_reg_ppstg_tmp_mid2_21_reg_401_pp0_iter7 = ap_reg_ppstg_tmp_mid2_21_reg_401_pp0_iter6.read();
        ap_reg_ppstg_tmp_mid2_21_reg_401_pp0_iter8 = ap_reg_ppstg_tmp_mid2_21_reg_401_pp0_iter7.read();
        ap_reg_ppstg_tmp_mid2_21_reg_401_pp0_iter9 = ap_reg_ppstg_tmp_mid2_21_reg_401_pp0_iter8.read();
        ap_reg_ppstg_tmp_mid2_reg_397_pp0_iter10 = ap_reg_ppstg_tmp_mid2_reg_397_pp0_iter9.read();
        ap_reg_ppstg_tmp_mid2_reg_397_pp0_iter2 = ap_reg_ppstg_tmp_mid2_reg_397_pp0_iter1.read();
        ap_reg_ppstg_tmp_mid2_reg_397_pp0_iter3 = ap_reg_ppstg_tmp_mid2_reg_397_pp0_iter2.read();
        ap_reg_ppstg_tmp_mid2_reg_397_pp0_iter4 = ap_reg_ppstg_tmp_mid2_reg_397_pp0_iter3.read();
        ap_reg_ppstg_tmp_mid2_reg_397_pp0_iter5 = ap_reg_ppstg_tmp_mid2_reg_397_pp0_iter4.read();
        ap_reg_ppstg_tmp_mid2_reg_397_pp0_iter6 = ap_reg_ppstg_tmp_mid2_reg_397_pp0_iter5.read();
        ap_reg_ppstg_tmp_mid2_reg_397_pp0_iter7 = ap_reg_ppstg_tmp_mid2_reg_397_pp0_iter6.read();
        ap_reg_ppstg_tmp_mid2_reg_397_pp0_iter8 = ap_reg_ppstg_tmp_mid2_reg_397_pp0_iter7.read();
        ap_reg_ppstg_tmp_mid2_reg_397_pp0_iter9 = ap_reg_ppstg_tmp_mid2_reg_397_pp0_iter8.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read())) {
        ap_reg_ppstg_Col_assign_mid2_reg_412_pp0_iter1 = Col_assign_mid2_reg_412.read();
        ap_reg_ppstg_exitcond_flatten1_reg_388_pp0_iter1 = exitcond_flatten1_reg_388.read();
        ap_reg_ppstg_tmp_34_mid2_reg_418_pp0_iter1 = tmp_34_mid2_reg_418.read();
        ap_reg_ppstg_tmp_mid2_21_reg_401_pp0_iter1 = tmp_mid2_21_reg_401.read();
        ap_reg_ppstg_tmp_mid2_reg_397_pp0_iter1 = tmp_mid2_reg_397.read();
        exitcond_flatten1_reg_388 = exitcond_flatten1_fu_184_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_reg_ppstg_exitcond_flatten1_reg_388_pp0_iter4.read(), ap_const_lv1_0)) {
        mult_reg_466 = grp_fu_178_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it5.read()) && esl_seteq<1,1,1>(ap_reg_ppstg_exitcond_flatten1_reg_388_pp0_iter4.read(), ap_const_lv1_0))) {
        sum_mult_load_reg_472 = sum_mult_q0.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && esl_seteq<1,1,1>(exitcond_flatten1_fu_184_p2.read(), ap_const_lv1_0))) {
        tmp_34_mid2_reg_418 = tmp_34_mid2_fu_302_p3.read();
        tmp_i_i_mid2_v_reg_405 = tmp_i_i_mid2_v_fu_256_p3.read();
    }
    if (esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_tmp_mid2_reg_397_pp0_iter9.read())) {
        tmp_36_reg_477 = grp_fu_174_p2.read();
    }
}

void dut_matrix_multiply_alt26::thread_A_address0() {
    A_address0 =  (sc_lv<17>) (tmp_55_cast_fu_339_p1.read());
}

void dut_matrix_multiply_alt26::thread_A_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()))) {
        A_ce0 = ap_const_logic_1;
    } else {
        A_ce0 = ap_const_logic_0;
    }
}

void dut_matrix_multiply_alt26::thread_B_address0() {
    B_address0 =  (sc_lv<17>) (tmp_57_cast_fu_346_p1.read());
}

void dut_matrix_multiply_alt26::thread_B_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()))) {
        B_ce0 = ap_const_logic_1;
    } else {
        B_ce0 = ap_const_logic_0;
    }
}

void dut_matrix_multiply_alt26::thread_C_address0() {
    C_address0 = ap_reg_ppstg_C_addr_reg_450_pp0_iter10.read();
}

void dut_matrix_multiply_alt26::thread_C_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it11.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it12.read()))) {
        C_ce0 = ap_const_logic_1;
    } else {
        C_ce0 = ap_const_logic_0;
    }
}

void dut_matrix_multiply_alt26::thread_C_d0() {
    C_d0 = tmp_36_reg_477.read();
}

void dut_matrix_multiply_alt26::thread_C_we0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it11.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_tmp_mid2_reg_397_pp0_iter10.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_tmp_mid2_21_reg_401_pp0_iter10.read())))) {
        C_we0 = ap_const_logic_1;
    } else {
        C_we0 = ap_const_logic_0;
    }
}

void dut_matrix_multiply_alt26::thread_Col_assign_2_phi_fu_134_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten1_reg_388.read(), ap_const_lv1_0))) {
        Col_assign_2_phi_fu_134_p4 = tmp_i_i_mid2_v_reg_405.read();
    } else {
        Col_assign_2_phi_fu_134_p4 = Col_assign_2_reg_130.read();
    }
}

void dut_matrix_multiply_alt26::thread_Col_assign_mid2_fu_294_p3() {
    Col_assign_mid2_fu_294_p3 = (!tmp_47_fu_288_p2.read()[0].is_01())? sc_lv<10>(): ((tmp_47_fu_288_p2.read()[0].to_bool())? ap_const_lv10_0: Col_assign_reg_163.read());
}

void dut_matrix_multiply_alt26::thread_Row_assign_mid_fu_208_p3() {
    Row_assign_mid_fu_208_p3 = (!exitcond_flatten_fu_202_p2.read()[0].is_01())? sc_lv<10>(): ((exitcond_flatten_fu_202_p2.read()[0].to_bool())? ap_const_lv10_0: Row_assign_phi_fu_156_p4.read());
}

void dut_matrix_multiply_alt26::thread_Row_assign_phi_fu_156_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten1_reg_388.read(), ap_const_lv1_0))) {
        Row_assign_phi_fu_156_p4 = tmp_34_mid2_reg_418.read();
    } else {
        Row_assign_phi_fu_156_p4 = Row_assign_reg_152.read();
    }
}

void dut_matrix_multiply_alt26::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st15_fsm_2.read()))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void dut_matrix_multiply_alt26::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void dut_matrix_multiply_alt26::thread_ap_ready() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st15_fsm_2.read())) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void dut_matrix_multiply_alt26::thread_ap_sig_20() {
    ap_sig_20 = esl_seteq<1,1,1>(ap_CS_fsm.read().range(0, 0), ap_const_lv1_1);
}

void dut_matrix_multiply_alt26::thread_ap_sig_250() {
    ap_sig_250 = (esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_tmp_mid2_reg_397_pp0_iter10.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_tmp_mid2_21_reg_401_pp0_iter10.read()));
}

void dut_matrix_multiply_alt26::thread_ap_sig_415() {
    ap_sig_415 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(2, 2));
}

void dut_matrix_multiply_alt26::thread_ap_sig_61() {
    ap_sig_61 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(1, 1));
}

void dut_matrix_multiply_alt26::thread_ap_sig_cseq_ST_pp0_stg0_fsm_1() {
    if (ap_sig_61.read()) {
        ap_sig_cseq_ST_pp0_stg0_fsm_1 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_pp0_stg0_fsm_1 = ap_const_logic_0;
    }
}

void dut_matrix_multiply_alt26::thread_ap_sig_cseq_ST_st15_fsm_2() {
    if (ap_sig_415.read()) {
        ap_sig_cseq_ST_st15_fsm_2 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st15_fsm_2 = ap_const_logic_0;
    }
}

void dut_matrix_multiply_alt26::thread_ap_sig_cseq_ST_st1_fsm_0() {
    if (ap_sig_20.read()) {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    }
}

void dut_matrix_multiply_alt26::thread_c_fu_310_p2() {
    c_fu_310_p2 = (!Col_assign_mid2_fu_294_p3.read().is_01() || !ap_const_lv10_1.is_01())? sc_lv<10>(): (sc_biguint<10>(Col_assign_mid2_fu_294_p3.read()) + sc_biguint<10>(ap_const_lv10_1));
}

void dut_matrix_multiply_alt26::thread_exitcond_flatten1_fu_184_p2() {
    exitcond_flatten1_fu_184_p2 = (!indvar_flatten1_reg_119.read().is_01() || !ap_const_lv26_3A9E400.is_01())? sc_lv<1>(): sc_lv<1>(indvar_flatten1_reg_119.read() == ap_const_lv26_3A9E400);
}

void dut_matrix_multiply_alt26::thread_exitcond_flatten_fu_202_p2() {
    exitcond_flatten_fu_202_p2 = (!indvar_flatten_reg_141.read().is_01() || !ap_const_lv20_96100.is_01())? sc_lv<1>(): sc_lv<1>(indvar_flatten_reg_141.read() == ap_const_lv20_96100);
}

void dut_matrix_multiply_alt26::thread_exitcond_fu_270_p2() {
    exitcond_fu_270_p2 = (!Col_assign_reg_163.read().is_01() || !ap_const_lv10_310.is_01())? sc_lv<1>(): sc_lv<1>(Col_assign_reg_163.read() == ap_const_lv10_310);
}

void dut_matrix_multiply_alt26::thread_exitcond_mid_fu_276_p2() {
    exitcond_mid_fu_276_p2 = (exitcond_fu_270_p2.read() & not_exitcond_flatten_fu_264_p2.read());
}

void dut_matrix_multiply_alt26::thread_grp_fu_361_p0() {
    grp_fu_361_p0 =  (sc_lv<10>) (grp_fu_361_p00.read());
}

void dut_matrix_multiply_alt26::thread_grp_fu_361_p00() {
    grp_fu_361_p00 = esl_zext<20,10>(ap_reg_ppstg_tmp_34_mid2_reg_418_pp0_iter1.read());
}

void dut_matrix_multiply_alt26::thread_grp_fu_361_p1() {
    grp_fu_361_p1 =  (sc_lv<11>) (ap_const_lv20_310);
}

void dut_matrix_multiply_alt26::thread_grp_fu_361_p2() {
    grp_fu_361_p2 =  (sc_lv<10>) (grp_fu_361_p20.read());
}

void dut_matrix_multiply_alt26::thread_grp_fu_361_p20() {
    grp_fu_361_p20 = esl_zext<20,10>(ap_reg_ppstg_Col_assign_mid2_reg_412_pp0_iter1.read());
}

void dut_matrix_multiply_alt26::thread_grp_fu_370_p0() {
    grp_fu_370_p0 =  (sc_lv<7>) (grp_fu_370_p00.read());
}

void dut_matrix_multiply_alt26::thread_grp_fu_370_p00() {
    grp_fu_370_p00 = esl_zext<17,7>(tmp_i_i_mid2_v_reg_405.read());
}

void dut_matrix_multiply_alt26::thread_grp_fu_370_p1() {
    grp_fu_370_p1 =  (sc_lv<11>) (ap_const_lv17_310);
}

void dut_matrix_multiply_alt26::thread_grp_fu_370_p2() {
    grp_fu_370_p2 =  (sc_lv<10>) (grp_fu_370_p20.read());
}

void dut_matrix_multiply_alt26::thread_grp_fu_370_p20() {
    grp_fu_370_p20 = esl_zext<17,10>(Col_assign_mid2_reg_412.read());
}

void dut_matrix_multiply_alt26::thread_grp_fu_379_p0() {
    grp_fu_379_p0 =  (sc_lv<10>) (grp_fu_379_p00.read());
}

void dut_matrix_multiply_alt26::thread_grp_fu_379_p00() {
    grp_fu_379_p00 = esl_zext<17,10>(tmp_34_mid2_reg_418.read());
}

void dut_matrix_multiply_alt26::thread_grp_fu_379_p1() {
    grp_fu_379_p1 =  (sc_lv<8>) (ap_const_lv17_64);
}

void dut_matrix_multiply_alt26::thread_grp_fu_379_p2() {
    grp_fu_379_p2 =  (sc_lv<7>) (grp_fu_379_p20.read());
}

void dut_matrix_multiply_alt26::thread_grp_fu_379_p20() {
    grp_fu_379_p20 = esl_zext<17,7>(tmp_i_i_mid2_v_reg_405.read());
}

void dut_matrix_multiply_alt26::thread_indvar_flatten_next1_fu_190_p2() {
    indvar_flatten_next1_fu_190_p2 = (!indvar_flatten1_reg_119.read().is_01() || !ap_const_lv26_1.is_01())? sc_lv<26>(): (sc_biguint<26>(indvar_flatten1_reg_119.read()) + sc_biguint<26>(ap_const_lv26_1));
}

void dut_matrix_multiply_alt26::thread_indvar_flatten_next_fu_322_p3() {
    indvar_flatten_next_fu_322_p3 = (!exitcond_flatten_fu_202_p2.read()[0].is_01())? sc_lv<20>(): ((exitcond_flatten_fu_202_p2.read()[0].to_bool())? ap_const_lv20_1: indvar_flatten_op_fu_316_p2.read());
}

void dut_matrix_multiply_alt26::thread_indvar_flatten_op_fu_316_p2() {
    indvar_flatten_op_fu_316_p2 = (!indvar_flatten_reg_141.read().is_01() || !ap_const_lv20_1.is_01())? sc_lv<20>(): (sc_biguint<20>(indvar_flatten_reg_141.read()) + sc_biguint<20>(ap_const_lv20_1));
}

void dut_matrix_multiply_alt26::thread_k_fu_196_p2() {
    k_fu_196_p2 = (!Col_assign_2_phi_fu_134_p4.read().is_01() || !ap_const_lv7_1.is_01())? sc_lv<7>(): (sc_biguint<7>(Col_assign_2_phi_fu_134_p4.read()) + sc_biguint<7>(ap_const_lv7_1));
}

void dut_matrix_multiply_alt26::thread_not_exitcond_flatten_fu_264_p2() {
    not_exitcond_flatten_fu_264_p2 = (exitcond_flatten_fu_202_p2.read() ^ ap_const_lv1_1);
}

void dut_matrix_multiply_alt26::thread_r_fu_282_p2() {
    r_fu_282_p2 = (!Row_assign_mid_fu_208_p3.read().is_01() || !ap_const_lv10_1.is_01())? sc_lv<10>(): (sc_biguint<10>(Row_assign_mid_fu_208_p3.read()) + sc_biguint<10>(ap_const_lv10_1));
}

void dut_matrix_multiply_alt26::thread_sum_mult_address0() {
    sum_mult_address0 =  (sc_lv<20>) (tmp_58_cast_fu_356_p1.read());
}

void dut_matrix_multiply_alt26::thread_sum_mult_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it2.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it3.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it5.read()))) {
        sum_mult_ce0 = ap_const_logic_1;
    } else {
        sum_mult_ce0 = ap_const_logic_0;
    }
}

void dut_matrix_multiply_alt26::thread_sum_mult_ce1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it12.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it11.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_tmp_mid2_reg_397_pp0_iter10.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_tmp_mid2_21_reg_401_pp0_iter10.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it11.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_tmp_mid2_reg_397_pp0_iter10.read())))) {
        sum_mult_ce1 = ap_const_logic_1;
    } else {
        sum_mult_ce1 = ap_const_logic_0;
    }
}

void dut_matrix_multiply_alt26::thread_sum_mult_d1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it11.read())) {
        if (!esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_tmp_mid2_reg_397_pp0_iter10.read())) {
            sum_mult_d1 = ap_reg_ppstg_mult_reg_466_pp0_iter10.read();
        } else if (ap_sig_250.read()) {
            sum_mult_d1 = tmp_36_reg_477.read();
        } else {
            sum_mult_d1 = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        }
    } else {
        sum_mult_d1 = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    }
}

void dut_matrix_multiply_alt26::thread_sum_mult_we1() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it11.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_tmp_mid2_reg_397_pp0_iter10.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_tmp_mid2_21_reg_401_pp0_iter10.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it11.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_tmp_mid2_reg_397_pp0_iter10.read())))) {
        sum_mult_we1 = ap_const_logic_1;
    } else {
        sum_mult_we1 = ap_const_logic_0;
    }
}

void dut_matrix_multiply_alt26::thread_tmp2_fu_222_p2() {
    tmp2_fu_222_p2 = (!Col_assign_2_phi_fu_134_p4.read().is_01() || !ap_const_lv7_0.is_01())? sc_lv<1>(): sc_lv<1>(Col_assign_2_phi_fu_134_p4.read() == ap_const_lv7_0);
}

void dut_matrix_multiply_alt26::thread_tmp_1_fu_242_p2() {
    tmp_1_fu_242_p2 = (!Col_assign_2_phi_fu_134_p4.read().is_01() || !ap_const_lv7_63.is_01())? sc_lv<1>(): sc_lv<1>(Col_assign_2_phi_fu_134_p4.read() == ap_const_lv7_63);
}

void dut_matrix_multiply_alt26::thread_tmp_34_mid2_fu_302_p3() {
    tmp_34_mid2_fu_302_p3 = (!exitcond_mid_fu_276_p2.read()[0].is_01())? sc_lv<10>(): ((exitcond_mid_fu_276_p2.read()[0].to_bool())? r_fu_282_p2.read(): Row_assign_mid_fu_208_p3.read());
}

void dut_matrix_multiply_alt26::thread_tmp_47_fu_288_p2() {
    tmp_47_fu_288_p2 = (exitcond_mid_fu_276_p2.read() | exitcond_flatten_fu_202_p2.read());
}

void dut_matrix_multiply_alt26::thread_tmp_55_cast_fu_339_p1() {
    tmp_55_cast_fu_339_p1 = esl_zext<64,17>(grp_fu_379_p3.read());
}

void dut_matrix_multiply_alt26::thread_tmp_57_cast_fu_346_p1() {
    tmp_57_cast_fu_346_p1 = esl_zext<64,17>(grp_fu_370_p3.read());
}

void dut_matrix_multiply_alt26::thread_tmp_58_cast_fu_356_p1() {
    tmp_58_cast_fu_356_p1 = esl_zext<64,20>(grp_fu_361_p3.read());
}

void dut_matrix_multiply_alt26::thread_tmp_i_i_mid2_v_fu_256_p3() {
    tmp_i_i_mid2_v_fu_256_p3 = (!exitcond_flatten_fu_202_p2.read()[0].is_01())? sc_lv<7>(): ((exitcond_flatten_fu_202_p2.read()[0].to_bool())? k_fu_196_p2.read(): Col_assign_2_phi_fu_134_p4.read());
}

void dut_matrix_multiply_alt26::thread_tmp_mid1_20_fu_236_p2() {
    tmp_mid1_20_fu_236_p2 = (!k_fu_196_p2.read().is_01() || !ap_const_lv7_63.is_01())? sc_lv<1>(): sc_lv<1>(k_fu_196_p2.read() == ap_const_lv7_63);
}

void dut_matrix_multiply_alt26::thread_tmp_mid1_fu_216_p2() {
    tmp_mid1_fu_216_p2 = (!k_fu_196_p2.read().is_01() || !ap_const_lv7_0.is_01())? sc_lv<1>(): sc_lv<1>(k_fu_196_p2.read() == ap_const_lv7_0);
}

void dut_matrix_multiply_alt26::thread_tmp_mid2_21_fu_248_p3() {
    tmp_mid2_21_fu_248_p3 = (!exitcond_flatten_fu_202_p2.read()[0].is_01())? sc_lv<1>(): ((exitcond_flatten_fu_202_p2.read()[0].to_bool())? tmp_mid1_20_fu_236_p2.read(): tmp_1_fu_242_p2.read());
}

void dut_matrix_multiply_alt26::thread_tmp_mid2_fu_228_p3() {
    tmp_mid2_fu_228_p3 = (!exitcond_flatten_fu_202_p2.read()[0].is_01())? sc_lv<1>(): ((exitcond_flatten_fu_202_p2.read()[0].to_bool())? tmp_mid1_fu_216_p2.read(): tmp2_fu_222_p2.read());
}

void dut_matrix_multiply_alt26::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if (!esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) {
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_1;
            } else {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            }
            break;
        case 2 : 
            if ((!(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it12.read()) && !esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it11.read())) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && !esl_seteq<1,1,1>(exitcond_flatten1_fu_184_p2.read(), ap_const_lv1_0) && !esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read())))) {
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_1;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && !esl_seteq<1,1,1>(exitcond_flatten1_fu_184_p2.read(), ap_const_lv1_0) && !esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()))) {
                ap_NS_fsm = ap_ST_st15_fsm_2;
            } else {
                ap_NS_fsm = ap_ST_st15_fsm_2;
            }
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_st1_fsm_0;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<3>) ("XXX");
            break;
    }
}

}

