// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.2
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "dut_matrix_multiply_alt2.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic dut_matrix_multiply_alt2::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic dut_matrix_multiply_alt2::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<15> dut_matrix_multiply_alt2::ap_ST_st1_fsm_0 = "1";
const sc_lv<15> dut_matrix_multiply_alt2::ap_ST_st2_fsm_1 = "10";
const sc_lv<15> dut_matrix_multiply_alt2::ap_ST_st3_fsm_2 = "100";
const sc_lv<15> dut_matrix_multiply_alt2::ap_ST_st4_fsm_3 = "1000";
const sc_lv<15> dut_matrix_multiply_alt2::ap_ST_st5_fsm_4 = "10000";
const sc_lv<15> dut_matrix_multiply_alt2::ap_ST_st6_fsm_5 = "100000";
const sc_lv<15> dut_matrix_multiply_alt2::ap_ST_st7_fsm_6 = "1000000";
const sc_lv<15> dut_matrix_multiply_alt2::ap_ST_st8_fsm_7 = "10000000";
const sc_lv<15> dut_matrix_multiply_alt2::ap_ST_st9_fsm_8 = "100000000";
const sc_lv<15> dut_matrix_multiply_alt2::ap_ST_st10_fsm_9 = "1000000000";
const sc_lv<15> dut_matrix_multiply_alt2::ap_ST_st11_fsm_10 = "10000000000";
const sc_lv<15> dut_matrix_multiply_alt2::ap_ST_st12_fsm_11 = "100000000000";
const sc_lv<15> dut_matrix_multiply_alt2::ap_ST_st13_fsm_12 = "1000000000000";
const sc_lv<15> dut_matrix_multiply_alt2::ap_ST_st14_fsm_13 = "10000000000000";
const sc_lv<15> dut_matrix_multiply_alt2::ap_ST_st15_fsm_14 = "100000000000000";
const sc_lv<32> dut_matrix_multiply_alt2::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> dut_matrix_multiply_alt2::ap_const_lv1_1 = "1";
const sc_lv<32> dut_matrix_multiply_alt2::ap_const_lv32_1 = "1";
const sc_lv<1> dut_matrix_multiply_alt2::ap_const_lv1_0 = "0";
const sc_lv<32> dut_matrix_multiply_alt2::ap_const_lv32_2 = "10";
const sc_lv<32> dut_matrix_multiply_alt2::ap_const_lv32_3 = "11";
const sc_lv<32> dut_matrix_multiply_alt2::ap_const_lv32_4 = "100";
const sc_lv<32> dut_matrix_multiply_alt2::ap_const_lv32_5 = "101";
const sc_lv<32> dut_matrix_multiply_alt2::ap_const_lv32_7 = "111";
const sc_lv<32> dut_matrix_multiply_alt2::ap_const_lv32_C = "1100";
const sc_lv<32> dut_matrix_multiply_alt2::ap_const_lv32_D = "1101";
const sc_lv<20> dut_matrix_multiply_alt2::ap_const_lv20_0 = "00000000000000000000";
const sc_lv<10> dut_matrix_multiply_alt2::ap_const_lv10_0 = "0000000000";
const sc_lv<11> dut_matrix_multiply_alt2::ap_const_lv11_0 = "00000000000";
const sc_lv<4> dut_matrix_multiply_alt2::ap_const_lv4_0 = "0000";
const sc_lv<7> dut_matrix_multiply_alt2::ap_const_lv7_0 = "0000000";
const sc_lv<32> dut_matrix_multiply_alt2::ap_const_lv32_8 = "1000";
const sc_lv<20> dut_matrix_multiply_alt2::ap_const_lv20_BF680 = "10111111011010000000";
const sc_lv<20> dut_matrix_multiply_alt2::ap_const_lv20_1 = "1";
const sc_lv<11> dut_matrix_multiply_alt2::ap_const_lv11_3E8 = "1111101000";
const sc_lv<7> dut_matrix_multiply_alt2::ap_const_lv7_64 = "1100100";
const sc_lv<4> dut_matrix_multiply_alt2::ap_const_lv4_1 = "1";
const sc_lv<10> dut_matrix_multiply_alt2::ap_const_lv10_1 = "1";
const sc_lv<10> dut_matrix_multiply_alt2::ap_const_lv10_30F = "1100001111";
const sc_lv<7> dut_matrix_multiply_alt2::ap_const_lv7_1 = "1";
const sc_lv<11> dut_matrix_multiply_alt2::ap_const_lv11_1 = "1";
const sc_lv<11> dut_matrix_multiply_alt2::ap_const_lv11_64 = "1100100";
const sc_lv<17> dut_matrix_multiply_alt2::ap_const_lv17_64 = "1100100";
const sc_lv<14> dut_matrix_multiply_alt2::ap_const_lv14_310 = "1100010000";
const sc_lv<32> dut_matrix_multiply_alt2::ap_const_lv32_E = "1110";

dut_matrix_multiply_alt2::dut_matrix_multiply_alt2(sc_module_name name) : sc_module(name), mVcdFile(0) {
    sum_mult_U = new dut_matrix_multiply_alt2_sum_mult("sum_mult_U");
    sum_mult_U->clk(ap_clk);
    sum_mult_U->reset(ap_rst);
    sum_mult_U->address0(sum_mult_address0);
    sum_mult_U->ce0(sum_mult_ce0);
    sum_mult_U->we0(sum_mult_we0);
    sum_mult_U->d0(sum_mult_d0);
    sum_mult_U->q0(sum_mult_q0);
    dut_fadd_32ns_32ns_32_5_full_dsp_U47 = new dut_fadd_32ns_32ns_32_5_full_dsp<1,5,32,32,32>("dut_fadd_32ns_32ns_32_5_full_dsp_U47");
    dut_fadd_32ns_32ns_32_5_full_dsp_U47->clk(ap_clk);
    dut_fadd_32ns_32ns_32_5_full_dsp_U47->reset(ap_rst);
    dut_fadd_32ns_32ns_32_5_full_dsp_U47->din0(sum_mult_load_reg_469);
    dut_fadd_32ns_32ns_32_5_full_dsp_U47->din1(mult_reg_474);
    dut_fadd_32ns_32ns_32_5_full_dsp_U47->ce(ap_var_for_const0);
    dut_fadd_32ns_32ns_32_5_full_dsp_U47->dout(grp_fu_179_p2);
    dut_fmul_32ns_32ns_32_4_max_dsp_U48 = new dut_fmul_32ns_32ns_32_4_max_dsp<1,4,32,32,32>("dut_fmul_32ns_32ns_32_4_max_dsp_U48");
    dut_fmul_32ns_32ns_32_4_max_dsp_U48->clk(ap_clk);
    dut_fmul_32ns_32ns_32_4_max_dsp_U48->reset(ap_rst);
    dut_fmul_32ns_32ns_32_4_max_dsp_U48->din0(A_q0);
    dut_fmul_32ns_32ns_32_4_max_dsp_U48->din1(B_q0);
    dut_fmul_32ns_32ns_32_4_max_dsp_U48->ce(ap_var_for_const0);
    dut_fmul_32ns_32ns_32_4_max_dsp_U48->dout(grp_fu_183_p2);
    dut_mac_muladd_4ns_8ns_7ns_11_1_U49 = new dut_mac_muladd_4ns_8ns_7ns_11_1<1,1,4,8,7,11>("dut_mac_muladd_4ns_8ns_7ns_11_1_U49");
    dut_mac_muladd_4ns_8ns_7ns_11_1_U49->din0(grp_fu_363_p0);
    dut_mac_muladd_4ns_8ns_7ns_11_1_U49->din1(grp_fu_363_p1);
    dut_mac_muladd_4ns_8ns_7ns_11_1_U49->din2(grp_fu_363_p2);
    dut_mac_muladd_4ns_8ns_7ns_11_1_U49->dout(grp_fu_363_p3);
    dut_mac_muladd_10ns_8ns_7ns_17_1_U50 = new dut_mac_muladd_10ns_8ns_7ns_17_1<1,1,10,8,7,17>("dut_mac_muladd_10ns_8ns_7ns_17_1_U50");
    dut_mac_muladd_10ns_8ns_7ns_17_1_U50->din0(grp_fu_372_p0);
    dut_mac_muladd_10ns_8ns_7ns_17_1_U50->din1(grp_fu_372_p1);
    dut_mac_muladd_10ns_8ns_7ns_17_1_U50->din2(grp_fu_372_p2);
    dut_mac_muladd_10ns_8ns_7ns_17_1_U50->dout(grp_fu_372_p3);
    dut_mac_muladd_4ns_11ns_10ns_14_1_U51 = new dut_mac_muladd_4ns_11ns_10ns_14_1<1,1,4,11,10,14>("dut_mac_muladd_4ns_11ns_10ns_14_1_U51");
    dut_mac_muladd_4ns_11ns_10ns_14_1_U51->din0(grp_fu_381_p0);
    dut_mac_muladd_4ns_11ns_10ns_14_1_U51->din1(grp_fu_381_p1);
    dut_mac_muladd_4ns_11ns_10ns_14_1_U51->din2(grp_fu_381_p2);
    dut_mac_muladd_4ns_11ns_10ns_14_1_U51->dout(grp_fu_381_p3);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_A_address0);
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );
    sensitive << ( tmp_62_cast_fu_323_p1 );

    SC_METHOD(thread_A_ce0);
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );

    SC_METHOD(thread_B_address0);
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );
    sensitive << ( tmp_64_cast_fu_330_p1 );

    SC_METHOD(thread_B_ce0);
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );

    SC_METHOD(thread_C_address0);
    sensitive << ( C_addr_reg_454 );
    sensitive << ( ap_sig_cseq_ST_st14_fsm_13 );

    SC_METHOD(thread_C_ce0);
    sensitive << ( ap_sig_cseq_ST_st14_fsm_13 );

    SC_METHOD(thread_C_d0);
    sensitive << ( tmp_42_reg_479 );
    sensitive << ( ap_sig_cseq_ST_st14_fsm_13 );

    SC_METHOD(thread_C_we0);
    sensitive << ( exitcond_flatten2_reg_389 );
    sensitive << ( tmp_mid2_reg_420 );
    sensitive << ( tmp_mid2_24_reg_424 );
    sensitive << ( ap_sig_cseq_ST_st14_fsm_13 );

    SC_METHOD(thread_Col_assign_mid2_fu_246_p3);
    sensitive << ( Col_assign_reg_168 );
    sensitive << ( tmp_53_fu_240_p2 );

    SC_METHOD(thread_Row_assign_mid_fu_208_p3);
    sensitive << ( exitcond_flatten_fu_202_p2 );
    sensitive << ( Row_assign_reg_157 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( ap_sig_cseq_ST_st15_fsm_14 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_sig_cseq_ST_st15_fsm_14 );

    SC_METHOD(thread_ap_sig_108);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_122);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_131);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_140);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_153);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_208);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_32);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_365);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_63);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_83);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_98);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_cseq_ST_st13_fsm_12);
    sensitive << ( ap_sig_140 );

    SC_METHOD(thread_ap_sig_cseq_ST_st14_fsm_13);
    sensitive << ( ap_sig_153 );

    SC_METHOD(thread_ap_sig_cseq_ST_st15_fsm_14);
    sensitive << ( ap_sig_365 );

    SC_METHOD(thread_ap_sig_cseq_ST_st1_fsm_0);
    sensitive << ( ap_sig_32 );

    SC_METHOD(thread_ap_sig_cseq_ST_st2_fsm_1);
    sensitive << ( ap_sig_63 );

    SC_METHOD(thread_ap_sig_cseq_ST_st3_fsm_2);
    sensitive << ( ap_sig_83 );

    SC_METHOD(thread_ap_sig_cseq_ST_st4_fsm_3);
    sensitive << ( ap_sig_98 );

    SC_METHOD(thread_ap_sig_cseq_ST_st5_fsm_4);
    sensitive << ( ap_sig_108 );

    SC_METHOD(thread_ap_sig_cseq_ST_st6_fsm_5);
    sensitive << ( ap_sig_122 );

    SC_METHOD(thread_ap_sig_cseq_ST_st8_fsm_7);
    sensitive << ( ap_sig_131 );

    SC_METHOD(thread_ap_sig_cseq_ST_st9_fsm_8);
    sensitive << ( ap_sig_208 );

    SC_METHOD(thread_c_fu_345_p2);
    sensitive << ( Col_assign_mid2_reg_406 );

    SC_METHOD(thread_exitcond_flatten2_fu_190_p2);
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( indvar_flatten2_reg_122 );

    SC_METHOD(thread_exitcond_flatten_fu_202_p2);
    sensitive << ( exitcond_flatten2_fu_190_p2 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( indvar_flatten_reg_145 );

    SC_METHOD(thread_exitcond_fu_222_p2);
    sensitive << ( exitcond_flatten2_fu_190_p2 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( Col_assign_reg_168 );

    SC_METHOD(thread_exitcond_mid_fu_228_p2);
    sensitive << ( exitcond_fu_222_p2 );
    sensitive << ( not_exitcond_flatten_fu_216_p2 );

    SC_METHOD(thread_grp_fu_363_p0);
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );
    sensitive << ( grp_fu_363_p00 );

    SC_METHOD(thread_grp_fu_363_p00);
    sensitive << ( tmp_40_mid2_reg_413 );

    SC_METHOD(thread_grp_fu_363_p1);
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );

    SC_METHOD(thread_grp_fu_363_p2);
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );
    sensitive << ( grp_fu_363_p20 );

    SC_METHOD(thread_grp_fu_363_p20);
    sensitive << ( Col_assign_mid2_reg_406 );

    SC_METHOD(thread_grp_fu_372_p0);
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );
    sensitive << ( grp_fu_372_p00 );

    SC_METHOD(thread_grp_fu_372_p00);
    sensitive << ( tmp_i_i_mid2_v_reg_428 );

    SC_METHOD(thread_grp_fu_372_p1);
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );

    SC_METHOD(thread_grp_fu_372_p2);
    sensitive << ( ap_sig_cseq_ST_st4_fsm_3 );
    sensitive << ( grp_fu_372_p20 );

    SC_METHOD(thread_grp_fu_372_p20);
    sensitive << ( Col_assign_mid2_reg_406 );

    SC_METHOD(thread_grp_fu_381_p0);
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );
    sensitive << ( grp_fu_381_p00 );

    SC_METHOD(thread_grp_fu_381_p00);
    sensitive << ( tmp_40_mid2_reg_413 );

    SC_METHOD(thread_grp_fu_381_p1);
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );

    SC_METHOD(thread_grp_fu_381_p2);
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );
    sensitive << ( grp_fu_381_p20 );

    SC_METHOD(thread_grp_fu_381_p20);
    sensitive << ( tmp_i_i_mid2_v_fu_306_p3 );

    SC_METHOD(thread_indvar_flatten_next2_fu_196_p2);
    sensitive << ( indvar_flatten2_reg_122 );

    SC_METHOD(thread_indvar_flatten_next_fu_356_p3);
    sensitive << ( exitcond_flatten_reg_398 );
    sensitive << ( indvar_flatten_op_fu_350_p2 );

    SC_METHOD(thread_indvar_flatten_op_fu_350_p2);
    sensitive << ( indvar_flatten_reg_145 );

    SC_METHOD(thread_k_fu_262_p2);
    sensitive << ( Col_assign_3_reg_133 );

    SC_METHOD(thread_not_exitcond_flatten_fu_216_p2);
    sensitive << ( exitcond_flatten_fu_202_p2 );

    SC_METHOD(thread_r_fu_234_p2);
    sensitive << ( Row_assign_mid_fu_208_p3 );

    SC_METHOD(thread_sum_mult_address0);
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );
    sensitive << ( sum_mult_addr_reg_459 );
    sensitive << ( ap_sig_cseq_ST_st8_fsm_7 );
    sensitive << ( ap_sig_cseq_ST_st14_fsm_13 );
    sensitive << ( tmp_65_cast_fu_340_p1 );

    SC_METHOD(thread_sum_mult_ce0);
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );
    sensitive << ( ap_sig_cseq_ST_st8_fsm_7 );
    sensitive << ( ap_sig_cseq_ST_st14_fsm_13 );

    SC_METHOD(thread_sum_mult_d0);
    sensitive << ( grp_fu_183_p2 );
    sensitive << ( ap_sig_cseq_ST_st8_fsm_7 );
    sensitive << ( tmp_42_reg_479 );
    sensitive << ( ap_sig_cseq_ST_st14_fsm_13 );

    SC_METHOD(thread_sum_mult_we0);
    sensitive << ( exitcond_flatten2_reg_389 );
    sensitive << ( tmp_mid2_reg_420 );
    sensitive << ( tmp_mid2_24_reg_424 );
    sensitive << ( ap_sig_cseq_ST_st8_fsm_7 );
    sensitive << ( ap_sig_cseq_ST_st14_fsm_13 );

    SC_METHOD(thread_tmp2_fu_274_p2);
    sensitive << ( exitcond_flatten_reg_398 );
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );
    sensitive << ( Col_assign_3_reg_133 );

    SC_METHOD(thread_tmp_1_fu_293_p2);
    sensitive << ( exitcond_flatten_reg_398 );
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );
    sensitive << ( Col_assign_3_reg_133 );

    SC_METHOD(thread_tmp_40_mid2_fu_254_p3);
    sensitive << ( Row_assign_mid_fu_208_p3 );
    sensitive << ( exitcond_mid_fu_228_p2 );
    sensitive << ( r_fu_234_p2 );

    SC_METHOD(thread_tmp_53_fu_240_p2);
    sensitive << ( exitcond_flatten_fu_202_p2 );
    sensitive << ( exitcond_mid_fu_228_p2 );

    SC_METHOD(thread_tmp_62_cast_fu_323_p1);
    sensitive << ( tmp_55_reg_434 );

    SC_METHOD(thread_tmp_64_cast_fu_330_p1);
    sensitive << ( grp_fu_372_p3 );

    SC_METHOD(thread_tmp_65_cast_fu_340_p1);
    sensitive << ( grp_fu_363_p3 );

    SC_METHOD(thread_tmp_i_i_mid2_v_fu_306_p3);
    sensitive << ( exitcond_flatten_reg_398 );
    sensitive << ( Col_assign_3_reg_133 );
    sensitive << ( k_fu_262_p2 );

    SC_METHOD(thread_tmp_mid1_23_fu_287_p2);
    sensitive << ( exitcond_flatten_reg_398 );
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );
    sensitive << ( k_fu_262_p2 );

    SC_METHOD(thread_tmp_mid1_fu_268_p2);
    sensitive << ( exitcond_flatten_reg_398 );
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );
    sensitive << ( k_fu_262_p2 );

    SC_METHOD(thread_tmp_mid2_24_fu_299_p3);
    sensitive << ( exitcond_flatten_reg_398 );
    sensitive << ( tmp_mid1_23_fu_287_p2 );
    sensitive << ( tmp_1_fu_293_p2 );

    SC_METHOD(thread_tmp_mid2_fu_280_p3);
    sensitive << ( exitcond_flatten_reg_398 );
    sensitive << ( tmp_mid1_fu_268_p2 );
    sensitive << ( tmp2_fu_274_p2 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( exitcond_flatten2_fu_190_p2 );

    SC_THREAD(thread_ap_var_for_const0);

    ap_CS_fsm = "000000000000001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "dut_matrix_multiply_alt2_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, A_address0, "(port)A_address0");
    sc_trace(mVcdFile, A_ce0, "(port)A_ce0");
    sc_trace(mVcdFile, A_q0, "(port)A_q0");
    sc_trace(mVcdFile, B_address0, "(port)B_address0");
    sc_trace(mVcdFile, B_ce0, "(port)B_ce0");
    sc_trace(mVcdFile, B_q0, "(port)B_q0");
    sc_trace(mVcdFile, C_address0, "(port)C_address0");
    sc_trace(mVcdFile, C_ce0, "(port)C_ce0");
    sc_trace(mVcdFile, C_we0, "(port)C_we0");
    sc_trace(mVcdFile, C_d0, "(port)C_d0");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st1_fsm_0, "ap_sig_cseq_ST_st1_fsm_0");
    sc_trace(mVcdFile, ap_sig_32, "ap_sig_32");
    sc_trace(mVcdFile, exitcond_flatten2_fu_190_p2, "exitcond_flatten2_fu_190_p2");
    sc_trace(mVcdFile, exitcond_flatten2_reg_389, "exitcond_flatten2_reg_389");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st2_fsm_1, "ap_sig_cseq_ST_st2_fsm_1");
    sc_trace(mVcdFile, ap_sig_63, "ap_sig_63");
    sc_trace(mVcdFile, indvar_flatten_next2_fu_196_p2, "indvar_flatten_next2_fu_196_p2");
    sc_trace(mVcdFile, indvar_flatten_next2_reg_393, "indvar_flatten_next2_reg_393");
    sc_trace(mVcdFile, exitcond_flatten_fu_202_p2, "exitcond_flatten_fu_202_p2");
    sc_trace(mVcdFile, exitcond_flatten_reg_398, "exitcond_flatten_reg_398");
    sc_trace(mVcdFile, Col_assign_mid2_fu_246_p3, "Col_assign_mid2_fu_246_p3");
    sc_trace(mVcdFile, Col_assign_mid2_reg_406, "Col_assign_mid2_reg_406");
    sc_trace(mVcdFile, tmp_40_mid2_fu_254_p3, "tmp_40_mid2_fu_254_p3");
    sc_trace(mVcdFile, tmp_40_mid2_reg_413, "tmp_40_mid2_reg_413");
    sc_trace(mVcdFile, tmp_mid2_fu_280_p3, "tmp_mid2_fu_280_p3");
    sc_trace(mVcdFile, tmp_mid2_reg_420, "tmp_mid2_reg_420");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st3_fsm_2, "ap_sig_cseq_ST_st3_fsm_2");
    sc_trace(mVcdFile, ap_sig_83, "ap_sig_83");
    sc_trace(mVcdFile, tmp_mid2_24_fu_299_p3, "tmp_mid2_24_fu_299_p3");
    sc_trace(mVcdFile, tmp_mid2_24_reg_424, "tmp_mid2_24_reg_424");
    sc_trace(mVcdFile, tmp_i_i_mid2_v_fu_306_p3, "tmp_i_i_mid2_v_fu_306_p3");
    sc_trace(mVcdFile, tmp_i_i_mid2_v_reg_428, "tmp_i_i_mid2_v_reg_428");
    sc_trace(mVcdFile, grp_fu_381_p3, "grp_fu_381_p3");
    sc_trace(mVcdFile, tmp_55_reg_434, "tmp_55_reg_434");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st4_fsm_3, "ap_sig_cseq_ST_st4_fsm_3");
    sc_trace(mVcdFile, ap_sig_98, "ap_sig_98");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st5_fsm_4, "ap_sig_cseq_ST_st5_fsm_4");
    sc_trace(mVcdFile, ap_sig_108, "ap_sig_108");
    sc_trace(mVcdFile, C_addr_reg_454, "C_addr_reg_454");
    sc_trace(mVcdFile, sum_mult_addr_reg_459, "sum_mult_addr_reg_459");
    sc_trace(mVcdFile, sum_mult_q0, "sum_mult_q0");
    sc_trace(mVcdFile, sum_mult_load_reg_469, "sum_mult_load_reg_469");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st6_fsm_5, "ap_sig_cseq_ST_st6_fsm_5");
    sc_trace(mVcdFile, ap_sig_122, "ap_sig_122");
    sc_trace(mVcdFile, grp_fu_183_p2, "grp_fu_183_p2");
    sc_trace(mVcdFile, mult_reg_474, "mult_reg_474");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st8_fsm_7, "ap_sig_cseq_ST_st8_fsm_7");
    sc_trace(mVcdFile, ap_sig_131, "ap_sig_131");
    sc_trace(mVcdFile, grp_fu_179_p2, "grp_fu_179_p2");
    sc_trace(mVcdFile, tmp_42_reg_479, "tmp_42_reg_479");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st13_fsm_12, "ap_sig_cseq_ST_st13_fsm_12");
    sc_trace(mVcdFile, ap_sig_140, "ap_sig_140");
    sc_trace(mVcdFile, c_fu_345_p2, "c_fu_345_p2");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st14_fsm_13, "ap_sig_cseq_ST_st14_fsm_13");
    sc_trace(mVcdFile, ap_sig_153, "ap_sig_153");
    sc_trace(mVcdFile, indvar_flatten_next_fu_356_p3, "indvar_flatten_next_fu_356_p3");
    sc_trace(mVcdFile, sum_mult_address0, "sum_mult_address0");
    sc_trace(mVcdFile, sum_mult_ce0, "sum_mult_ce0");
    sc_trace(mVcdFile, sum_mult_we0, "sum_mult_we0");
    sc_trace(mVcdFile, sum_mult_d0, "sum_mult_d0");
    sc_trace(mVcdFile, indvar_flatten2_reg_122, "indvar_flatten2_reg_122");
    sc_trace(mVcdFile, Col_assign_3_reg_133, "Col_assign_3_reg_133");
    sc_trace(mVcdFile, indvar_flatten_reg_145, "indvar_flatten_reg_145");
    sc_trace(mVcdFile, Row_assign_reg_157, "Row_assign_reg_157");
    sc_trace(mVcdFile, Col_assign_reg_168, "Col_assign_reg_168");
    sc_trace(mVcdFile, tmp_62_cast_fu_323_p1, "tmp_62_cast_fu_323_p1");
    sc_trace(mVcdFile, tmp_64_cast_fu_330_p1, "tmp_64_cast_fu_330_p1");
    sc_trace(mVcdFile, tmp_65_cast_fu_340_p1, "tmp_65_cast_fu_340_p1");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st9_fsm_8, "ap_sig_cseq_ST_st9_fsm_8");
    sc_trace(mVcdFile, ap_sig_208, "ap_sig_208");
    sc_trace(mVcdFile, exitcond_fu_222_p2, "exitcond_fu_222_p2");
    sc_trace(mVcdFile, not_exitcond_flatten_fu_216_p2, "not_exitcond_flatten_fu_216_p2");
    sc_trace(mVcdFile, Row_assign_mid_fu_208_p3, "Row_assign_mid_fu_208_p3");
    sc_trace(mVcdFile, exitcond_mid_fu_228_p2, "exitcond_mid_fu_228_p2");
    sc_trace(mVcdFile, tmp_53_fu_240_p2, "tmp_53_fu_240_p2");
    sc_trace(mVcdFile, r_fu_234_p2, "r_fu_234_p2");
    sc_trace(mVcdFile, k_fu_262_p2, "k_fu_262_p2");
    sc_trace(mVcdFile, tmp_mid1_fu_268_p2, "tmp_mid1_fu_268_p2");
    sc_trace(mVcdFile, tmp2_fu_274_p2, "tmp2_fu_274_p2");
    sc_trace(mVcdFile, tmp_mid1_23_fu_287_p2, "tmp_mid1_23_fu_287_p2");
    sc_trace(mVcdFile, tmp_1_fu_293_p2, "tmp_1_fu_293_p2");
    sc_trace(mVcdFile, grp_fu_372_p3, "grp_fu_372_p3");
    sc_trace(mVcdFile, grp_fu_363_p3, "grp_fu_363_p3");
    sc_trace(mVcdFile, indvar_flatten_op_fu_350_p2, "indvar_flatten_op_fu_350_p2");
    sc_trace(mVcdFile, grp_fu_363_p0, "grp_fu_363_p0");
    sc_trace(mVcdFile, grp_fu_363_p1, "grp_fu_363_p1");
    sc_trace(mVcdFile, grp_fu_363_p2, "grp_fu_363_p2");
    sc_trace(mVcdFile, grp_fu_372_p0, "grp_fu_372_p0");
    sc_trace(mVcdFile, grp_fu_372_p1, "grp_fu_372_p1");
    sc_trace(mVcdFile, grp_fu_372_p2, "grp_fu_372_p2");
    sc_trace(mVcdFile, grp_fu_381_p0, "grp_fu_381_p0");
    sc_trace(mVcdFile, grp_fu_381_p1, "grp_fu_381_p1");
    sc_trace(mVcdFile, grp_fu_381_p2, "grp_fu_381_p2");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st15_fsm_14, "ap_sig_cseq_ST_st15_fsm_14");
    sc_trace(mVcdFile, ap_sig_365, "ap_sig_365");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, grp_fu_363_p00, "grp_fu_363_p00");
    sc_trace(mVcdFile, grp_fu_363_p20, "grp_fu_363_p20");
    sc_trace(mVcdFile, grp_fu_372_p00, "grp_fu_372_p00");
    sc_trace(mVcdFile, grp_fu_372_p20, "grp_fu_372_p20");
    sc_trace(mVcdFile, grp_fu_381_p00, "grp_fu_381_p00");
    sc_trace(mVcdFile, grp_fu_381_p20, "grp_fu_381_p20");
#endif

    }
}

dut_matrix_multiply_alt2::~dut_matrix_multiply_alt2() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete sum_mult_U;
    delete dut_fadd_32ns_32ns_32_5_full_dsp_U47;
    delete dut_fmul_32ns_32ns_32_4_max_dsp_U48;
    delete dut_mac_muladd_4ns_8ns_7ns_11_1_U49;
    delete dut_mac_muladd_10ns_8ns_7ns_17_1_U50;
    delete dut_mac_muladd_4ns_11ns_10ns_14_1_U51;
}

void dut_matrix_multiply_alt2::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void dut_matrix_multiply_alt2::thread_ap_clk_no_reset_() {
    if ((esl_seteq<1,1,1>(exitcond_flatten2_reg_389.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st14_fsm_13.read()))) {
        Col_assign_3_reg_133 = tmp_i_i_mid2_v_reg_428.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        Col_assign_3_reg_133 = ap_const_lv10_0;
    }
    if ((esl_seteq<1,1,1>(exitcond_flatten2_reg_389.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st14_fsm_13.read()))) {
        Col_assign_reg_168 = c_fu_345_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        Col_assign_reg_168 = ap_const_lv7_0;
    }
    if ((esl_seteq<1,1,1>(exitcond_flatten2_reg_389.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st14_fsm_13.read()))) {
        Row_assign_reg_157 = tmp_40_mid2_reg_413.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        Row_assign_reg_157 = ap_const_lv4_0;
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_st1_fsm_0;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ((esl_seteq<1,1,1>(exitcond_flatten2_reg_389.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st14_fsm_13.read()))) {
        indvar_flatten2_reg_122 = indvar_flatten_next2_reg_393.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        indvar_flatten2_reg_122 = ap_const_lv20_0;
    }
    if ((esl_seteq<1,1,1>(exitcond_flatten2_reg_389.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st14_fsm_13.read()))) {
        indvar_flatten_reg_145 = indvar_flatten_next_fu_356_p3.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        indvar_flatten_reg_145 = ap_const_lv11_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read())) {
        C_addr_reg_454 =  (sc_lv<10>) (tmp_65_cast_fu_340_p1.read());
        sum_mult_addr_reg_459 =  (sc_lv<10>) (tmp_65_cast_fu_340_p1.read());
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && esl_seteq<1,1,1>(exitcond_flatten2_fu_190_p2.read(), ap_const_lv1_0))) {
        Col_assign_mid2_reg_406 = Col_assign_mid2_fu_246_p3.read();
        exitcond_flatten_reg_398 = exitcond_flatten_fu_202_p2.read();
        tmp_40_mid2_reg_413 = tmp_40_mid2_fu_254_p3.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        exitcond_flatten2_reg_389 = exitcond_flatten2_fu_190_p2.read();
        indvar_flatten_next2_reg_393 = indvar_flatten_next2_fu_196_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st8_fsm_7.read())) {
        mult_reg_474 = grp_fu_183_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read())) {
        sum_mult_load_reg_469 = sum_mult_q0.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st13_fsm_12.read()) && esl_seteq<1,1,1>(exitcond_flatten2_reg_389.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_lv1_0, tmp_mid2_reg_420.read()))) {
        tmp_42_reg_479 = grp_fu_179_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read())) {
        tmp_55_reg_434 = grp_fu_381_p3.read();
        tmp_i_i_mid2_v_reg_428 = tmp_i_i_mid2_v_fu_306_p3.read();
        tmp_mid2_24_reg_424 = tmp_mid2_24_fu_299_p3.read();
        tmp_mid2_reg_420 = tmp_mid2_fu_280_p3.read();
    }
}

void dut_matrix_multiply_alt2::thread_A_address0() {
    A_address0 =  (sc_lv<13>) (tmp_62_cast_fu_323_p1.read());
}

void dut_matrix_multiply_alt2::thread_A_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read())) {
        A_ce0 = ap_const_logic_1;
    } else {
        A_ce0 = ap_const_logic_0;
    }
}

void dut_matrix_multiply_alt2::thread_B_address0() {
    B_address0 =  (sc_lv<17>) (tmp_64_cast_fu_330_p1.read());
}

void dut_matrix_multiply_alt2::thread_B_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read())) {
        B_ce0 = ap_const_logic_1;
    } else {
        B_ce0 = ap_const_logic_0;
    }
}

void dut_matrix_multiply_alt2::thread_C_address0() {
    C_address0 = C_addr_reg_454.read();
}

void dut_matrix_multiply_alt2::thread_C_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st14_fsm_13.read())) {
        C_ce0 = ap_const_logic_1;
    } else {
        C_ce0 = ap_const_logic_0;
    }
}

void dut_matrix_multiply_alt2::thread_C_d0() {
    C_d0 = tmp_42_reg_479.read();
}

void dut_matrix_multiply_alt2::thread_C_we0() {
    if (((esl_seteq<1,1,1>(exitcond_flatten2_reg_389.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_mid2_reg_420.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st14_fsm_13.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_mid2_24_reg_424.read())))) {
        C_we0 = ap_const_logic_1;
    } else {
        C_we0 = ap_const_logic_0;
    }
}

void dut_matrix_multiply_alt2::thread_Col_assign_mid2_fu_246_p3() {
    Col_assign_mid2_fu_246_p3 = (!tmp_53_fu_240_p2.read()[0].is_01())? sc_lv<7>(): ((tmp_53_fu_240_p2.read()[0].to_bool())? ap_const_lv7_0: Col_assign_reg_168.read());
}

void dut_matrix_multiply_alt2::thread_Row_assign_mid_fu_208_p3() {
    Row_assign_mid_fu_208_p3 = (!exitcond_flatten_fu_202_p2.read()[0].is_01())? sc_lv<4>(): ((exitcond_flatten_fu_202_p2.read()[0].to_bool())? ap_const_lv4_0: Row_assign_reg_157.read());
}

void dut_matrix_multiply_alt2::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st15_fsm_14.read()))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void dut_matrix_multiply_alt2::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void dut_matrix_multiply_alt2::thread_ap_ready() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st15_fsm_14.read())) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void dut_matrix_multiply_alt2::thread_ap_sig_108() {
    ap_sig_108 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(4, 4));
}

void dut_matrix_multiply_alt2::thread_ap_sig_122() {
    ap_sig_122 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(5, 5));
}

void dut_matrix_multiply_alt2::thread_ap_sig_131() {
    ap_sig_131 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(7, 7));
}

void dut_matrix_multiply_alt2::thread_ap_sig_140() {
    ap_sig_140 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(12, 12));
}

void dut_matrix_multiply_alt2::thread_ap_sig_153() {
    ap_sig_153 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(13, 13));
}

void dut_matrix_multiply_alt2::thread_ap_sig_208() {
    ap_sig_208 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(8, 8));
}

void dut_matrix_multiply_alt2::thread_ap_sig_32() {
    ap_sig_32 = esl_seteq<1,1,1>(ap_CS_fsm.read().range(0, 0), ap_const_lv1_1);
}

void dut_matrix_multiply_alt2::thread_ap_sig_365() {
    ap_sig_365 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(14, 14));
}

void dut_matrix_multiply_alt2::thread_ap_sig_63() {
    ap_sig_63 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(1, 1));
}

void dut_matrix_multiply_alt2::thread_ap_sig_83() {
    ap_sig_83 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(2, 2));
}

void dut_matrix_multiply_alt2::thread_ap_sig_98() {
    ap_sig_98 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(3, 3));
}

void dut_matrix_multiply_alt2::thread_ap_sig_cseq_ST_st13_fsm_12() {
    if (ap_sig_140.read()) {
        ap_sig_cseq_ST_st13_fsm_12 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st13_fsm_12 = ap_const_logic_0;
    }
}

void dut_matrix_multiply_alt2::thread_ap_sig_cseq_ST_st14_fsm_13() {
    if (ap_sig_153.read()) {
        ap_sig_cseq_ST_st14_fsm_13 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st14_fsm_13 = ap_const_logic_0;
    }
}

void dut_matrix_multiply_alt2::thread_ap_sig_cseq_ST_st15_fsm_14() {
    if (ap_sig_365.read()) {
        ap_sig_cseq_ST_st15_fsm_14 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st15_fsm_14 = ap_const_logic_0;
    }
}

void dut_matrix_multiply_alt2::thread_ap_sig_cseq_ST_st1_fsm_0() {
    if (ap_sig_32.read()) {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    }
}

void dut_matrix_multiply_alt2::thread_ap_sig_cseq_ST_st2_fsm_1() {
    if (ap_sig_63.read()) {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_0;
    }
}

void dut_matrix_multiply_alt2::thread_ap_sig_cseq_ST_st3_fsm_2() {
    if (ap_sig_83.read()) {
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_0;
    }
}

void dut_matrix_multiply_alt2::thread_ap_sig_cseq_ST_st4_fsm_3() {
    if (ap_sig_98.read()) {
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_0;
    }
}

void dut_matrix_multiply_alt2::thread_ap_sig_cseq_ST_st5_fsm_4() {
    if (ap_sig_108.read()) {
        ap_sig_cseq_ST_st5_fsm_4 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st5_fsm_4 = ap_const_logic_0;
    }
}

void dut_matrix_multiply_alt2::thread_ap_sig_cseq_ST_st6_fsm_5() {
    if (ap_sig_122.read()) {
        ap_sig_cseq_ST_st6_fsm_5 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st6_fsm_5 = ap_const_logic_0;
    }
}

void dut_matrix_multiply_alt2::thread_ap_sig_cseq_ST_st8_fsm_7() {
    if (ap_sig_131.read()) {
        ap_sig_cseq_ST_st8_fsm_7 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st8_fsm_7 = ap_const_logic_0;
    }
}

void dut_matrix_multiply_alt2::thread_ap_sig_cseq_ST_st9_fsm_8() {
    if (ap_sig_208.read()) {
        ap_sig_cseq_ST_st9_fsm_8 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st9_fsm_8 = ap_const_logic_0;
    }
}

void dut_matrix_multiply_alt2::thread_c_fu_345_p2() {
    c_fu_345_p2 = (!Col_assign_mid2_reg_406.read().is_01() || !ap_const_lv7_1.is_01())? sc_lv<7>(): (sc_biguint<7>(Col_assign_mid2_reg_406.read()) + sc_biguint<7>(ap_const_lv7_1));
}

void dut_matrix_multiply_alt2::thread_exitcond_flatten2_fu_190_p2() {
    exitcond_flatten2_fu_190_p2 = (!indvar_flatten2_reg_122.read().is_01() || !ap_const_lv20_BF680.is_01())? sc_lv<1>(): sc_lv<1>(indvar_flatten2_reg_122.read() == ap_const_lv20_BF680);
}

void dut_matrix_multiply_alt2::thread_exitcond_flatten_fu_202_p2() {
    exitcond_flatten_fu_202_p2 = (!indvar_flatten_reg_145.read().is_01() || !ap_const_lv11_3E8.is_01())? sc_lv<1>(): sc_lv<1>(indvar_flatten_reg_145.read() == ap_const_lv11_3E8);
}

void dut_matrix_multiply_alt2::thread_exitcond_fu_222_p2() {
    exitcond_fu_222_p2 = (!Col_assign_reg_168.read().is_01() || !ap_const_lv7_64.is_01())? sc_lv<1>(): sc_lv<1>(Col_assign_reg_168.read() == ap_const_lv7_64);
}

void dut_matrix_multiply_alt2::thread_exitcond_mid_fu_228_p2() {
    exitcond_mid_fu_228_p2 = (exitcond_fu_222_p2.read() & not_exitcond_flatten_fu_216_p2.read());
}

void dut_matrix_multiply_alt2::thread_grp_fu_363_p0() {
    grp_fu_363_p0 =  (sc_lv<4>) (grp_fu_363_p00.read());
}

void dut_matrix_multiply_alt2::thread_grp_fu_363_p00() {
    grp_fu_363_p00 = esl_zext<11,4>(tmp_40_mid2_reg_413.read());
}

void dut_matrix_multiply_alt2::thread_grp_fu_363_p1() {
    grp_fu_363_p1 =  (sc_lv<8>) (ap_const_lv11_64);
}

void dut_matrix_multiply_alt2::thread_grp_fu_363_p2() {
    grp_fu_363_p2 =  (sc_lv<7>) (grp_fu_363_p20.read());
}

void dut_matrix_multiply_alt2::thread_grp_fu_363_p20() {
    grp_fu_363_p20 = esl_zext<11,7>(Col_assign_mid2_reg_406.read());
}

void dut_matrix_multiply_alt2::thread_grp_fu_372_p0() {
    grp_fu_372_p0 =  (sc_lv<10>) (grp_fu_372_p00.read());
}

void dut_matrix_multiply_alt2::thread_grp_fu_372_p00() {
    grp_fu_372_p00 = esl_zext<17,10>(tmp_i_i_mid2_v_reg_428.read());
}

void dut_matrix_multiply_alt2::thread_grp_fu_372_p1() {
    grp_fu_372_p1 =  (sc_lv<8>) (ap_const_lv17_64);
}

void dut_matrix_multiply_alt2::thread_grp_fu_372_p2() {
    grp_fu_372_p2 =  (sc_lv<7>) (grp_fu_372_p20.read());
}

void dut_matrix_multiply_alt2::thread_grp_fu_372_p20() {
    grp_fu_372_p20 = esl_zext<17,7>(Col_assign_mid2_reg_406.read());
}

void dut_matrix_multiply_alt2::thread_grp_fu_381_p0() {
    grp_fu_381_p0 =  (sc_lv<4>) (grp_fu_381_p00.read());
}

void dut_matrix_multiply_alt2::thread_grp_fu_381_p00() {
    grp_fu_381_p00 = esl_zext<14,4>(tmp_40_mid2_reg_413.read());
}

void dut_matrix_multiply_alt2::thread_grp_fu_381_p1() {
    grp_fu_381_p1 =  (sc_lv<11>) (ap_const_lv14_310);
}

void dut_matrix_multiply_alt2::thread_grp_fu_381_p2() {
    grp_fu_381_p2 =  (sc_lv<10>) (grp_fu_381_p20.read());
}

void dut_matrix_multiply_alt2::thread_grp_fu_381_p20() {
    grp_fu_381_p20 = esl_zext<14,10>(tmp_i_i_mid2_v_fu_306_p3.read());
}

void dut_matrix_multiply_alt2::thread_indvar_flatten_next2_fu_196_p2() {
    indvar_flatten_next2_fu_196_p2 = (!indvar_flatten2_reg_122.read().is_01() || !ap_const_lv20_1.is_01())? sc_lv<20>(): (sc_biguint<20>(indvar_flatten2_reg_122.read()) + sc_biguint<20>(ap_const_lv20_1));
}

void dut_matrix_multiply_alt2::thread_indvar_flatten_next_fu_356_p3() {
    indvar_flatten_next_fu_356_p3 = (!exitcond_flatten_reg_398.read()[0].is_01())? sc_lv<11>(): ((exitcond_flatten_reg_398.read()[0].to_bool())? ap_const_lv11_1: indvar_flatten_op_fu_350_p2.read());
}

void dut_matrix_multiply_alt2::thread_indvar_flatten_op_fu_350_p2() {
    indvar_flatten_op_fu_350_p2 = (!indvar_flatten_reg_145.read().is_01() || !ap_const_lv11_1.is_01())? sc_lv<11>(): (sc_biguint<11>(indvar_flatten_reg_145.read()) + sc_biguint<11>(ap_const_lv11_1));
}

void dut_matrix_multiply_alt2::thread_k_fu_262_p2() {
    k_fu_262_p2 = (!Col_assign_3_reg_133.read().is_01() || !ap_const_lv10_1.is_01())? sc_lv<10>(): (sc_biguint<10>(Col_assign_3_reg_133.read()) + sc_biguint<10>(ap_const_lv10_1));
}

void dut_matrix_multiply_alt2::thread_not_exitcond_flatten_fu_216_p2() {
    not_exitcond_flatten_fu_216_p2 = (exitcond_flatten_fu_202_p2.read() ^ ap_const_lv1_1);
}

void dut_matrix_multiply_alt2::thread_r_fu_234_p2() {
    r_fu_234_p2 = (!Row_assign_mid_fu_208_p3.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(Row_assign_mid_fu_208_p3.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void dut_matrix_multiply_alt2::thread_sum_mult_address0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st8_fsm_7.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st14_fsm_13.read()))) {
        sum_mult_address0 = sum_mult_addr_reg_459.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read())) {
        sum_mult_address0 =  (sc_lv<10>) (tmp_65_cast_fu_340_p1.read());
    } else {
        sum_mult_address0 = "XXXXXXXXXX";
    }
}

void dut_matrix_multiply_alt2::thread_sum_mult_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st8_fsm_7.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st14_fsm_13.read()))) {
        sum_mult_ce0 = ap_const_logic_1;
    } else {
        sum_mult_ce0 = ap_const_logic_0;
    }
}

void dut_matrix_multiply_alt2::thread_sum_mult_d0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st14_fsm_13.read())) {
        sum_mult_d0 = tmp_42_reg_479.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st8_fsm_7.read())) {
        sum_mult_d0 = grp_fu_183_p2.read();
    } else {
        sum_mult_d0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void dut_matrix_multiply_alt2::thread_sum_mult_we0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st8_fsm_7.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_mid2_reg_420.read())) || 
         (esl_seteq<1,1,1>(exitcond_flatten2_reg_389.read(), ap_const_lv1_0) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_mid2_reg_420.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st14_fsm_13.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_mid2_24_reg_424.read())))) {
        sum_mult_we0 = ap_const_logic_1;
    } else {
        sum_mult_we0 = ap_const_logic_0;
    }
}

void dut_matrix_multiply_alt2::thread_tmp2_fu_274_p2() {
    tmp2_fu_274_p2 = (!Col_assign_3_reg_133.read().is_01() || !ap_const_lv10_0.is_01())? sc_lv<1>(): sc_lv<1>(Col_assign_3_reg_133.read() == ap_const_lv10_0);
}

void dut_matrix_multiply_alt2::thread_tmp_1_fu_293_p2() {
    tmp_1_fu_293_p2 = (!Col_assign_3_reg_133.read().is_01() || !ap_const_lv10_30F.is_01())? sc_lv<1>(): sc_lv<1>(Col_assign_3_reg_133.read() == ap_const_lv10_30F);
}

void dut_matrix_multiply_alt2::thread_tmp_40_mid2_fu_254_p3() {
    tmp_40_mid2_fu_254_p3 = (!exitcond_mid_fu_228_p2.read()[0].is_01())? sc_lv<4>(): ((exitcond_mid_fu_228_p2.read()[0].to_bool())? r_fu_234_p2.read(): Row_assign_mid_fu_208_p3.read());
}

void dut_matrix_multiply_alt2::thread_tmp_53_fu_240_p2() {
    tmp_53_fu_240_p2 = (exitcond_mid_fu_228_p2.read() | exitcond_flatten_fu_202_p2.read());
}

void dut_matrix_multiply_alt2::thread_tmp_62_cast_fu_323_p1() {
    tmp_62_cast_fu_323_p1 = esl_sext<64,14>(tmp_55_reg_434.read());
}

void dut_matrix_multiply_alt2::thread_tmp_64_cast_fu_330_p1() {
    tmp_64_cast_fu_330_p1 = esl_zext<64,17>(grp_fu_372_p3.read());
}

void dut_matrix_multiply_alt2::thread_tmp_65_cast_fu_340_p1() {
    tmp_65_cast_fu_340_p1 = esl_sext<64,11>(grp_fu_363_p3.read());
}

void dut_matrix_multiply_alt2::thread_tmp_i_i_mid2_v_fu_306_p3() {
    tmp_i_i_mid2_v_fu_306_p3 = (!exitcond_flatten_reg_398.read()[0].is_01())? sc_lv<10>(): ((exitcond_flatten_reg_398.read()[0].to_bool())? k_fu_262_p2.read(): Col_assign_3_reg_133.read());
}

void dut_matrix_multiply_alt2::thread_tmp_mid1_23_fu_287_p2() {
    tmp_mid1_23_fu_287_p2 = (!k_fu_262_p2.read().is_01() || !ap_const_lv10_30F.is_01())? sc_lv<1>(): sc_lv<1>(k_fu_262_p2.read() == ap_const_lv10_30F);
}

void dut_matrix_multiply_alt2::thread_tmp_mid1_fu_268_p2() {
    tmp_mid1_fu_268_p2 = (!k_fu_262_p2.read().is_01() || !ap_const_lv10_0.is_01())? sc_lv<1>(): sc_lv<1>(k_fu_262_p2.read() == ap_const_lv10_0);
}

void dut_matrix_multiply_alt2::thread_tmp_mid2_24_fu_299_p3() {
    tmp_mid2_24_fu_299_p3 = (!exitcond_flatten_reg_398.read()[0].is_01())? sc_lv<1>(): ((exitcond_flatten_reg_398.read()[0].to_bool())? tmp_mid1_23_fu_287_p2.read(): tmp_1_fu_293_p2.read());
}

void dut_matrix_multiply_alt2::thread_tmp_mid2_fu_280_p3() {
    tmp_mid2_fu_280_p3 = (!exitcond_flatten_reg_398.read()[0].is_01())? sc_lv<1>(): ((exitcond_flatten_reg_398.read()[0].to_bool())? tmp_mid1_fu_268_p2.read(): tmp2_fu_274_p2.read());
}

void dut_matrix_multiply_alt2::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if (!esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) {
                ap_NS_fsm = ap_ST_st2_fsm_1;
            } else {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            }
            break;
        case 2 : 
            if (esl_seteq<1,1,1>(exitcond_flatten2_fu_190_p2.read(), ap_const_lv1_0)) {
                ap_NS_fsm = ap_ST_st3_fsm_2;
            } else {
                ap_NS_fsm = ap_ST_st15_fsm_14;
            }
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_st4_fsm_3;
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_st5_fsm_4;
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_st6_fsm_5;
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_st7_fsm_6;
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_st8_fsm_7;
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_st9_fsm_8;
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_st10_fsm_9;
            break;
        case 512 : 
            ap_NS_fsm = ap_ST_st11_fsm_10;
            break;
        case 1024 : 
            ap_NS_fsm = ap_ST_st12_fsm_11;
            break;
        case 2048 : 
            ap_NS_fsm = ap_ST_st13_fsm_12;
            break;
        case 4096 : 
            ap_NS_fsm = ap_ST_st14_fsm_13;
            break;
        case 8192 : 
            ap_NS_fsm = ap_ST_st2_fsm_1;
            break;
        case 16384 : 
            ap_NS_fsm = ap_ST_st1_fsm_0;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<15>) ("XXXXXXXXXXXXXXX");
            break;
    }
}

}

