// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.2
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "dut_backproj.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic dut_backproj::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic dut_backproj::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<9> dut_backproj::ap_ST_st1_fsm_0 = "1";
const sc_lv<9> dut_backproj::ap_ST_st2_fsm_1 = "10";
const sc_lv<9> dut_backproj::ap_ST_pp0_stg0_fsm_2 = "100";
const sc_lv<9> dut_backproj::ap_ST_pp1_stg0_fsm_3 = "1000";
const sc_lv<9> dut_backproj::ap_ST_pp1_stg1_fsm_4 = "10000";
const sc_lv<9> dut_backproj::ap_ST_pp1_stg2_fsm_5 = "100000";
const sc_lv<9> dut_backproj::ap_ST_pp1_stg3_fsm_6 = "1000000";
const sc_lv<9> dut_backproj::ap_ST_pp1_stg4_fsm_7 = "10000000";
const sc_lv<9> dut_backproj::ap_ST_st17_fsm_8 = "100000000";
const sc_lv<32> dut_backproj::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> dut_backproj::ap_const_lv1_1 = "1";
const sc_lv<32> dut_backproj::ap_const_lv32_2 = "10";
const sc_lv<1> dut_backproj::ap_const_lv1_0 = "0";
const sc_lv<32> dut_backproj::ap_const_lv32_4 = "100";
const sc_lv<32> dut_backproj::ap_const_lv32_1 = "1";
const sc_lv<32> dut_backproj::ap_const_lv32_3 = "11";
const sc_lv<32> dut_backproj::ap_const_lv32_5 = "101";
const sc_lv<32> dut_backproj::ap_const_lv32_7 = "111";
const sc_lv<4> dut_backproj::ap_const_lv4_0 = "0000";
const sc_lv<32> dut_backproj::ap_const_lv32_8 = "1000";
const sc_lv<10> dut_backproj::ap_const_lv10_0 = "0000000000";
const sc_lv<17> dut_backproj::ap_const_lv17_0 = "00000000000000000";
const sc_lv<4> dut_backproj::ap_const_lv4_A = "1010";
const sc_lv<4> dut_backproj::ap_const_lv4_1 = "1";
const sc_lv<10> dut_backproj::ap_const_lv10_310 = "1100010000";
const sc_lv<10> dut_backproj::ap_const_lv10_1 = "1";
const sc_lv<17> dut_backproj::ap_const_lv17_13240 = "10011001001000000";
const sc_lv<17> dut_backproj::ap_const_lv17_1 = "1";
const sc_lv<10> dut_backproj::ap_const_lv10_30F = "1100001111";
const sc_lv<32> dut_backproj::ap_const_lv32_6 = "110";

dut_backproj::dut_backproj(sc_module_name name) : sc_module(name), mVcdFile(0) {
    A_U = new dut_backproj_A("A_U");
    A_U->clk(ap_clk);
    A_U->reset(ap_rst);
    A_U->address0(A_address0);
    A_U->ce0(A_ce0);
    A_U->we0(A_we0);
    A_U->d0(strm_in_V_dout);
    A_U->q0(A_q0);
    dut_fadd_32ns_32ns_32_5_full_dsp_U1 = new dut_fadd_32ns_32ns_32_5_full_dsp<1,5,32,32,32>("dut_fadd_32ns_32ns_32_5_full_dsp_U1");
    dut_fadd_32ns_32ns_32_5_full_dsp_U1->clk(ap_clk);
    dut_fadd_32ns_32ns_32_5_full_dsp_U1->reset(ap_rst);
    dut_fadd_32ns_32ns_32_5_full_dsp_U1->din0(grp_fu_161_p0);
    dut_fadd_32ns_32ns_32_5_full_dsp_U1->din1(tmp_1_reg_336);
    dut_fadd_32ns_32ns_32_5_full_dsp_U1->ce(grp_fu_161_ce);
    dut_fadd_32ns_32ns_32_5_full_dsp_U1->dout(grp_fu_161_p2);
    dut_fmul_32ns_32ns_32_4_max_dsp_U2 = new dut_fmul_32ns_32ns_32_4_max_dsp<1,4,32,32,32>("dut_fmul_32ns_32ns_32_4_max_dsp_U2");
    dut_fmul_32ns_32ns_32_4_max_dsp_U2->clk(ap_clk);
    dut_fmul_32ns_32ns_32_4_max_dsp_U2->reset(ap_rst);
    dut_fmul_32ns_32ns_32_4_max_dsp_U2->din0(A_q0);
    dut_fmul_32ns_32ns_32_4_max_dsp_U2->din1(tmp_171_reg_317);
    dut_fmul_32ns_32ns_32_4_max_dsp_U2->ce(grp_fu_165_ce);
    dut_fmul_32ns_32ns_32_4_max_dsp_U2->dout(grp_fu_165_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_A_address0);
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_2 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_sig_cseq_ST_pp1_stg1_fsm_4 );
    sensitive << ( ap_reg_ppiten_pp1_it0 );
    sensitive << ( tmp_s_fu_199_p1 );
    sensitive << ( tmp_9_fu_235_p1 );

    SC_METHOD(thread_A_ce0);
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_2 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_sig_cseq_ST_pp1_stg1_fsm_4 );
    sensitive << ( ap_reg_ppiten_pp1_it0 );
    sensitive << ( ap_reg_ppiten_pp1_it2 );
    sensitive << ( ap_sig_101 );
    sensitive << ( ap_sig_130 );
    sensitive << ( ap_sig_134 );

    SC_METHOD(thread_A_we0);
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_2 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( exitcond7_reg_281 );
    sensitive << ( ap_sig_101 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( exitcond8_fu_175_p2 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( exitcond8_fu_175_p2 );
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );

    SC_METHOD(thread_ap_sig_101);
    sensitive << ( strm_in_V_empty_n );
    sensitive << ( exitcond7_reg_281 );

    SC_METHOD(thread_ap_sig_115);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_130);
    sensitive << ( strm_in_V_empty_n );
    sensitive << ( exitcond_flatten_reg_290 );

    SC_METHOD(thread_ap_sig_134);
    sensitive << ( strm_out_V_full_n );
    sensitive << ( ap_reg_ppstg_tmp_2_reg_322_pp1_iter1 );

    SC_METHOD(thread_ap_sig_157);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_186);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_212);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_26);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_292);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_45);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_61);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_94);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_cseq_ST_pp0_stg0_fsm_2);
    sensitive << ( ap_sig_45 );

    SC_METHOD(thread_ap_sig_cseq_ST_pp1_stg0_fsm_3);
    sensitive << ( ap_sig_115 );

    SC_METHOD(thread_ap_sig_cseq_ST_pp1_stg1_fsm_4);
    sensitive << ( ap_sig_61 );

    SC_METHOD(thread_ap_sig_cseq_ST_pp1_stg2_fsm_5);
    sensitive << ( ap_sig_157 );

    SC_METHOD(thread_ap_sig_cseq_ST_pp1_stg3_fsm_6);
    sensitive << ( ap_sig_292 );

    SC_METHOD(thread_ap_sig_cseq_ST_pp1_stg4_fsm_7);
    sensitive << ( ap_sig_186 );

    SC_METHOD(thread_ap_sig_cseq_ST_st17_fsm_8);
    sensitive << ( ap_sig_212 );

    SC_METHOD(thread_ap_sig_cseq_ST_st1_fsm_0);
    sensitive << ( ap_sig_26 );

    SC_METHOD(thread_ap_sig_cseq_ST_st2_fsm_1);
    sensitive << ( ap_sig_94 );

    SC_METHOD(thread_exitcond7_fu_187_p2);
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_2 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_sig_101 );
    sensitive << ( m_phi_fu_131_p4 );

    SC_METHOD(thread_exitcond8_fu_175_p2);
    sensitive << ( ap_sig_cseq_ST_st2_fsm_1 );
    sensitive << ( i_reg_116 );

    SC_METHOD(thread_exitcond_flatten_fu_204_p2);
    sensitive << ( ap_reg_ppiten_pp1_it0 );
    sensitive << ( ap_sig_cseq_ST_pp1_stg0_fsm_3 );
    sensitive << ( indvar_flatten_phi_fu_143_p4 );

    SC_METHOD(thread_exitcond_fu_216_p2);
    sensitive << ( ap_reg_ppiten_pp1_it0 );
    sensitive << ( exitcond_flatten_fu_204_p2 );
    sensitive << ( ap_sig_cseq_ST_pp1_stg0_fsm_3 );
    sensitive << ( k_phi_fu_154_p4 );

    SC_METHOD(thread_grp_fu_161_ce);
    sensitive << ( ap_sig_cseq_ST_pp1_stg1_fsm_4 );
    sensitive << ( ap_reg_ppiten_pp1_it0 );
    sensitive << ( ap_reg_ppiten_pp1_it2 );
    sensitive << ( ap_sig_cseq_ST_pp1_stg0_fsm_3 );
    sensitive << ( ap_sig_130 );
    sensitive << ( ap_sig_134 );
    sensitive << ( ap_sig_cseq_ST_pp1_stg2_fsm_5 );
    sensitive << ( ap_sig_cseq_ST_pp1_stg4_fsm_7 );
    sensitive << ( ap_sig_cseq_ST_pp1_stg3_fsm_6 );

    SC_METHOD(thread_grp_fu_161_p0);
    sensitive << ( ap_sig_cseq_ST_pp1_stg1_fsm_4 );
    sensitive << ( ap_reg_ppiten_pp1_it1 );
    sensitive << ( tmp_8_reg_307 );
    sensitive << ( tmp_fu_76 );

    SC_METHOD(thread_grp_fu_165_ce);
    sensitive << ( ap_sig_cseq_ST_pp1_stg0_fsm_3 );
    sensitive << ( ap_sig_cseq_ST_pp1_stg2_fsm_5 );
    sensitive << ( ap_sig_cseq_ST_pp1_stg4_fsm_7 );
    sensitive << ( ap_sig_cseq_ST_pp1_stg3_fsm_6 );

    SC_METHOD(thread_i_2_fu_181_p2);
    sensitive << ( i_reg_116 );

    SC_METHOD(thread_indvar_flatten_next_fu_210_p2);
    sensitive << ( indvar_flatten_phi_fu_143_p4 );

    SC_METHOD(thread_indvar_flatten_phi_fu_143_p4);
    sensitive << ( ap_reg_ppiten_pp1_it1 );
    sensitive << ( exitcond_flatten_reg_290 );
    sensitive << ( indvar_flatten_reg_139 );
    sensitive << ( ap_sig_cseq_ST_pp1_stg0_fsm_3 );
    sensitive << ( indvar_flatten_next_reg_294 );

    SC_METHOD(thread_k_1_fu_244_p2);
    sensitive << ( k_mid2_reg_299 );

    SC_METHOD(thread_k_mid2_fu_222_p3);
    sensitive << ( k_phi_fu_154_p4 );
    sensitive << ( exitcond_fu_216_p2 );

    SC_METHOD(thread_k_phi_fu_154_p4);
    sensitive << ( ap_reg_ppiten_pp1_it1 );
    sensitive << ( exitcond_flatten_reg_290 );
    sensitive << ( k_reg_150 );
    sensitive << ( ap_sig_cseq_ST_pp1_stg0_fsm_3 );
    sensitive << ( k_1_reg_326 );

    SC_METHOD(thread_m_2_fu_193_p2);
    sensitive << ( m_phi_fu_131_p4 );

    SC_METHOD(thread_m_phi_fu_131_p4);
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_2 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( exitcond7_reg_281 );
    sensitive << ( m_reg_127 );
    sensitive << ( m_2_reg_285 );

    SC_METHOD(thread_strm_in_V_blk_n);
    sensitive << ( strm_in_V_empty_n );
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_2 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( exitcond7_reg_281 );
    sensitive << ( ap_sig_cseq_ST_pp1_stg1_fsm_4 );
    sensitive << ( ap_reg_ppiten_pp1_it0 );
    sensitive << ( exitcond_flatten_reg_290 );

    SC_METHOD(thread_strm_in_V_read);
    sensitive << ( ap_sig_cseq_ST_pp0_stg0_fsm_2 );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( exitcond7_reg_281 );
    sensitive << ( ap_sig_cseq_ST_pp1_stg1_fsm_4 );
    sensitive << ( ap_reg_ppiten_pp1_it0 );
    sensitive << ( ap_reg_ppiten_pp1_it2 );
    sensitive << ( exitcond_flatten_reg_290 );
    sensitive << ( ap_sig_101 );
    sensitive << ( ap_sig_130 );
    sensitive << ( ap_sig_134 );

    SC_METHOD(thread_strm_out_V_blk_n);
    sensitive << ( strm_out_V_full_n );
    sensitive << ( ap_sig_cseq_ST_pp1_stg1_fsm_4 );
    sensitive << ( ap_reg_ppiten_pp1_it2 );
    sensitive << ( ap_reg_ppstg_tmp_2_reg_322_pp1_iter1 );

    SC_METHOD(thread_strm_out_V_din);
    sensitive << ( ap_sig_cseq_ST_pp1_stg1_fsm_4 );
    sensitive << ( ap_reg_ppiten_pp1_it0 );
    sensitive << ( ap_reg_ppiten_pp1_it2 );
    sensitive << ( ap_reg_ppstg_tmp_2_reg_322_pp1_iter1 );
    sensitive << ( ap_sig_130 );
    sensitive << ( ap_sig_134 );
    sensitive << ( tmp_172_reg_346 );

    SC_METHOD(thread_strm_out_V_write);
    sensitive << ( ap_sig_cseq_ST_pp1_stg1_fsm_4 );
    sensitive << ( ap_reg_ppiten_pp1_it0 );
    sensitive << ( ap_reg_ppiten_pp1_it2 );
    sensitive << ( ap_reg_ppstg_tmp_2_reg_322_pp1_iter1 );
    sensitive << ( ap_sig_130 );
    sensitive << ( ap_sig_134 );

    SC_METHOD(thread_tmp_2_fu_239_p2);
    sensitive << ( ap_sig_cseq_ST_pp1_stg1_fsm_4 );
    sensitive << ( ap_reg_ppiten_pp1_it0 );
    sensitive << ( ap_reg_ppiten_pp1_it2 );
    sensitive << ( exitcond_flatten_reg_290 );
    sensitive << ( k_mid2_reg_299 );
    sensitive << ( ap_sig_130 );
    sensitive << ( ap_sig_134 );

    SC_METHOD(thread_tmp_8_fu_230_p2);
    sensitive << ( ap_sig_cseq_ST_pp1_stg1_fsm_4 );
    sensitive << ( ap_reg_ppiten_pp1_it0 );
    sensitive << ( ap_reg_ppiten_pp1_it2 );
    sensitive << ( exitcond_flatten_reg_290 );
    sensitive << ( k_mid2_reg_299 );
    sensitive << ( ap_sig_130 );
    sensitive << ( ap_sig_134 );

    SC_METHOD(thread_tmp_9_fu_235_p1);
    sensitive << ( k_mid2_reg_299 );

    SC_METHOD(thread_tmp_s_fu_199_p1);
    sensitive << ( m_reg_127 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_reg_ppiten_pp0_it1 );
    sensitive << ( ap_reg_ppiten_pp0_it0 );
    sensitive << ( ap_sig_cseq_ST_pp1_stg1_fsm_4 );
    sensitive << ( ap_reg_ppiten_pp1_it0 );
    sensitive << ( ap_reg_ppiten_pp1_it1 );
    sensitive << ( ap_reg_ppiten_pp1_it2 );
    sensitive << ( exitcond8_fu_175_p2 );
    sensitive << ( exitcond7_fu_187_p2 );
    sensitive << ( ap_sig_101 );
    sensitive << ( exitcond_flatten_fu_204_p2 );
    sensitive << ( ap_sig_130 );
    sensitive << ( ap_sig_134 );

    ap_CS_fsm = "000000001";
    ap_reg_ppiten_pp0_it1 = SC_LOGIC_0;
    ap_reg_ppiten_pp0_it0 = SC_LOGIC_0;
    ap_reg_ppiten_pp1_it0 = SC_LOGIC_0;
    ap_reg_ppiten_pp1_it1 = SC_LOGIC_0;
    ap_reg_ppiten_pp1_it2 = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "dut_backproj_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, strm_in_V_dout, "(port)strm_in_V_dout");
    sc_trace(mVcdFile, strm_in_V_empty_n, "(port)strm_in_V_empty_n");
    sc_trace(mVcdFile, strm_in_V_read, "(port)strm_in_V_read");
    sc_trace(mVcdFile, strm_out_V_din, "(port)strm_out_V_din");
    sc_trace(mVcdFile, strm_out_V_full_n, "(port)strm_out_V_full_n");
    sc_trace(mVcdFile, strm_out_V_write, "(port)strm_out_V_write");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st1_fsm_0, "ap_sig_cseq_ST_st1_fsm_0");
    sc_trace(mVcdFile, ap_sig_26, "ap_sig_26");
    sc_trace(mVcdFile, strm_in_V_blk_n, "strm_in_V_blk_n");
    sc_trace(mVcdFile, ap_sig_cseq_ST_pp0_stg0_fsm_2, "ap_sig_cseq_ST_pp0_stg0_fsm_2");
    sc_trace(mVcdFile, ap_sig_45, "ap_sig_45");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it1, "ap_reg_ppiten_pp0_it1");
    sc_trace(mVcdFile, ap_reg_ppiten_pp0_it0, "ap_reg_ppiten_pp0_it0");
    sc_trace(mVcdFile, exitcond7_reg_281, "exitcond7_reg_281");
    sc_trace(mVcdFile, ap_sig_cseq_ST_pp1_stg1_fsm_4, "ap_sig_cseq_ST_pp1_stg1_fsm_4");
    sc_trace(mVcdFile, ap_sig_61, "ap_sig_61");
    sc_trace(mVcdFile, ap_reg_ppiten_pp1_it0, "ap_reg_ppiten_pp1_it0");
    sc_trace(mVcdFile, ap_reg_ppiten_pp1_it1, "ap_reg_ppiten_pp1_it1");
    sc_trace(mVcdFile, ap_reg_ppiten_pp1_it2, "ap_reg_ppiten_pp1_it2");
    sc_trace(mVcdFile, exitcond_flatten_reg_290, "exitcond_flatten_reg_290");
    sc_trace(mVcdFile, strm_out_V_blk_n, "strm_out_V_blk_n");
    sc_trace(mVcdFile, tmp_2_reg_322, "tmp_2_reg_322");
    sc_trace(mVcdFile, ap_reg_ppstg_tmp_2_reg_322_pp1_iter1, "ap_reg_ppstg_tmp_2_reg_322_pp1_iter1");
    sc_trace(mVcdFile, m_reg_127, "m_reg_127");
    sc_trace(mVcdFile, indvar_flatten_reg_139, "indvar_flatten_reg_139");
    sc_trace(mVcdFile, k_reg_150, "k_reg_150");
    sc_trace(mVcdFile, exitcond8_fu_175_p2, "exitcond8_fu_175_p2");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st2_fsm_1, "ap_sig_cseq_ST_st2_fsm_1");
    sc_trace(mVcdFile, ap_sig_94, "ap_sig_94");
    sc_trace(mVcdFile, i_2_fu_181_p2, "i_2_fu_181_p2");
    sc_trace(mVcdFile, i_2_reg_276, "i_2_reg_276");
    sc_trace(mVcdFile, exitcond7_fu_187_p2, "exitcond7_fu_187_p2");
    sc_trace(mVcdFile, ap_sig_101, "ap_sig_101");
    sc_trace(mVcdFile, m_2_fu_193_p2, "m_2_fu_193_p2");
    sc_trace(mVcdFile, m_2_reg_285, "m_2_reg_285");
    sc_trace(mVcdFile, exitcond_flatten_fu_204_p2, "exitcond_flatten_fu_204_p2");
    sc_trace(mVcdFile, ap_sig_cseq_ST_pp1_stg0_fsm_3, "ap_sig_cseq_ST_pp1_stg0_fsm_3");
    sc_trace(mVcdFile, ap_sig_115, "ap_sig_115");
    sc_trace(mVcdFile, ap_reg_ppstg_exitcond_flatten_reg_290_pp1_iter1, "ap_reg_ppstg_exitcond_flatten_reg_290_pp1_iter1");
    sc_trace(mVcdFile, indvar_flatten_next_fu_210_p2, "indvar_flatten_next_fu_210_p2");
    sc_trace(mVcdFile, indvar_flatten_next_reg_294, "indvar_flatten_next_reg_294");
    sc_trace(mVcdFile, k_mid2_fu_222_p3, "k_mid2_fu_222_p3");
    sc_trace(mVcdFile, k_mid2_reg_299, "k_mid2_reg_299");
    sc_trace(mVcdFile, tmp_8_fu_230_p2, "tmp_8_fu_230_p2");
    sc_trace(mVcdFile, tmp_8_reg_307, "tmp_8_reg_307");
    sc_trace(mVcdFile, ap_sig_130, "ap_sig_130");
    sc_trace(mVcdFile, ap_sig_134, "ap_sig_134");
    sc_trace(mVcdFile, tmp_171_reg_317, "tmp_171_reg_317");
    sc_trace(mVcdFile, tmp_2_fu_239_p2, "tmp_2_fu_239_p2");
    sc_trace(mVcdFile, k_1_fu_244_p2, "k_1_fu_244_p2");
    sc_trace(mVcdFile, k_1_reg_326, "k_1_reg_326");
    sc_trace(mVcdFile, A_q0, "A_q0");
    sc_trace(mVcdFile, ap_sig_cseq_ST_pp1_stg2_fsm_5, "ap_sig_cseq_ST_pp1_stg2_fsm_5");
    sc_trace(mVcdFile, ap_sig_157, "ap_sig_157");
    sc_trace(mVcdFile, grp_fu_165_p2, "grp_fu_165_p2");
    sc_trace(mVcdFile, tmp_1_reg_336, "tmp_1_reg_336");
    sc_trace(mVcdFile, grp_fu_161_p2, "grp_fu_161_p2");
    sc_trace(mVcdFile, tmp_172_reg_346, "tmp_172_reg_346");
    sc_trace(mVcdFile, ap_sig_cseq_ST_pp1_stg4_fsm_7, "ap_sig_cseq_ST_pp1_stg4_fsm_7");
    sc_trace(mVcdFile, ap_sig_186, "ap_sig_186");
    sc_trace(mVcdFile, A_address0, "A_address0");
    sc_trace(mVcdFile, A_ce0, "A_ce0");
    sc_trace(mVcdFile, A_we0, "A_we0");
    sc_trace(mVcdFile, i_reg_116, "i_reg_116");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st17_fsm_8, "ap_sig_cseq_ST_st17_fsm_8");
    sc_trace(mVcdFile, ap_sig_212, "ap_sig_212");
    sc_trace(mVcdFile, m_phi_fu_131_p4, "m_phi_fu_131_p4");
    sc_trace(mVcdFile, indvar_flatten_phi_fu_143_p4, "indvar_flatten_phi_fu_143_p4");
    sc_trace(mVcdFile, k_phi_fu_154_p4, "k_phi_fu_154_p4");
    sc_trace(mVcdFile, tmp_s_fu_199_p1, "tmp_s_fu_199_p1");
    sc_trace(mVcdFile, tmp_9_fu_235_p1, "tmp_9_fu_235_p1");
    sc_trace(mVcdFile, tmp_fu_76, "tmp_fu_76");
    sc_trace(mVcdFile, grp_fu_161_p0, "grp_fu_161_p0");
    sc_trace(mVcdFile, exitcond_fu_216_p2, "exitcond_fu_216_p2");
    sc_trace(mVcdFile, grp_fu_161_ce, "grp_fu_161_ce");
    sc_trace(mVcdFile, ap_sig_cseq_ST_pp1_stg3_fsm_6, "ap_sig_cseq_ST_pp1_stg3_fsm_6");
    sc_trace(mVcdFile, ap_sig_292, "ap_sig_292");
    sc_trace(mVcdFile, grp_fu_165_ce, "grp_fu_165_ce");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

dut_backproj::~dut_backproj() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete A_U;
    delete dut_fadd_32ns_32ns_32_5_full_dsp_U1;
    delete dut_fmul_32ns_32ns_32_4_max_dsp_U2;
}

void dut_backproj::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_st1_fsm_0;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && 
             !(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && ap_sig_101.read()) && 
             !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond7_fu_187_p2.read()))) {
            ap_reg_ppiten_pp0_it0 = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
                    esl_seteq<1,1,1>(ap_const_lv1_0, exitcond8_fu_175_p2.read()))) {
            ap_reg_ppiten_pp0_it0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp0_it1 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && 
             !(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && ap_sig_101.read()) && 
             esl_seteq<1,1,1>(ap_const_lv1_0, exitcond7_fu_187_p2.read()))) {
            ap_reg_ppiten_pp0_it1 = ap_const_logic_1;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
                     esl_seteq<1,1,1>(ap_const_lv1_0, exitcond8_fu_175_p2.read())) || 
                    (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && 
                     !(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && ap_sig_101.read()) && 
                     !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond7_fu_187_p2.read())))) {
            ap_reg_ppiten_pp0_it1 = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp1_it0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp1_stg0_fsm_3.read()) && 
             !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_flatten_fu_204_p2.read()))) {
            ap_reg_ppiten_pp1_it0 = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && 
                    esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
                    !(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && ap_sig_101.read()) && 
                    !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond7_fu_187_p2.read()))) {
            ap_reg_ppiten_pp1_it0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp1_it1 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_flatten_reg_290.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp1_stg4_fsm_7.read()))) {
            ap_reg_ppiten_pp1_it1 = ap_const_logic_1;
        } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && 
                     esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
                     !(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && ap_sig_101.read()) && 
                     !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond7_fu_187_p2.read())) || 
                    (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp1_stg4_fsm_7.read()) && 
                     !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_flatten_reg_290.read())))) {
            ap_reg_ppiten_pp1_it1 = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_ppiten_pp1_it2 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp1_stg4_fsm_7.read())) {
            ap_reg_ppiten_pp1_it2 = ap_reg_ppiten_pp1_it1.read();
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && 
                    esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
                    !(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && ap_sig_101.read()) && 
                    !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond7_fu_187_p2.read()))) {
            ap_reg_ppiten_pp1_it2 = ap_const_logic_0;
        }
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st17_fsm_8.read())) {
        i_reg_116 = i_2_reg_276.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        i_reg_116 = ap_const_lv4_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && ap_sig_101.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond7_fu_187_p2.read()))) {
        indvar_flatten_reg_139 = ap_const_lv17_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it1.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_flatten_reg_290.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp1_stg0_fsm_3.read()))) {
        indvar_flatten_reg_139 = indvar_flatten_next_reg_294.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && ap_sig_101.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond7_fu_187_p2.read()))) {
        k_reg_150 = ap_const_lv10_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it1.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_flatten_reg_290.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp1_stg0_fsm_3.read()))) {
        k_reg_150 = k_1_reg_326.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
         esl_seteq<1,1,1>(exitcond7_reg_281.read(), ap_const_lv1_0) && 
         !(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && ap_sig_101.read()))) {
        m_reg_127 = m_2_reg_285.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, exitcond8_fu_175_p2.read()))) {
        m_reg_127 = ap_const_lv10_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it2.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp1_stg0_fsm_3.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_exitcond_flatten_reg_290_pp1_iter1.read()))) {
        tmp_fu_76 = grp_fu_161_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()) && 
                !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        tmp_fu_76 = ap_const_lv32_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp1_stg0_fsm_3.read())) {
        ap_reg_ppstg_exitcond_flatten_reg_290_pp1_iter1 = exitcond_flatten_reg_290.read();
        exitcond_flatten_reg_290 = exitcond_flatten_fu_204_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp1_stg1_fsm_4.read()) && !((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it0.read()) && 
  ap_sig_130.read()) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it2.read()) && 
  ap_sig_134.read())))) {
        ap_reg_ppstg_tmp_2_reg_322_pp1_iter1 = tmp_2_reg_322.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && ap_sig_101.read()))) {
        exitcond7_reg_281 = exitcond7_fu_187_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        i_2_reg_276 = i_2_fu_181_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it0.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp1_stg0_fsm_3.read()))) {
        indvar_flatten_next_reg_294 = indvar_flatten_next_fu_210_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp1_stg1_fsm_4.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it0.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_flatten_reg_290.read()) && !((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it0.read()) && 
  ap_sig_130.read()) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it2.read()) && 
  ap_sig_134.read())))) {
        k_1_reg_326 = k_1_fu_244_p2.read();
        tmp_171_reg_317 = strm_in_V_dout.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp1_stg0_fsm_3.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_flatten_fu_204_p2.read()))) {
        k_mid2_reg_299 = k_mid2_fu_222_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && ap_sig_101.read()))) {
        m_2_reg_285 = m_2_fu_193_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp1_stg0_fsm_3.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_exitcond_flatten_reg_290_pp1_iter1.read()))) {
        tmp_172_reg_346 = grp_fu_161_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_flatten_reg_290.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp1_stg0_fsm_3.read()))) {
        tmp_1_reg_336 = grp_fu_165_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp1_stg1_fsm_4.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_flatten_reg_290.read()) && !((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it0.read()) && 
  ap_sig_130.read()) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it2.read()) && 
  ap_sig_134.read())))) {
        tmp_2_reg_322 = tmp_2_fu_239_p2.read();
        tmp_8_reg_307 = tmp_8_fu_230_p2.read();
    }
}

void dut_backproj::thread_A_address0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()))) {
        A_address0 =  (sc_lv<10>) (tmp_s_fu_199_p1.read());
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp1_stg1_fsm_4.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it0.read()))) {
        A_address0 =  (sc_lv<10>) (tmp_9_fu_235_p1.read());
    } else {
        A_address0 = "XXXXXXXXXX";
    }
}

void dut_backproj::thread_A_ce0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp1_stg1_fsm_4.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it0.read()) && 
          !((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it0.read()) && 
  ap_sig_130.read()) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it2.read()) && 
  ap_sig_134.read()))) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
          !(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && ap_sig_101.read())))) {
        A_ce0 = ap_const_logic_1;
    } else {
        A_ce0 = ap_const_logic_0;
    }
}

void dut_backproj::thread_A_we0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
          esl_seteq<1,1,1>(exitcond7_reg_281.read(), ap_const_lv1_0) && 
          !(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && ap_sig_101.read())))) {
        A_we0 = ap_const_logic_1;
    } else {
        A_we0 = ap_const_logic_0;
    }
}

void dut_backproj::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond8_fu_175_p2.read())))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void dut_backproj::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void dut_backproj::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond8_fu_175_p2.read()))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void dut_backproj::thread_ap_sig_101() {
    ap_sig_101 = (esl_seteq<1,1,1>(exitcond7_reg_281.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(strm_in_V_empty_n.read(), ap_const_logic_0));
}

void dut_backproj::thread_ap_sig_115() {
    ap_sig_115 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(3, 3));
}

void dut_backproj::thread_ap_sig_130() {
    ap_sig_130 = (esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_flatten_reg_290.read()) && esl_seteq<1,1,1>(strm_in_V_empty_n.read(), ap_const_logic_0));
}

void dut_backproj::thread_ap_sig_134() {
    ap_sig_134 = (!esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_tmp_2_reg_322_pp1_iter1.read()) && esl_seteq<1,1,1>(strm_out_V_full_n.read(), ap_const_logic_0));
}

void dut_backproj::thread_ap_sig_157() {
    ap_sig_157 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(5, 5));
}

void dut_backproj::thread_ap_sig_186() {
    ap_sig_186 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(7, 7));
}

void dut_backproj::thread_ap_sig_212() {
    ap_sig_212 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(8, 8));
}

void dut_backproj::thread_ap_sig_26() {
    ap_sig_26 = esl_seteq<1,1,1>(ap_CS_fsm.read().range(0, 0), ap_const_lv1_1);
}

void dut_backproj::thread_ap_sig_292() {
    ap_sig_292 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(6, 6));
}

void dut_backproj::thread_ap_sig_45() {
    ap_sig_45 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(2, 2));
}

void dut_backproj::thread_ap_sig_61() {
    ap_sig_61 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(4, 4));
}

void dut_backproj::thread_ap_sig_94() {
    ap_sig_94 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(1, 1));
}

void dut_backproj::thread_ap_sig_cseq_ST_pp0_stg0_fsm_2() {
    if (ap_sig_45.read()) {
        ap_sig_cseq_ST_pp0_stg0_fsm_2 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_pp0_stg0_fsm_2 = ap_const_logic_0;
    }
}

void dut_backproj::thread_ap_sig_cseq_ST_pp1_stg0_fsm_3() {
    if (ap_sig_115.read()) {
        ap_sig_cseq_ST_pp1_stg0_fsm_3 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_pp1_stg0_fsm_3 = ap_const_logic_0;
    }
}

void dut_backproj::thread_ap_sig_cseq_ST_pp1_stg1_fsm_4() {
    if (ap_sig_61.read()) {
        ap_sig_cseq_ST_pp1_stg1_fsm_4 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_pp1_stg1_fsm_4 = ap_const_logic_0;
    }
}

void dut_backproj::thread_ap_sig_cseq_ST_pp1_stg2_fsm_5() {
    if (ap_sig_157.read()) {
        ap_sig_cseq_ST_pp1_stg2_fsm_5 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_pp1_stg2_fsm_5 = ap_const_logic_0;
    }
}

void dut_backproj::thread_ap_sig_cseq_ST_pp1_stg3_fsm_6() {
    if (ap_sig_292.read()) {
        ap_sig_cseq_ST_pp1_stg3_fsm_6 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_pp1_stg3_fsm_6 = ap_const_logic_0;
    }
}

void dut_backproj::thread_ap_sig_cseq_ST_pp1_stg4_fsm_7() {
    if (ap_sig_186.read()) {
        ap_sig_cseq_ST_pp1_stg4_fsm_7 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_pp1_stg4_fsm_7 = ap_const_logic_0;
    }
}

void dut_backproj::thread_ap_sig_cseq_ST_st17_fsm_8() {
    if (ap_sig_212.read()) {
        ap_sig_cseq_ST_st17_fsm_8 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st17_fsm_8 = ap_const_logic_0;
    }
}

void dut_backproj::thread_ap_sig_cseq_ST_st1_fsm_0() {
    if (ap_sig_26.read()) {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    }
}

void dut_backproj::thread_ap_sig_cseq_ST_st2_fsm_1() {
    if (ap_sig_94.read()) {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_0;
    }
}

void dut_backproj::thread_exitcond7_fu_187_p2() {
    exitcond7_fu_187_p2 = (!m_phi_fu_131_p4.read().is_01() || !ap_const_lv10_310.is_01())? sc_lv<1>(): sc_lv<1>(m_phi_fu_131_p4.read() == ap_const_lv10_310);
}

void dut_backproj::thread_exitcond8_fu_175_p2() {
    exitcond8_fu_175_p2 = (!i_reg_116.read().is_01() || !ap_const_lv4_A.is_01())? sc_lv<1>(): sc_lv<1>(i_reg_116.read() == ap_const_lv4_A);
}

void dut_backproj::thread_exitcond_flatten_fu_204_p2() {
    exitcond_flatten_fu_204_p2 = (!indvar_flatten_phi_fu_143_p4.read().is_01() || !ap_const_lv17_13240.is_01())? sc_lv<1>(): sc_lv<1>(indvar_flatten_phi_fu_143_p4.read() == ap_const_lv17_13240);
}

void dut_backproj::thread_exitcond_fu_216_p2() {
    exitcond_fu_216_p2 = (!k_phi_fu_154_p4.read().is_01() || !ap_const_lv10_310.is_01())? sc_lv<1>(): sc_lv<1>(k_phi_fu_154_p4.read() == ap_const_lv10_310);
}

void dut_backproj::thread_grp_fu_161_ce() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp1_stg0_fsm_3.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp1_stg1_fsm_4.read()) && 
          !((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it0.read()) && 
  ap_sig_130.read()) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it2.read()) && 
  ap_sig_134.read()))) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp1_stg2_fsm_5.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp1_stg4_fsm_7.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp1_stg3_fsm_6.read()))) {
        grp_fu_161_ce = ap_const_logic_1;
    } else {
        grp_fu_161_ce = ap_const_logic_0;
    }
}

void dut_backproj::thread_grp_fu_161_p0() {
    grp_fu_161_p0 = (!tmp_8_reg_307.read()[0].is_01())? sc_lv<32>(): ((tmp_8_reg_307.read()[0].to_bool())? ap_const_lv32_0: tmp_fu_76.read());
}

void dut_backproj::thread_grp_fu_165_ce() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp1_stg0_fsm_3.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp1_stg2_fsm_5.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp1_stg4_fsm_7.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp1_stg3_fsm_6.read()))) {
        grp_fu_165_ce = ap_const_logic_1;
    } else {
        grp_fu_165_ce = ap_const_logic_0;
    }
}

void dut_backproj::thread_i_2_fu_181_p2() {
    i_2_fu_181_p2 = (!i_reg_116.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(i_reg_116.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void dut_backproj::thread_indvar_flatten_next_fu_210_p2() {
    indvar_flatten_next_fu_210_p2 = (!indvar_flatten_phi_fu_143_p4.read().is_01() || !ap_const_lv17_1.is_01())? sc_lv<17>(): (sc_biguint<17>(indvar_flatten_phi_fu_143_p4.read()) + sc_biguint<17>(ap_const_lv17_1));
}

void dut_backproj::thread_indvar_flatten_phi_fu_143_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_flatten_reg_290.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp1_stg0_fsm_3.read()))) {
        indvar_flatten_phi_fu_143_p4 = indvar_flatten_next_reg_294.read();
    } else {
        indvar_flatten_phi_fu_143_p4 = indvar_flatten_reg_139.read();
    }
}

void dut_backproj::thread_k_1_fu_244_p2() {
    k_1_fu_244_p2 = (!k_mid2_reg_299.read().is_01() || !ap_const_lv10_1.is_01())? sc_lv<10>(): (sc_biguint<10>(k_mid2_reg_299.read()) + sc_biguint<10>(ap_const_lv10_1));
}

void dut_backproj::thread_k_mid2_fu_222_p3() {
    k_mid2_fu_222_p3 = (!exitcond_fu_216_p2.read()[0].is_01())? sc_lv<10>(): ((exitcond_fu_216_p2.read()[0].to_bool())? ap_const_lv10_0: k_phi_fu_154_p4.read());
}

void dut_backproj::thread_k_phi_fu_154_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_flatten_reg_290.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp1_stg0_fsm_3.read()))) {
        k_phi_fu_154_p4 = k_1_reg_326.read();
    } else {
        k_phi_fu_154_p4 = k_reg_150.read();
    }
}

void dut_backproj::thread_m_2_fu_193_p2() {
    m_2_fu_193_p2 = (!m_phi_fu_131_p4.read().is_01() || !ap_const_lv10_1.is_01())? sc_lv<10>(): (sc_biguint<10>(m_phi_fu_131_p4.read()) + sc_biguint<10>(ap_const_lv10_1));
}

void dut_backproj::thread_m_phi_fu_131_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
         esl_seteq<1,1,1>(exitcond7_reg_281.read(), ap_const_lv1_0))) {
        m_phi_fu_131_p4 = m_2_reg_285.read();
    } else {
        m_phi_fu_131_p4 = m_reg_127.read();
    }
}

void dut_backproj::thread_strm_in_V_blk_n() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
          esl_seteq<1,1,1>(exitcond7_reg_281.read(), ap_const_lv1_0)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp1_stg1_fsm_4.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it0.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_flatten_reg_290.read())))) {
        strm_in_V_blk_n = strm_in_V_empty_n.read();
    } else {
        strm_in_V_blk_n = ap_const_logic_1;
    }
}

void dut_backproj::thread_strm_in_V_read() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp1_stg1_fsm_4.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it0.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_flatten_reg_290.read()) && 
          !((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it0.read()) && 
  ap_sig_130.read()) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it2.read()) && 
  ap_sig_134.read()))) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp0_stg0_fsm_2.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && 
          esl_seteq<1,1,1>(exitcond7_reg_281.read(), ap_const_lv1_0) && 
          !(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && ap_sig_101.read())))) {
        strm_in_V_read = ap_const_logic_1;
    } else {
        strm_in_V_read = ap_const_logic_0;
    }
}

void dut_backproj::thread_strm_out_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp1_stg1_fsm_4.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it2.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_tmp_2_reg_322_pp1_iter1.read()))) {
        strm_out_V_blk_n = strm_out_V_full_n.read();
    } else {
        strm_out_V_blk_n = ap_const_logic_1;
    }
}

void dut_backproj::thread_strm_out_V_din() {
    strm_out_V_din = tmp_172_reg_346.read();
}

void dut_backproj::thread_strm_out_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp1_stg1_fsm_4.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it2.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, ap_reg_ppstg_tmp_2_reg_322_pp1_iter1.read()) && 
         !((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it0.read()) && 
  ap_sig_130.read()) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it2.read()) && 
  ap_sig_134.read())))) {
        strm_out_V_write = ap_const_logic_1;
    } else {
        strm_out_V_write = ap_const_logic_0;
    }
}

void dut_backproj::thread_tmp_2_fu_239_p2() {
    tmp_2_fu_239_p2 = (!k_mid2_reg_299.read().is_01() || !ap_const_lv10_30F.is_01())? sc_lv<1>(): sc_lv<1>(k_mid2_reg_299.read() == ap_const_lv10_30F);
}

void dut_backproj::thread_tmp_8_fu_230_p2() {
    tmp_8_fu_230_p2 = (!k_mid2_reg_299.read().is_01() || !ap_const_lv10_0.is_01())? sc_lv<1>(): sc_lv<1>(k_mid2_reg_299.read() == ap_const_lv10_0);
}

void dut_backproj::thread_tmp_9_fu_235_p1() {
    tmp_9_fu_235_p1 = esl_zext<64,10>(k_mid2_reg_299.read());
}

void dut_backproj::thread_tmp_s_fu_199_p1() {
    tmp_s_fu_199_p1 = esl_zext<64,10>(m_reg_127.read());
}

void dut_backproj::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if (!esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) {
                ap_NS_fsm = ap_ST_st2_fsm_1;
            } else {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            }
            break;
        case 2 : 
            if (!esl_seteq<1,1,1>(ap_const_lv1_0, exitcond8_fu_175_p2.read())) {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            } else {
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_2;
            }
            break;
        case 4 : 
            if (!(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && ap_sig_101.read()) && !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond7_fu_187_p2.read()))) {
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_2;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it0.read()) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp0_it1.read()) && ap_sig_101.read()) && !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond7_fu_187_p2.read()))) {
                ap_NS_fsm = ap_ST_pp1_stg0_fsm_3;
            } else {
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_2;
            }
            break;
        case 8 : 
            if (!(esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it0.read()) && !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_flatten_fu_204_p2.read()) && !esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it1.read()))) {
                ap_NS_fsm = ap_ST_pp1_stg1_fsm_4;
            } else {
                ap_NS_fsm = ap_ST_st17_fsm_8;
            }
            break;
        case 16 : 
            if ((!((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it0.read()) && 
  ap_sig_130.read()) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it2.read()) && 
  ap_sig_134.read())) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp1_stg1_fsm_4.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it2.read()) && !((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it0.read()) && 
  ap_sig_130.read()) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it2.read()) && 
  ap_sig_134.read())) && !esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it1.read())))) {
                ap_NS_fsm = ap_ST_pp1_stg2_fsm_5;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_pp1_stg1_fsm_4.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it2.read()) && !((esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it0.read()) && 
  ap_sig_130.read()) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it2.read()) && 
  ap_sig_134.read())) && !esl_seteq<1,1,1>(ap_const_logic_1, ap_reg_ppiten_pp1_it1.read()))) {
                ap_NS_fsm = ap_ST_st17_fsm_8;
            } else {
                ap_NS_fsm = ap_ST_pp1_stg1_fsm_4;
            }
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_pp1_stg3_fsm_6;
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_pp1_stg4_fsm_7;
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_pp1_stg0_fsm_3;
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_st2_fsm_1;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<9>) ("XXXXXXXXX");
            break;
    }
}

}

