// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.2
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "dut_rank.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic dut_rank::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic dut_rank::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<16> dut_rank::ap_ST_st1_fsm_0 = "1";
const sc_lv<16> dut_rank::ap_ST_st2_fsm_1 = "10";
const sc_lv<16> dut_rank::ap_ST_st3_fsm_2 = "100";
const sc_lv<16> dut_rank::ap_ST_st4_fsm_3 = "1000";
const sc_lv<16> dut_rank::ap_ST_st5_fsm_4 = "10000";
const sc_lv<16> dut_rank::ap_ST_st6_fsm_5 = "100000";
const sc_lv<16> dut_rank::ap_ST_st7_fsm_6 = "1000000";
const sc_lv<16> dut_rank::ap_ST_st8_fsm_7 = "10000000";
const sc_lv<16> dut_rank::ap_ST_st9_fsm_8 = "100000000";
const sc_lv<16> dut_rank::ap_ST_st10_fsm_9 = "1000000000";
const sc_lv<16> dut_rank::ap_ST_st11_fsm_10 = "10000000000";
const sc_lv<16> dut_rank::ap_ST_st12_fsm_11 = "100000000000";
const sc_lv<16> dut_rank::ap_ST_st13_fsm_12 = "1000000000000";
const sc_lv<16> dut_rank::ap_ST_st14_fsm_13 = "10000000000000";
const sc_lv<16> dut_rank::ap_ST_st15_fsm_14 = "100000000000000";
const sc_lv<16> dut_rank::ap_ST_st16_fsm_15 = "1000000000000000";
const sc_lv<32> dut_rank::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> dut_rank::ap_const_lv1_1 = "1";
const sc_lv<32> dut_rank::ap_const_lv32_2 = "10";
const sc_lv<1> dut_rank::ap_const_lv1_0 = "0";
const sc_lv<32> dut_rank::ap_const_lv32_3 = "11";
const sc_lv<32> dut_rank::ap_const_lv32_4 = "100";
const sc_lv<32> dut_rank::ap_const_lv32_5 = "101";
const sc_lv<32> dut_rank::ap_const_lv32_8 = "1000";
const sc_lv<32> dut_rank::ap_const_lv32_A = "1010";
const sc_lv<32> dut_rank::ap_const_lv32_B = "1011";
const sc_lv<32> dut_rank::ap_const_lv32_C = "1100";
const sc_lv<32> dut_rank::ap_const_lv32_1 = "1";
const sc_lv<32> dut_rank::ap_const_lv32_9 = "1001";
const sc_lv<10> dut_rank::ap_const_lv10_0 = "0000000000";
const sc_lv<4> dut_rank::ap_const_lv4_0 = "0000";
const sc_lv<13> dut_rank::ap_const_lv13_0 = "0000000000000";
const sc_lv<32> dut_rank::ap_const_lv32_F = "1111";
const sc_lv<20> dut_rank::ap_const_lv20_0 = "00000000000000000000";
const sc_lv<32> dut_rank::ap_const_lv32_6 = "110";
const sc_lv<32> dut_rank::ap_const_lv32_7 = "111";
const sc_lv<32> dut_rank::ap_const_lv32_D = "1101";
const sc_lv<32> dut_rank::ap_const_lv32_E = "1110";
const sc_lv<10> dut_rank::ap_const_lv10_30F = "1100001111";
const sc_lv<10> dut_rank::ap_const_lv10_1 = "1";
const sc_lv<32> dut_rank::ap_const_lv32_17 = "10111";
const sc_lv<32> dut_rank::ap_const_lv32_1E = "11110";
const sc_lv<8> dut_rank::ap_const_lv8_FF = "11111111";
const sc_lv<23> dut_rank::ap_const_lv23_0 = "00000000000000000000000";
const sc_lv<13> dut_rank::ap_const_lv13_310 = "1100010000";
const sc_lv<4> dut_rank::ap_const_lv4_A = "1010";
const sc_lv<4> dut_rank::ap_const_lv4_1 = "1";
const sc_lv<10> dut_rank::ap_const_lv10_310 = "1100010000";
const sc_lv<20> dut_rank::ap_const_lv20_310 = "1100010000";
const sc_lv<21> dut_rank::ap_const_lv21_311 = "1100010001";
const sc_lv<5> dut_rank::ap_const_lv5_4 = "100";

dut_rank::dut_rank(sc_module_name name) : sc_module(name), mVcdFile(0) {
    dut_fcmp_32ns_32ns_1_1_U40 = new dut_fcmp_32ns_32ns_1_1<1,1,32,32,1>("dut_fcmp_32ns_32ns_1_1_U40");
    dut_fcmp_32ns_32ns_1_1_U40->din0(S_load_reg_475);
    dut_fcmp_32ns_32ns_1_1_U40->din1(S_load_1_reg_481);
    dut_fcmp_32ns_32ns_1_1_U40->opcode(ap_var_for_const0);
    dut_fcmp_32ns_32ns_1_1_U40->dout(tmp_38_fu_209_p2);
    dut_mul_mul_11ns_21s_21_1_U41 = new dut_mul_mul_11ns_21s_21_1<1,1,11,21,21>("dut_mul_mul_11ns_21s_21_1_U41");
    dut_mul_mul_11ns_21s_21_1_U41->din0(tmp_40_fu_406_p0);
    dut_mul_mul_11ns_21s_21_1_U41->din1(tmp_30_reg_450);
    dut_mul_mul_11ns_21s_21_1_U41->dout(tmp_40_fu_406_p2);
    dut_mul_mul_11ns_21s_21_1_U42 = new dut_mul_mul_11ns_21s_21_1<1,1,11,21,21>("dut_mul_mul_11ns_21s_21_1_U42");
    dut_mul_mul_11ns_21s_21_1_U42->din0(tmp_34_fu_411_p0);
    dut_mul_mul_11ns_21s_21_1_U42->din1(tmp_29_reg_440);
    dut_mul_mul_11ns_21s_21_1_U42->dout(tmp_34_fu_411_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_PCA_sorted_idx_address0);
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );
    sensitive << ( PCA_sorted_idx_addr_1_reg_425 );
    sensitive << ( PCA_sorted_idx_addr_reg_503 );
    sensitive << ( ap_sig_cseq_ST_st12_fsm_11 );
    sensitive << ( ap_sig_cseq_ST_st10_fsm_9 );
    sensitive << ( tmp_i_fu_225_p1 );

    SC_METHOD(thread_PCA_sorted_idx_address1);
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );
    sensitive << ( PCA_sorted_idx_addr_2_reg_430 );
    sensitive << ( ap_sig_cseq_ST_st10_fsm_9 );
    sensitive << ( tmp_81_i_fu_230_p1 );

    SC_METHOD(thread_PCA_sorted_idx_ce0);
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );
    sensitive << ( ap_sig_cseq_ST_st12_fsm_11 );
    sensitive << ( ap_sig_cseq_ST_st10_fsm_9 );

    SC_METHOD(thread_PCA_sorted_idx_ce1);
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );
    sensitive << ( ap_sig_cseq_ST_st10_fsm_9 );

    SC_METHOD(thread_PCA_sorted_idx_d0);
    sensitive << ( PCA_sorted_idx_load_2_reg_445 );
    sensitive << ( ap_sig_cseq_ST_st10_fsm_9 );

    SC_METHOD(thread_PCA_sorted_idx_d1);
    sensitive << ( temp_reg_435 );
    sensitive << ( ap_sig_cseq_ST_st10_fsm_9 );

    SC_METHOD(thread_PCA_sorted_idx_we0);
    sensitive << ( ap_sig_cseq_ST_st10_fsm_9 );
    sensitive << ( tmp_39_fu_327_p2 );

    SC_METHOD(thread_PCA_sorted_idx_we1);
    sensitive << ( ap_sig_cseq_ST_st10_fsm_9 );
    sensitive << ( tmp_39_fu_327_p2 );

    SC_METHOD(thread_S_address0);
    sensitive << ( ap_sig_cseq_ST_st6_fsm_5 );
    sensitive << ( tmp_44_cast_fu_243_p1 );

    SC_METHOD(thread_S_address1);
    sensitive << ( ap_sig_cseq_ST_st6_fsm_5 );
    sensitive << ( tmp_45_cast_fu_247_p1 );

    SC_METHOD(thread_S_ce0);
    sensitive << ( ap_sig_cseq_ST_st6_fsm_5 );
    sensitive << ( ap_sig_cseq_ST_st9_fsm_8 );
    sensitive << ( ap_sig_cseq_ST_st7_fsm_6 );
    sensitive << ( ap_sig_cseq_ST_st8_fsm_7 );

    SC_METHOD(thread_S_ce1);
    sensitive << ( ap_sig_cseq_ST_st6_fsm_5 );
    sensitive << ( ap_sig_cseq_ST_st9_fsm_8 );
    sensitive << ( ap_sig_cseq_ST_st7_fsm_6 );
    sensitive << ( ap_sig_cseq_ST_st8_fsm_7 );

    SC_METHOD(thread_S_load_1_to_int_fu_268_p1);
    sensitive << ( S_load_1_reg_481 );

    SC_METHOD(thread_S_load_to_int_fu_251_p1);
    sensitive << ( S_load_reg_475 );

    SC_METHOD(thread_U_address0);
    sensitive << ( ap_sig_cseq_ST_st13_fsm_12 );
    sensitive << ( tmp_49_cast_fu_397_p1 );

    SC_METHOD(thread_U_ce0);
    sensitive << ( ap_sig_cseq_ST_st13_fsm_12 );
    sensitive << ( ap_sig_cseq_ST_st16_fsm_15 );
    sensitive << ( ap_sig_cseq_ST_st14_fsm_13 );
    sensitive << ( ap_sig_cseq_ST_st15_fsm_14 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );
    sensitive << ( ap_sig_cseq_ST_st11_fsm_10 );
    sensitive << ( exitcond1_fu_339_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_sig_cseq_ST_st1_fsm_0 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_sig_cseq_ST_st11_fsm_10 );
    sensitive << ( exitcond1_fu_339_p2 );

    SC_METHOD(thread_ap_sig_110);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_121);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_131);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_141);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_157);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_175);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_184);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_191);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_221);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_243);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_251);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_260);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_268);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_33);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_80);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_96);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_sig_cseq_ST_st10_fsm_9);
    sensitive << ( ap_sig_191 );

    SC_METHOD(thread_ap_sig_cseq_ST_st11_fsm_10);
    sensitive << ( ap_sig_141 );

    SC_METHOD(thread_ap_sig_cseq_ST_st12_fsm_11);
    sensitive << ( ap_sig_157 );

    SC_METHOD(thread_ap_sig_cseq_ST_st13_fsm_12);
    sensitive << ( ap_sig_175 );

    SC_METHOD(thread_ap_sig_cseq_ST_st14_fsm_13);
    sensitive << ( ap_sig_260 );

    SC_METHOD(thread_ap_sig_cseq_ST_st15_fsm_14);
    sensitive << ( ap_sig_268 );

    SC_METHOD(thread_ap_sig_cseq_ST_st16_fsm_15);
    sensitive << ( ap_sig_221 );

    SC_METHOD(thread_ap_sig_cseq_ST_st1_fsm_0);
    sensitive << ( ap_sig_33 );

    SC_METHOD(thread_ap_sig_cseq_ST_st2_fsm_1);
    sensitive << ( ap_sig_184 );

    SC_METHOD(thread_ap_sig_cseq_ST_st3_fsm_2);
    sensitive << ( ap_sig_80 );

    SC_METHOD(thread_ap_sig_cseq_ST_st4_fsm_3);
    sensitive << ( ap_sig_96 );

    SC_METHOD(thread_ap_sig_cseq_ST_st5_fsm_4);
    sensitive << ( ap_sig_110 );

    SC_METHOD(thread_ap_sig_cseq_ST_st6_fsm_5);
    sensitive << ( ap_sig_121 );

    SC_METHOD(thread_ap_sig_cseq_ST_st7_fsm_6);
    sensitive << ( ap_sig_243 );

    SC_METHOD(thread_ap_sig_cseq_ST_st8_fsm_7);
    sensitive << ( ap_sig_251 );

    SC_METHOD(thread_ap_sig_cseq_ST_st9_fsm_8);
    sensitive << ( ap_sig_131 );

    SC_METHOD(thread_exitcond1_fu_339_p2);
    sensitive << ( ap_sig_cseq_ST_st11_fsm_10 );
    sensitive << ( i_reg_164 );

    SC_METHOD(thread_exitcond_fu_360_p2);
    sensitive << ( ap_sig_cseq_ST_st12_fsm_11 );
    sensitive << ( j_reg_187 );

    SC_METHOD(thread_exitcond_i_fu_213_p2);
    sensitive << ( ap_sig_cseq_ST_st3_fsm_2 );
    sensitive << ( i_i_reg_151 );

    SC_METHOD(thread_i_1_fu_219_p2);
    sensitive << ( i_i_reg_151 );

    SC_METHOD(thread_i_2_fu_345_p2);
    sensitive << ( i_reg_164 );

    SC_METHOD(thread_j_1_fu_366_p2);
    sensitive << ( j_reg_187 );

    SC_METHOD(thread_next_mul2_fu_333_p2);
    sensitive << ( phi_mul1_reg_175 );

    SC_METHOD(thread_next_mul_fu_382_p2);
    sensitive << ( phi_mul_reg_198 );

    SC_METHOD(thread_notlhs3_fu_303_p2);
    sensitive << ( ap_sig_cseq_ST_st10_fsm_9 );
    sensitive << ( tmp_33_fu_271_p4 );

    SC_METHOD(thread_notlhs_fu_285_p2);
    sensitive << ( ap_sig_cseq_ST_st10_fsm_9 );
    sensitive << ( tmp_fu_254_p4 );

    SC_METHOD(thread_notrhs4_fu_309_p2);
    sensitive << ( ap_sig_cseq_ST_st10_fsm_9 );
    sensitive << ( tmp_32_fu_281_p1 );

    SC_METHOD(thread_notrhs_fu_291_p2);
    sensitive << ( ap_sig_cseq_ST_st10_fsm_9 );
    sensitive << ( tmp_31_fu_264_p1 );

    SC_METHOD(thread_phi_mul_cast_fu_356_p1);
    sensitive << ( phi_mul_reg_198 );

    SC_METHOD(thread_swap_i_phi_fu_139_p6);
    sensitive << ( swap_i_reg_134 );

    SC_METHOD(thread_tmp_29_fu_235_p1);
    sensitive << ( PCA_sorted_idx_q0 );

    SC_METHOD(thread_tmp_30_fu_239_p1);
    sensitive << ( PCA_sorted_idx_q1 );

    SC_METHOD(thread_tmp_31_fu_264_p1);
    sensitive << ( S_load_to_int_fu_251_p1 );

    SC_METHOD(thread_tmp_32_fu_281_p1);
    sensitive << ( S_load_1_to_int_fu_268_p1 );

    SC_METHOD(thread_tmp_33_fu_271_p4);
    sensitive << ( S_load_1_to_int_fu_268_p1 );

    SC_METHOD(thread_tmp_34_fu_411_p0);
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );

    SC_METHOD(thread_tmp_35_fu_297_p2);
    sensitive << ( notrhs_fu_291_p2 );
    sensitive << ( notlhs_fu_285_p2 );

    SC_METHOD(thread_tmp_36_fu_315_p2);
    sensitive << ( notrhs4_fu_309_p2 );
    sensitive << ( notlhs3_fu_303_p2 );

    SC_METHOD(thread_tmp_37_fu_321_p2);
    sensitive << ( tmp_35_fu_297_p2 );
    sensitive << ( tmp_36_fu_315_p2 );

    SC_METHOD(thread_tmp_39_fu_327_p2);
    sensitive << ( tmp_37_fu_321_p2 );
    sensitive << ( tmp_38_fu_209_p2 );

    SC_METHOD(thread_tmp_40_fu_406_p0);
    sensitive << ( ap_sig_cseq_ST_st5_fsm_4 );

    SC_METHOD(thread_tmp_41_cast_fu_372_p1);
    sensitive << ( j_reg_187 );

    SC_METHOD(thread_tmp_41_fu_388_p1);
    sensitive << ( PCA_sorted_idx_q0 );

    SC_METHOD(thread_tmp_42_fu_376_p2);
    sensitive << ( phi_mul1_reg_175 );
    sensitive << ( tmp_41_cast_fu_372_p1 );

    SC_METHOD(thread_tmp_43_fu_392_p2);
    sensitive << ( phi_mul_cast_reg_508 );
    sensitive << ( tmp_41_fu_388_p1 );

    SC_METHOD(thread_tmp_44_cast_fu_243_p1);
    sensitive << ( tmp_34_reg_455 );

    SC_METHOD(thread_tmp_45_cast_fu_247_p1);
    sensitive << ( tmp_40_reg_460 );

    SC_METHOD(thread_tmp_47_cast_fu_402_p1);
    sensitive << ( tmp_42_reg_521 );

    SC_METHOD(thread_tmp_49_cast_fu_397_p1);
    sensitive << ( tmp_43_fu_392_p2 );

    SC_METHOD(thread_tmp_81_i_fu_230_p1);
    sensitive << ( i_1_fu_219_p2 );

    SC_METHOD(thread_tmp_fu_254_p4);
    sensitive << ( S_load_to_int_fu_251_p1 );

    SC_METHOD(thread_tmp_i_fu_225_p1);
    sensitive << ( i_i_reg_151 );

    SC_METHOD(thread_tmp_s_fu_351_p1);
    sensitive << ( i_reg_164 );

    SC_METHOD(thread_tsf_mat_address0);
    sensitive << ( ap_sig_cseq_ST_st16_fsm_15 );
    sensitive << ( tmp_47_cast_fu_402_p1 );

    SC_METHOD(thread_tsf_mat_ce0);
    sensitive << ( ap_sig_cseq_ST_st16_fsm_15 );

    SC_METHOD(thread_tsf_mat_d0);
    sensitive << ( U_q0 );
    sensitive << ( ap_sig_cseq_ST_st16_fsm_15 );

    SC_METHOD(thread_tsf_mat_we0);
    sensitive << ( ap_sig_cseq_ST_st16_fsm_15 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( exitcond_i_fu_213_p2 );
    sensitive << ( exitcond1_fu_339_p2 );
    sensitive << ( exitcond_fu_360_p2 );
    sensitive << ( swap_i_phi_fu_139_p6 );

    SC_THREAD(thread_ap_var_for_const0);

    ap_CS_fsm = "0000000000000001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "dut_rank_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, PCA_sorted_idx_address0, "(port)PCA_sorted_idx_address0");
    sc_trace(mVcdFile, PCA_sorted_idx_ce0, "(port)PCA_sorted_idx_ce0");
    sc_trace(mVcdFile, PCA_sorted_idx_we0, "(port)PCA_sorted_idx_we0");
    sc_trace(mVcdFile, PCA_sorted_idx_d0, "(port)PCA_sorted_idx_d0");
    sc_trace(mVcdFile, PCA_sorted_idx_q0, "(port)PCA_sorted_idx_q0");
    sc_trace(mVcdFile, PCA_sorted_idx_address1, "(port)PCA_sorted_idx_address1");
    sc_trace(mVcdFile, PCA_sorted_idx_ce1, "(port)PCA_sorted_idx_ce1");
    sc_trace(mVcdFile, PCA_sorted_idx_we1, "(port)PCA_sorted_idx_we1");
    sc_trace(mVcdFile, PCA_sorted_idx_d1, "(port)PCA_sorted_idx_d1");
    sc_trace(mVcdFile, PCA_sorted_idx_q1, "(port)PCA_sorted_idx_q1");
    sc_trace(mVcdFile, tsf_mat_address0, "(port)tsf_mat_address0");
    sc_trace(mVcdFile, tsf_mat_ce0, "(port)tsf_mat_ce0");
    sc_trace(mVcdFile, tsf_mat_we0, "(port)tsf_mat_we0");
    sc_trace(mVcdFile, tsf_mat_d0, "(port)tsf_mat_d0");
    sc_trace(mVcdFile, S_address0, "(port)S_address0");
    sc_trace(mVcdFile, S_ce0, "(port)S_ce0");
    sc_trace(mVcdFile, S_q0, "(port)S_q0");
    sc_trace(mVcdFile, S_address1, "(port)S_address1");
    sc_trace(mVcdFile, S_ce1, "(port)S_ce1");
    sc_trace(mVcdFile, S_q1, "(port)S_q1");
    sc_trace(mVcdFile, U_address0, "(port)U_address0");
    sc_trace(mVcdFile, U_ce0, "(port)U_ce0");
    sc_trace(mVcdFile, U_q0, "(port)U_q0");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st1_fsm_0, "ap_sig_cseq_ST_st1_fsm_0");
    sc_trace(mVcdFile, ap_sig_33, "ap_sig_33");
    sc_trace(mVcdFile, i_1_fu_219_p2, "i_1_fu_219_p2");
    sc_trace(mVcdFile, i_1_reg_419, "i_1_reg_419");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st3_fsm_2, "ap_sig_cseq_ST_st3_fsm_2");
    sc_trace(mVcdFile, ap_sig_80, "ap_sig_80");
    sc_trace(mVcdFile, PCA_sorted_idx_addr_1_reg_425, "PCA_sorted_idx_addr_1_reg_425");
    sc_trace(mVcdFile, exitcond_i_fu_213_p2, "exitcond_i_fu_213_p2");
    sc_trace(mVcdFile, PCA_sorted_idx_addr_2_reg_430, "PCA_sorted_idx_addr_2_reg_430");
    sc_trace(mVcdFile, temp_reg_435, "temp_reg_435");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st4_fsm_3, "ap_sig_cseq_ST_st4_fsm_3");
    sc_trace(mVcdFile, ap_sig_96, "ap_sig_96");
    sc_trace(mVcdFile, tmp_29_fu_235_p1, "tmp_29_fu_235_p1");
    sc_trace(mVcdFile, tmp_29_reg_440, "tmp_29_reg_440");
    sc_trace(mVcdFile, PCA_sorted_idx_load_2_reg_445, "PCA_sorted_idx_load_2_reg_445");
    sc_trace(mVcdFile, tmp_30_fu_239_p1, "tmp_30_fu_239_p1");
    sc_trace(mVcdFile, tmp_30_reg_450, "tmp_30_reg_450");
    sc_trace(mVcdFile, tmp_34_fu_411_p2, "tmp_34_fu_411_p2");
    sc_trace(mVcdFile, tmp_34_reg_455, "tmp_34_reg_455");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st5_fsm_4, "ap_sig_cseq_ST_st5_fsm_4");
    sc_trace(mVcdFile, ap_sig_110, "ap_sig_110");
    sc_trace(mVcdFile, tmp_40_fu_406_p2, "tmp_40_fu_406_p2");
    sc_trace(mVcdFile, tmp_40_reg_460, "tmp_40_reg_460");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st6_fsm_5, "ap_sig_cseq_ST_st6_fsm_5");
    sc_trace(mVcdFile, ap_sig_121, "ap_sig_121");
    sc_trace(mVcdFile, S_load_reg_475, "S_load_reg_475");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st9_fsm_8, "ap_sig_cseq_ST_st9_fsm_8");
    sc_trace(mVcdFile, ap_sig_131, "ap_sig_131");
    sc_trace(mVcdFile, S_load_1_reg_481, "S_load_1_reg_481");
    sc_trace(mVcdFile, next_mul2_fu_333_p2, "next_mul2_fu_333_p2");
    sc_trace(mVcdFile, next_mul2_reg_490, "next_mul2_reg_490");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st11_fsm_10, "ap_sig_cseq_ST_st11_fsm_10");
    sc_trace(mVcdFile, ap_sig_141, "ap_sig_141");
    sc_trace(mVcdFile, i_2_fu_345_p2, "i_2_fu_345_p2");
    sc_trace(mVcdFile, i_2_reg_498, "i_2_reg_498");
    sc_trace(mVcdFile, PCA_sorted_idx_addr_reg_503, "PCA_sorted_idx_addr_reg_503");
    sc_trace(mVcdFile, exitcond1_fu_339_p2, "exitcond1_fu_339_p2");
    sc_trace(mVcdFile, phi_mul_cast_fu_356_p1, "phi_mul_cast_fu_356_p1");
    sc_trace(mVcdFile, phi_mul_cast_reg_508, "phi_mul_cast_reg_508");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st12_fsm_11, "ap_sig_cseq_ST_st12_fsm_11");
    sc_trace(mVcdFile, ap_sig_157, "ap_sig_157");
    sc_trace(mVcdFile, j_1_fu_366_p2, "j_1_fu_366_p2");
    sc_trace(mVcdFile, j_1_reg_516, "j_1_reg_516");
    sc_trace(mVcdFile, tmp_42_fu_376_p2, "tmp_42_fu_376_p2");
    sc_trace(mVcdFile, tmp_42_reg_521, "tmp_42_reg_521");
    sc_trace(mVcdFile, exitcond_fu_360_p2, "exitcond_fu_360_p2");
    sc_trace(mVcdFile, next_mul_fu_382_p2, "next_mul_fu_382_p2");
    sc_trace(mVcdFile, next_mul_reg_526, "next_mul_reg_526");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st13_fsm_12, "ap_sig_cseq_ST_st13_fsm_12");
    sc_trace(mVcdFile, ap_sig_175, "ap_sig_175");
    sc_trace(mVcdFile, swap_i_phi_fu_139_p6, "swap_i_phi_fu_139_p6");
    sc_trace(mVcdFile, swap_i_reg_134, "swap_i_reg_134");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st2_fsm_1, "ap_sig_cseq_ST_st2_fsm_1");
    sc_trace(mVcdFile, ap_sig_184, "ap_sig_184");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st10_fsm_9, "ap_sig_cseq_ST_st10_fsm_9");
    sc_trace(mVcdFile, ap_sig_191, "ap_sig_191");
    sc_trace(mVcdFile, tmp_39_fu_327_p2, "tmp_39_fu_327_p2");
    sc_trace(mVcdFile, i_i_reg_151, "i_i_reg_151");
    sc_trace(mVcdFile, i_reg_164, "i_reg_164");
    sc_trace(mVcdFile, phi_mul1_reg_175, "phi_mul1_reg_175");
    sc_trace(mVcdFile, j_reg_187, "j_reg_187");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st16_fsm_15, "ap_sig_cseq_ST_st16_fsm_15");
    sc_trace(mVcdFile, ap_sig_221, "ap_sig_221");
    sc_trace(mVcdFile, phi_mul_reg_198, "phi_mul_reg_198");
    sc_trace(mVcdFile, tmp_i_fu_225_p1, "tmp_i_fu_225_p1");
    sc_trace(mVcdFile, tmp_81_i_fu_230_p1, "tmp_81_i_fu_230_p1");
    sc_trace(mVcdFile, tmp_44_cast_fu_243_p1, "tmp_44_cast_fu_243_p1");
    sc_trace(mVcdFile, tmp_45_cast_fu_247_p1, "tmp_45_cast_fu_247_p1");
    sc_trace(mVcdFile, tmp_s_fu_351_p1, "tmp_s_fu_351_p1");
    sc_trace(mVcdFile, tmp_49_cast_fu_397_p1, "tmp_49_cast_fu_397_p1");
    sc_trace(mVcdFile, tmp_47_cast_fu_402_p1, "tmp_47_cast_fu_402_p1");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st7_fsm_6, "ap_sig_cseq_ST_st7_fsm_6");
    sc_trace(mVcdFile, ap_sig_243, "ap_sig_243");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st8_fsm_7, "ap_sig_cseq_ST_st8_fsm_7");
    sc_trace(mVcdFile, ap_sig_251, "ap_sig_251");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st14_fsm_13, "ap_sig_cseq_ST_st14_fsm_13");
    sc_trace(mVcdFile, ap_sig_260, "ap_sig_260");
    sc_trace(mVcdFile, ap_sig_cseq_ST_st15_fsm_14, "ap_sig_cseq_ST_st15_fsm_14");
    sc_trace(mVcdFile, ap_sig_268, "ap_sig_268");
    sc_trace(mVcdFile, S_load_to_int_fu_251_p1, "S_load_to_int_fu_251_p1");
    sc_trace(mVcdFile, S_load_1_to_int_fu_268_p1, "S_load_1_to_int_fu_268_p1");
    sc_trace(mVcdFile, tmp_fu_254_p4, "tmp_fu_254_p4");
    sc_trace(mVcdFile, tmp_31_fu_264_p1, "tmp_31_fu_264_p1");
    sc_trace(mVcdFile, notrhs_fu_291_p2, "notrhs_fu_291_p2");
    sc_trace(mVcdFile, notlhs_fu_285_p2, "notlhs_fu_285_p2");
    sc_trace(mVcdFile, tmp_33_fu_271_p4, "tmp_33_fu_271_p4");
    sc_trace(mVcdFile, tmp_32_fu_281_p1, "tmp_32_fu_281_p1");
    sc_trace(mVcdFile, notrhs4_fu_309_p2, "notrhs4_fu_309_p2");
    sc_trace(mVcdFile, notlhs3_fu_303_p2, "notlhs3_fu_303_p2");
    sc_trace(mVcdFile, tmp_35_fu_297_p2, "tmp_35_fu_297_p2");
    sc_trace(mVcdFile, tmp_36_fu_315_p2, "tmp_36_fu_315_p2");
    sc_trace(mVcdFile, tmp_37_fu_321_p2, "tmp_37_fu_321_p2");
    sc_trace(mVcdFile, tmp_38_fu_209_p2, "tmp_38_fu_209_p2");
    sc_trace(mVcdFile, tmp_41_cast_fu_372_p1, "tmp_41_cast_fu_372_p1");
    sc_trace(mVcdFile, tmp_41_fu_388_p1, "tmp_41_fu_388_p1");
    sc_trace(mVcdFile, tmp_43_fu_392_p2, "tmp_43_fu_392_p2");
    sc_trace(mVcdFile, tmp_40_fu_406_p0, "tmp_40_fu_406_p0");
    sc_trace(mVcdFile, tmp_34_fu_411_p0, "tmp_34_fu_411_p0");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

dut_rank::~dut_rank() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete dut_fcmp_32ns_32ns_1_1_U40;
    delete dut_mul_mul_11ns_21s_21_1_U41;
    delete dut_mul_mul_11ns_21s_21_1_U42;
}

void dut_rank::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_lv5_4;
}

void dut_rank::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_st1_fsm_0;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st10_fsm_9.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_39_fu_327_p2.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st10_fsm_9.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_39_fu_327_p2.read())))) {
        i_i_reg_151 = i_1_reg_419.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        i_i_reg_151 = ap_const_lv10_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st12_fsm_11.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_360_p2.read()))) {
        i_reg_164 = i_2_reg_498.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, swap_i_phi_fu_139_p6.read()) && 
                !esl_seteq<1,1,1>(exitcond_i_fu_213_p2.read(), ap_const_lv1_0))) {
        i_reg_164 = ap_const_lv4_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st11_fsm_10.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_339_p2.read()))) {
        j_reg_187 = ap_const_lv10_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st16_fsm_15.read())) {
        j_reg_187 = j_1_reg_516.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st12_fsm_11.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_360_p2.read()))) {
        phi_mul1_reg_175 = next_mul2_reg_490.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, swap_i_phi_fu_139_p6.read()) && 
                !esl_seteq<1,1,1>(exitcond_i_fu_213_p2.read(), ap_const_lv1_0))) {
        phi_mul1_reg_175 = ap_const_lv13_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st11_fsm_10.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_339_p2.read()))) {
        phi_mul_reg_198 = ap_const_lv20_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st16_fsm_15.read())) {
        phi_mul_reg_198 = next_mul_reg_526.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st10_fsm_9.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, tmp_39_fu_327_p2.read()))) {
        swap_i_reg_134 = swap_i_reg_134.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st10_fsm_9.read()) && 
                !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_39_fu_327_p2.read()))) {
        swap_i_reg_134 = ap_const_lv1_1;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st2_fsm_1.read())) {
        swap_i_reg_134 = ap_const_lv1_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()) && esl_seteq<1,1,1>(exitcond_i_fu_213_p2.read(), ap_const_lv1_0))) {
        PCA_sorted_idx_addr_1_reg_425 =  (sc_lv<10>) (tmp_i_fu_225_p1.read());
        PCA_sorted_idx_addr_2_reg_430 =  (sc_lv<10>) (tmp_81_i_fu_230_p1.read());
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st11_fsm_10.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_339_p2.read()))) {
        PCA_sorted_idx_addr_reg_503 =  (sc_lv<10>) (tmp_s_fu_351_p1.read());
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st4_fsm_3.read())) {
        PCA_sorted_idx_load_2_reg_445 = PCA_sorted_idx_q1.read();
        temp_reg_435 = PCA_sorted_idx_q0.read();
        tmp_29_reg_440 = tmp_29_fu_235_p1.read();
        tmp_30_reg_450 = tmp_30_fu_239_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st9_fsm_8.read())) {
        S_load_1_reg_481 = S_q1.read();
        S_load_reg_475 = S_q0.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read())) {
        i_1_reg_419 = i_1_fu_219_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st11_fsm_10.read())) {
        i_2_reg_498 = i_2_fu_345_p2.read();
        next_mul2_reg_490 = next_mul2_fu_333_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st12_fsm_11.read())) {
        j_1_reg_516 = j_1_fu_366_p2.read();
        phi_mul_cast_reg_508 = phi_mul_cast_fu_356_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st12_fsm_11.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_360_p2.read()))) {
        next_mul_reg_526 = next_mul_fu_382_p2.read();
        tmp_42_reg_521 = tmp_42_fu_376_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st5_fsm_4.read())) {
        tmp_34_reg_455 = tmp_34_fu_411_p2.read();
        tmp_40_reg_460 = tmp_40_fu_406_p2.read();
    }
}

void dut_rank::thread_PCA_sorted_idx_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st10_fsm_9.read())) {
        PCA_sorted_idx_address0 = PCA_sorted_idx_addr_1_reg_425.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st12_fsm_11.read())) {
        PCA_sorted_idx_address0 = PCA_sorted_idx_addr_reg_503.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read())) {
        PCA_sorted_idx_address0 =  (sc_lv<10>) (tmp_i_fu_225_p1.read());
    } else {
        PCA_sorted_idx_address0 = "XXXXXXXXXX";
    }
}

void dut_rank::thread_PCA_sorted_idx_address1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st10_fsm_9.read())) {
        PCA_sorted_idx_address1 = PCA_sorted_idx_addr_2_reg_430.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read())) {
        PCA_sorted_idx_address1 =  (sc_lv<10>) (tmp_81_i_fu_230_p1.read());
    } else {
        PCA_sorted_idx_address1 = "XXXXXXXXXX";
    }
}

void dut_rank::thread_PCA_sorted_idx_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st12_fsm_11.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st10_fsm_9.read()))) {
        PCA_sorted_idx_ce0 = ap_const_logic_1;
    } else {
        PCA_sorted_idx_ce0 = ap_const_logic_0;
    }
}

void dut_rank::thread_PCA_sorted_idx_ce1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st3_fsm_2.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st10_fsm_9.read()))) {
        PCA_sorted_idx_ce1 = ap_const_logic_1;
    } else {
        PCA_sorted_idx_ce1 = ap_const_logic_0;
    }
}

void dut_rank::thread_PCA_sorted_idx_d0() {
    PCA_sorted_idx_d0 = PCA_sorted_idx_load_2_reg_445.read();
}

void dut_rank::thread_PCA_sorted_idx_d1() {
    PCA_sorted_idx_d1 = temp_reg_435.read();
}

void dut_rank::thread_PCA_sorted_idx_we0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st10_fsm_9.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_39_fu_327_p2.read())))) {
        PCA_sorted_idx_we0 = ap_const_logic_1;
    } else {
        PCA_sorted_idx_we0 = ap_const_logic_0;
    }
}

void dut_rank::thread_PCA_sorted_idx_we1() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st10_fsm_9.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_39_fu_327_p2.read())))) {
        PCA_sorted_idx_we1 = ap_const_logic_1;
    } else {
        PCA_sorted_idx_we1 = ap_const_logic_0;
    }
}

void dut_rank::thread_S_address0() {
    S_address0 =  (sc_lv<20>) (tmp_44_cast_fu_243_p1.read());
}

void dut_rank::thread_S_address1() {
    S_address1 =  (sc_lv<20>) (tmp_45_cast_fu_247_p1.read());
}

void dut_rank::thread_S_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st9_fsm_8.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st8_fsm_7.read()))) {
        S_ce0 = ap_const_logic_1;
    } else {
        S_ce0 = ap_const_logic_0;
    }
}

void dut_rank::thread_S_ce1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st6_fsm_5.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st9_fsm_8.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st7_fsm_6.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st8_fsm_7.read()))) {
        S_ce1 = ap_const_logic_1;
    } else {
        S_ce1 = ap_const_logic_0;
    }
}

void dut_rank::thread_S_load_1_to_int_fu_268_p1() {
    S_load_1_to_int_fu_268_p1 = S_load_1_reg_481.read();
}

void dut_rank::thread_S_load_to_int_fu_251_p1() {
    S_load_to_int_fu_251_p1 = S_load_reg_475.read();
}

void dut_rank::thread_U_address0() {
    U_address0 =  (sc_lv<20>) (tmp_49_cast_fu_397_p1.read());
}

void dut_rank::thread_U_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st13_fsm_12.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st16_fsm_15.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st14_fsm_13.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st15_fsm_14.read()))) {
        U_ce0 = ap_const_logic_1;
    } else {
        U_ce0 = ap_const_logic_0;
    }
}

void dut_rank::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st11_fsm_10.read()) && 
          !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_339_p2.read())))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void dut_rank::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st1_fsm_0.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void dut_rank::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st11_fsm_10.read()) && 
         !esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_339_p2.read()))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void dut_rank::thread_ap_sig_110() {
    ap_sig_110 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(4, 4));
}

void dut_rank::thread_ap_sig_121() {
    ap_sig_121 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(5, 5));
}

void dut_rank::thread_ap_sig_131() {
    ap_sig_131 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(8, 8));
}

void dut_rank::thread_ap_sig_141() {
    ap_sig_141 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(10, 10));
}

void dut_rank::thread_ap_sig_157() {
    ap_sig_157 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(11, 11));
}

void dut_rank::thread_ap_sig_175() {
    ap_sig_175 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(12, 12));
}

void dut_rank::thread_ap_sig_184() {
    ap_sig_184 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(1, 1));
}

void dut_rank::thread_ap_sig_191() {
    ap_sig_191 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(9, 9));
}

void dut_rank::thread_ap_sig_221() {
    ap_sig_221 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(15, 15));
}

void dut_rank::thread_ap_sig_243() {
    ap_sig_243 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(6, 6));
}

void dut_rank::thread_ap_sig_251() {
    ap_sig_251 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(7, 7));
}

void dut_rank::thread_ap_sig_260() {
    ap_sig_260 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(13, 13));
}

void dut_rank::thread_ap_sig_268() {
    ap_sig_268 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(14, 14));
}

void dut_rank::thread_ap_sig_33() {
    ap_sig_33 = esl_seteq<1,1,1>(ap_CS_fsm.read().range(0, 0), ap_const_lv1_1);
}

void dut_rank::thread_ap_sig_80() {
    ap_sig_80 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(2, 2));
}

void dut_rank::thread_ap_sig_96() {
    ap_sig_96 = esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm.read().range(3, 3));
}

void dut_rank::thread_ap_sig_cseq_ST_st10_fsm_9() {
    if (ap_sig_191.read()) {
        ap_sig_cseq_ST_st10_fsm_9 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st10_fsm_9 = ap_const_logic_0;
    }
}

void dut_rank::thread_ap_sig_cseq_ST_st11_fsm_10() {
    if (ap_sig_141.read()) {
        ap_sig_cseq_ST_st11_fsm_10 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st11_fsm_10 = ap_const_logic_0;
    }
}

void dut_rank::thread_ap_sig_cseq_ST_st12_fsm_11() {
    if (ap_sig_157.read()) {
        ap_sig_cseq_ST_st12_fsm_11 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st12_fsm_11 = ap_const_logic_0;
    }
}

void dut_rank::thread_ap_sig_cseq_ST_st13_fsm_12() {
    if (ap_sig_175.read()) {
        ap_sig_cseq_ST_st13_fsm_12 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st13_fsm_12 = ap_const_logic_0;
    }
}

void dut_rank::thread_ap_sig_cseq_ST_st14_fsm_13() {
    if (ap_sig_260.read()) {
        ap_sig_cseq_ST_st14_fsm_13 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st14_fsm_13 = ap_const_logic_0;
    }
}

void dut_rank::thread_ap_sig_cseq_ST_st15_fsm_14() {
    if (ap_sig_268.read()) {
        ap_sig_cseq_ST_st15_fsm_14 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st15_fsm_14 = ap_const_logic_0;
    }
}

void dut_rank::thread_ap_sig_cseq_ST_st16_fsm_15() {
    if (ap_sig_221.read()) {
        ap_sig_cseq_ST_st16_fsm_15 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st16_fsm_15 = ap_const_logic_0;
    }
}

void dut_rank::thread_ap_sig_cseq_ST_st1_fsm_0() {
    if (ap_sig_33.read()) {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    }
}

void dut_rank::thread_ap_sig_cseq_ST_st2_fsm_1() {
    if (ap_sig_184.read()) {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_0;
    }
}

void dut_rank::thread_ap_sig_cseq_ST_st3_fsm_2() {
    if (ap_sig_80.read()) {
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_0;
    }
}

void dut_rank::thread_ap_sig_cseq_ST_st4_fsm_3() {
    if (ap_sig_96.read()) {
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_0;
    }
}

void dut_rank::thread_ap_sig_cseq_ST_st5_fsm_4() {
    if (ap_sig_110.read()) {
        ap_sig_cseq_ST_st5_fsm_4 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st5_fsm_4 = ap_const_logic_0;
    }
}

void dut_rank::thread_ap_sig_cseq_ST_st6_fsm_5() {
    if (ap_sig_121.read()) {
        ap_sig_cseq_ST_st6_fsm_5 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st6_fsm_5 = ap_const_logic_0;
    }
}

void dut_rank::thread_ap_sig_cseq_ST_st7_fsm_6() {
    if (ap_sig_243.read()) {
        ap_sig_cseq_ST_st7_fsm_6 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st7_fsm_6 = ap_const_logic_0;
    }
}

void dut_rank::thread_ap_sig_cseq_ST_st8_fsm_7() {
    if (ap_sig_251.read()) {
        ap_sig_cseq_ST_st8_fsm_7 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st8_fsm_7 = ap_const_logic_0;
    }
}

void dut_rank::thread_ap_sig_cseq_ST_st9_fsm_8() {
    if (ap_sig_131.read()) {
        ap_sig_cseq_ST_st9_fsm_8 = ap_const_logic_1;
    } else {
        ap_sig_cseq_ST_st9_fsm_8 = ap_const_logic_0;
    }
}

void dut_rank::thread_exitcond1_fu_339_p2() {
    exitcond1_fu_339_p2 = (!i_reg_164.read().is_01() || !ap_const_lv4_A.is_01())? sc_lv<1>(): sc_lv<1>(i_reg_164.read() == ap_const_lv4_A);
}

void dut_rank::thread_exitcond_fu_360_p2() {
    exitcond_fu_360_p2 = (!j_reg_187.read().is_01() || !ap_const_lv10_310.is_01())? sc_lv<1>(): sc_lv<1>(j_reg_187.read() == ap_const_lv10_310);
}

void dut_rank::thread_exitcond_i_fu_213_p2() {
    exitcond_i_fu_213_p2 = (!i_i_reg_151.read().is_01() || !ap_const_lv10_30F.is_01())? sc_lv<1>(): sc_lv<1>(i_i_reg_151.read() == ap_const_lv10_30F);
}

void dut_rank::thread_i_1_fu_219_p2() {
    i_1_fu_219_p2 = (!i_i_reg_151.read().is_01() || !ap_const_lv10_1.is_01())? sc_lv<10>(): (sc_biguint<10>(i_i_reg_151.read()) + sc_biguint<10>(ap_const_lv10_1));
}

void dut_rank::thread_i_2_fu_345_p2() {
    i_2_fu_345_p2 = (!i_reg_164.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(i_reg_164.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void dut_rank::thread_j_1_fu_366_p2() {
    j_1_fu_366_p2 = (!j_reg_187.read().is_01() || !ap_const_lv10_1.is_01())? sc_lv<10>(): (sc_biguint<10>(j_reg_187.read()) + sc_biguint<10>(ap_const_lv10_1));
}

void dut_rank::thread_next_mul2_fu_333_p2() {
    next_mul2_fu_333_p2 = (!phi_mul1_reg_175.read().is_01() || !ap_const_lv13_310.is_01())? sc_lv<13>(): (sc_biguint<13>(phi_mul1_reg_175.read()) + sc_biguint<13>(ap_const_lv13_310));
}

void dut_rank::thread_next_mul_fu_382_p2() {
    next_mul_fu_382_p2 = (!ap_const_lv20_310.is_01() || !phi_mul_reg_198.read().is_01())? sc_lv<20>(): (sc_biguint<20>(ap_const_lv20_310) + sc_biguint<20>(phi_mul_reg_198.read()));
}

void dut_rank::thread_notlhs3_fu_303_p2() {
    notlhs3_fu_303_p2 = (!tmp_33_fu_271_p4.read().is_01() || !ap_const_lv8_FF.is_01())? sc_lv<1>(): sc_lv<1>(tmp_33_fu_271_p4.read() != ap_const_lv8_FF);
}

void dut_rank::thread_notlhs_fu_285_p2() {
    notlhs_fu_285_p2 = (!tmp_fu_254_p4.read().is_01() || !ap_const_lv8_FF.is_01())? sc_lv<1>(): sc_lv<1>(tmp_fu_254_p4.read() != ap_const_lv8_FF);
}

void dut_rank::thread_notrhs4_fu_309_p2() {
    notrhs4_fu_309_p2 = (!tmp_32_fu_281_p1.read().is_01() || !ap_const_lv23_0.is_01())? sc_lv<1>(): sc_lv<1>(tmp_32_fu_281_p1.read() == ap_const_lv23_0);
}

void dut_rank::thread_notrhs_fu_291_p2() {
    notrhs_fu_291_p2 = (!tmp_31_fu_264_p1.read().is_01() || !ap_const_lv23_0.is_01())? sc_lv<1>(): sc_lv<1>(tmp_31_fu_264_p1.read() == ap_const_lv23_0);
}

void dut_rank::thread_phi_mul_cast_fu_356_p1() {
    phi_mul_cast_fu_356_p1 = esl_zext<21,20>(phi_mul_reg_198.read());
}

void dut_rank::thread_swap_i_phi_fu_139_p6() {
    swap_i_phi_fu_139_p6 = swap_i_reg_134.read();
}

void dut_rank::thread_tmp_29_fu_235_p1() {
    tmp_29_fu_235_p1 = PCA_sorted_idx_q0.read().range(21-1, 0);
}

void dut_rank::thread_tmp_30_fu_239_p1() {
    tmp_30_fu_239_p1 = PCA_sorted_idx_q1.read().range(21-1, 0);
}

void dut_rank::thread_tmp_31_fu_264_p1() {
    tmp_31_fu_264_p1 = S_load_to_int_fu_251_p1.read().range(23-1, 0);
}

void dut_rank::thread_tmp_32_fu_281_p1() {
    tmp_32_fu_281_p1 = S_load_1_to_int_fu_268_p1.read().range(23-1, 0);
}

void dut_rank::thread_tmp_33_fu_271_p4() {
    tmp_33_fu_271_p4 = S_load_1_to_int_fu_268_p1.read().range(30, 23);
}

void dut_rank::thread_tmp_34_fu_411_p0() {
    tmp_34_fu_411_p0 =  (sc_lv<11>) (ap_const_lv21_311);
}

void dut_rank::thread_tmp_35_fu_297_p2() {
    tmp_35_fu_297_p2 = (notrhs_fu_291_p2.read() | notlhs_fu_285_p2.read());
}

void dut_rank::thread_tmp_36_fu_315_p2() {
    tmp_36_fu_315_p2 = (notrhs4_fu_309_p2.read() | notlhs3_fu_303_p2.read());
}

void dut_rank::thread_tmp_37_fu_321_p2() {
    tmp_37_fu_321_p2 = (tmp_35_fu_297_p2.read() & tmp_36_fu_315_p2.read());
}

void dut_rank::thread_tmp_39_fu_327_p2() {
    tmp_39_fu_327_p2 = (tmp_37_fu_321_p2.read() & tmp_38_fu_209_p2.read());
}

void dut_rank::thread_tmp_40_fu_406_p0() {
    tmp_40_fu_406_p0 =  (sc_lv<11>) (ap_const_lv21_311);
}

void dut_rank::thread_tmp_41_cast_fu_372_p1() {
    tmp_41_cast_fu_372_p1 = esl_zext<13,10>(j_reg_187.read());
}

void dut_rank::thread_tmp_41_fu_388_p1() {
    tmp_41_fu_388_p1 = PCA_sorted_idx_q0.read().range(21-1, 0);
}

void dut_rank::thread_tmp_42_fu_376_p2() {
    tmp_42_fu_376_p2 = (!tmp_41_cast_fu_372_p1.read().is_01() || !phi_mul1_reg_175.read().is_01())? sc_lv<13>(): (sc_biguint<13>(tmp_41_cast_fu_372_p1.read()) + sc_biguint<13>(phi_mul1_reg_175.read()));
}

void dut_rank::thread_tmp_43_fu_392_p2() {
    tmp_43_fu_392_p2 = (!tmp_41_fu_388_p1.read().is_01() || !phi_mul_cast_reg_508.read().is_01())? sc_lv<21>(): (sc_biguint<21>(tmp_41_fu_388_p1.read()) + sc_biguint<21>(phi_mul_cast_reg_508.read()));
}

void dut_rank::thread_tmp_44_cast_fu_243_p1() {
    tmp_44_cast_fu_243_p1 = esl_sext<64,21>(tmp_34_reg_455.read());
}

void dut_rank::thread_tmp_45_cast_fu_247_p1() {
    tmp_45_cast_fu_247_p1 = esl_sext<64,21>(tmp_40_reg_460.read());
}

void dut_rank::thread_tmp_47_cast_fu_402_p1() {
    tmp_47_cast_fu_402_p1 = esl_zext<64,13>(tmp_42_reg_521.read());
}

void dut_rank::thread_tmp_49_cast_fu_397_p1() {
    tmp_49_cast_fu_397_p1 = esl_zext<64,21>(tmp_43_fu_392_p2.read());
}

void dut_rank::thread_tmp_81_i_fu_230_p1() {
    tmp_81_i_fu_230_p1 = esl_zext<64,10>(i_1_fu_219_p2.read());
}

void dut_rank::thread_tmp_fu_254_p4() {
    tmp_fu_254_p4 = S_load_to_int_fu_251_p1.read().range(30, 23);
}

void dut_rank::thread_tmp_i_fu_225_p1() {
    tmp_i_fu_225_p1 = esl_zext<64,10>(i_i_reg_151.read());
}

void dut_rank::thread_tmp_s_fu_351_p1() {
    tmp_s_fu_351_p1 = esl_zext<64,4>(i_reg_164.read());
}

void dut_rank::thread_tsf_mat_address0() {
    tsf_mat_address0 =  (sc_lv<13>) (tmp_47_cast_fu_402_p1.read());
}

void dut_rank::thread_tsf_mat_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st16_fsm_15.read())) {
        tsf_mat_ce0 = ap_const_logic_1;
    } else {
        tsf_mat_ce0 = ap_const_logic_0;
    }
}

void dut_rank::thread_tsf_mat_d0() {
    tsf_mat_d0 = U_q0.read();
}

void dut_rank::thread_tsf_mat_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_cseq_ST_st16_fsm_15.read()))) {
        tsf_mat_we0 = ap_const_logic_1;
    } else {
        tsf_mat_we0 = ap_const_logic_0;
    }
}

void dut_rank::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if (!esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) {
                ap_NS_fsm = ap_ST_st2_fsm_1;
            } else {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            }
            break;
        case 2 : 
            ap_NS_fsm = ap_ST_st3_fsm_2;
            break;
        case 4 : 
            if ((esl_seteq<1,1,1>(ap_const_lv1_0, swap_i_phi_fu_139_p6.read()) && !esl_seteq<1,1,1>(exitcond_i_fu_213_p2.read(), ap_const_lv1_0))) {
                ap_NS_fsm = ap_ST_st11_fsm_10;
            } else if ((!esl_seteq<1,1,1>(exitcond_i_fu_213_p2.read(), ap_const_lv1_0) && !esl_seteq<1,1,1>(ap_const_lv1_0, swap_i_phi_fu_139_p6.read()))) {
                ap_NS_fsm = ap_ST_st2_fsm_1;
            } else {
                ap_NS_fsm = ap_ST_st4_fsm_3;
            }
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_st5_fsm_4;
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_st6_fsm_5;
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_st7_fsm_6;
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_st8_fsm_7;
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_st9_fsm_8;
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_st10_fsm_9;
            break;
        case 512 : 
            ap_NS_fsm = ap_ST_st3_fsm_2;
            break;
        case 1024 : 
            if (!esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_339_p2.read())) {
                ap_NS_fsm = ap_ST_st1_fsm_0;
            } else {
                ap_NS_fsm = ap_ST_st12_fsm_11;
            }
            break;
        case 2048 : 
            if (esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_fu_360_p2.read())) {
                ap_NS_fsm = ap_ST_st13_fsm_12;
            } else {
                ap_NS_fsm = ap_ST_st11_fsm_10;
            }
            break;
        case 4096 : 
            ap_NS_fsm = ap_ST_st14_fsm_13;
            break;
        case 8192 : 
            ap_NS_fsm = ap_ST_st15_fsm_14;
            break;
        case 16384 : 
            ap_NS_fsm = ap_ST_st16_fsm_15;
            break;
        case 32768 : 
            ap_NS_fsm = ap_ST_st12_fsm_11;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<16>) ("XXXXXXXXXXXXXXXX");
            break;
    }
}

}

